// Static game data: attributes, positions, formations, roles, traits, nations, leagues and calendar rules.
// Clubs are in clubs.js.
(function () {
  const FM = window.FM;

  FM.D = {};

  // ---------- Attributes (1–20 scale, FM-style) ----------
  FM.D.ATTRS = [
    'pace',
    'stamina',
    'strength',
    'dribbling',
    'technique',
    'passing',
    'vision',
    'finishing',
    'tackling',
    'positioning',
    'composure',
    'workRate',
    'reflexes',
    'handling',
  ];
  FM.D.ATTR_LABEL = {
    pace: 'Pace',
    stamina: 'Stamina',
    strength: 'Strength',
    dribbling: 'Dribbling',
    technique: 'Technique',
    passing: 'Passing',
    vision: 'Vision',
    finishing: 'Finishing',
    tackling: 'Tackling',
    positioning: 'Positioning',
    composure: 'Composure',
    workRate: 'Work Rate',
    reflexes: 'Reflexes',
    handling: 'Handling',
  };
  FM.D.ATTR_GROUPS = {
    Physical: ['pace', 'stamina', 'strength', 'workRate'],
    Technical: ['dribbling', 'technique', 'passing', 'finishing', 'tackling'],
    Mental: ['vision', 'positioning', 'composure'],
    Goalkeeping: ['reflexes', 'handling'],
  };
  // A keeper's profile: shot-stopping, command of the box, distribution, then the rest
  FM.D.ATTR_GROUPS_GK = {
    Goalkeeping: ['reflexes', 'handling', 'positioning'],
    Distribution: ['passing', 'vision'],
    Mental: ['composure', 'workRate'],
    Physical: ['pace', 'strength', 'stamina'],
  };
  // Outfield skills a keeper barely uses: generated low (a top keeper finishes like a keeper, not a forward) and
  // not grown in development
  FM.D.GK_OUTFIELD = { finishing: [1, 5], tackling: [2, 6], dribbling: [3, 8], technique: [4, 9] };
  // Radar axes: label -> attrs averaged
  FM.D.RADAR = {
    Pace: ['pace'],
    Attack: ['finishing', 'composure'],
    Creativity: ['vision', 'passing'],
    Skill: ['dribbling', 'technique'],
    Defence: ['tackling', 'positioning'],
    Physical: ['strength', 'stamina', 'workRate'],
  };
  FM.D.RADAR_GK = {
    Reflexes: ['reflexes'],
    Handling: ['handling'],
    Positioning: ['positioning'],
    Distribution: ['passing'],
    Composure: ['composure'],
    Physical: ['strength', 'pace'],
  };

  // Scouting language: [elite >=17, good >=14, weak <=7]
  FM.D.PHRASES = {
    pace: ['Blistering acceleration', 'Quick across the ground', 'Lacks a yard of pace'],
    stamina: ['Tireless — runs all day', 'Good engine', 'Fades late in games'],
    strength: ['Built like a tank', 'Holds his own physically', 'Easily knocked off the ball'],
    dribbling: ['Beats players for fun', 'Comfortable running with the ball', 'Loses the ball under pressure'],
    technique: ['Silky first touch', 'Clean technique', 'Heavy touch'],
    passing: ['Pinpoint range of passing', 'Tidy, reliable passer', 'Wasteful in possession'],
    vision: ["Sees passes others don't", 'Good awareness of teammates', 'Rarely lifts his head'],
    finishing: ['Ruthless in front of goal', 'Knows where the net is', 'Snatches at chances'],
    tackling: ['Ferocious, perfectly timed tackles', 'Wins his duels', 'Rash in the challenge'],
    positioning: ['Reads the game superbly', 'Disciplined positionally', 'Often caught out of position'],
    composure: ['Ice in his veins', 'Calm on the ball', 'Panics under pressure'],
    workRate: ['Relentless presser', 'Puts a shift in', 'Coasts through games'],
    reflexes: ['Cat-like reflexes', 'Sharp shot-stopper', 'Slow to react'],
    handling: ['Safe hands', 'Dependable handling', 'Spills routine shots'],
  };

  // ---------- Positions ----------
  FM.D.POS = ['GK', 'CB', 'FB', 'WB', 'DM', 'CM', 'WM', 'AM', 'W', 'ST'];
  FM.D.POS_NAME = {
    GK: 'Goalkeeper',
    CB: 'Centre-Back',
    FB: 'Full-Back',
    DM: 'Defensive Mid',
    CM: 'Central Mid',
    AM: 'Attacking Mid',
    W: 'Winger',
    ST: 'Striker',
    WB: 'Wing-Back',
    WM: 'Wide Midfielder',
  };
  FM.D.POS_GROUP = {
    GK: 'GK',
    CB: 'DEF',
    FB: 'DEF',
    WB: 'DEF',
    DM: 'MID',
    CM: 'MID',
    WM: 'MID',
    AM: 'MID',
    W: 'ATT',
    ST: 'ATT',
  };
  // What each position's rating counts (current ability, CA, is a weighted mean of attributes times five). These weights
  // are measured from the match engine, not guessed: 150,000 simulated matches with random attributes, goal difference
  // regressed on every attribute of every position, checked against what the engine's own team-strength formulas
  // predict (js/engine.js: attack, midfield, defence and goalkeeper values). On held-out matches a team's mean rating
  // from this table explains 21% more of the goal difference than the old hand-made one did, and reaches 96% of what
  // any rating built from the attributes could. The largest weight of a position is 3; attributes under 0.2 count for nothing.
  FM.D.RATE_W = {
    GK: { reflexes: 3, positioning: 2.5, handling: 2.4, composure: 0.9, passing: 0.5 },
    CB: {
      tackling: 3,
      positioning: 2.7,
      workRate: 1.6,
      pace: 1.5,
      finishing: 1.2,
      strength: 1.1,
      passing: 1.1,
      composure: 1.1,
      technique: 0.9,
      vision: 0.9,
      stamina: 0.7,
      dribbling: 0.3,
    },
    FB: {
      positioning: 3,
      tackling: 2.9,
      technique: 2.3,
      composure: 2.2,
      pace: 1.9,
      workRate: 1.9,
      vision: 1.7,
      finishing: 1.7,
      strength: 1.6,
      passing: 1.5,
      dribbling: 0.9,
      stamina: 0.6,
    },
    WB: {
      positioning: 3,
      tackling: 2.9,
      composure: 2.8,
      finishing: 2.7,
      technique: 2.4,
      passing: 2.4,
      workRate: 1.8,
      pace: 1.6,
      vision: 1.5,
      strength: 1.2,
      stamina: 1.1,
      dribbling: 1.1,
    },
    DM: {
      positioning: 3,
      technique: 2.8,
      passing: 2.7,
      tackling: 2.6,
      vision: 2.4,
      composure: 2.4,
      workRate: 2,
      finishing: 1.9,
      pace: 1.8,
      strength: 1.4,
      stamina: 0.9,
      dribbling: 0.4,
    },
    CM: {
      technique: 3,
      passing: 2.6,
      composure: 2.6,
      vision: 2.3,
      finishing: 2.1,
      pace: 1.9,
      workRate: 1.8,
      tackling: 1.7,
      positioning: 1.7,
      dribbling: 1,
      stamina: 0.7,
      strength: 0.7,
    },
    WM: {
      composure: 3,
      technique: 2.9,
      finishing: 2.7,
      passing: 2,
      pace: 1.9,
      vision: 1.9,
      dribbling: 1.5,
      tackling: 1.4,
      positioning: 1.1,
      workRate: 1.1,
      stamina: 0.6,
      strength: 0.3,
    },
    AM: {
      finishing: 3,
      technique: 2.5,
      composure: 2.2,
      pace: 1.6,
      dribbling: 1.4,
      passing: 1.4,
      vision: 1.3,
      positioning: 1,
      tackling: 0.7,
      stamina: 0.6,
      workRate: 0.6,
      strength: 0.3,
    },
    W: {
      finishing: 3,
      composure: 2.8,
      technique: 2.3,
      dribbling: 2,
      pace: 1.7,
      passing: 1.1,
      vision: 1,
      tackling: 0.8,
      positioning: 0.7,
      workRate: 0.5,
      stamina: 0.4,
      strength: 0.2,
    },
    ST: {
      finishing: 3,
      composure: 2.3,
      dribbling: 2.1,
      technique: 2.1,
      pace: 1.9,
      passing: 1.2,
      positioning: 0.8,
      stamina: 0.7,
      vision: 0.7,
      tackling: 0.7,
      workRate: 0.5,
    },
  };
  // The rating is a weighted mean of attributes times five plus a constant for the position, which keeps it on the scale
  // the game was built on: the measured weights count more attributes, in which a typical player of a position is weaker,
  // so without it every rating would fall by 3 to 5 points (values and wages by a third). Worked out on worlds made with
  // the earlier weights, where the gap holds within about 0.3 points from a 30 to an 80 rating.
  FM.D.RATE_OFF = { GK: 0, CB: 4.1, FB: 4.9, WB: 5, DM: 4.5, CM: 4.3, WM: 4.5, AM: 4.4, W: 4.6, ST: 2.7 };
  // The shape of a position's players (what generation and development lean on, and what makes a centre-back look like
  // one): the weights the game used for ability before the rating was measured. Not the rating itself: see RATE_W.
  FM.D.POS_W = {
    GK: { reflexes: 3, handling: 3, positioning: 1.5, composure: 1, passing: 0.5 },
    CB: { tackling: 3, positioning: 3, strength: 2, pace: 1, composure: 1, passing: 0.5 },
    FB: { pace: 2, tackling: 2, positioning: 1.5, stamina: 1.5, workRate: 1, passing: 1, dribbling: 0.5 },
    // a wing-back: a full-back's defending, plus the legs and delivery to cover the whole flank
    WB: { pace: 2, tackling: 2.3, positioning: 1.8, stamina: 2, workRate: 1.5, passing: 1.2, dribbling: 1 },
    DM: { tackling: 2.5, positioning: 2, passing: 2, workRate: 1.5, stamina: 1, strength: 1, vision: 0.5 },
    CM: { passing: 2.5, vision: 2, technique: 1.5, stamina: 1.5, workRate: 1, tackling: 0.7, composure: 1 },
    // a wide midfielder: the legs and delivery to run the flank both ways, with a winger's touch and a midfielder's passing
    WM: { pace: 1.5, stamina: 2, workRate: 1.5, passing: 2, dribbling: 1.5, technique: 1.5, vision: 1, tackling: 0.5 },
    AM: { vision: 2.5, technique: 2.5, passing: 2, dribbling: 2, finishing: 1, composure: 1 },
    W: { pace: 2.5, dribbling: 2.5, technique: 1.5, passing: 1, finishing: 1, stamina: 1 },
    ST: { finishing: 3, composure: 2, pace: 1.5, strength: 1, technique: 1, dribbling: 1, positioning: 0.5 },
  };
  // How well a natural position fits a formation slot type (0–1)
  FM.D.FIT = {
    GK: { GK: 1 },
    CB: { CB: 1, DM: 0.75, FB: 0.7 },
    FB: { FB: 1, WB: 0.95, CB: 0.7, W: 0.65, WM: 0.72, DM: 0.6 },
    WB: { WB: 1, FB: 0.92, WM: 0.88, W: 0.8, CM: 0.55, DM: 0.55 },
    DM: { DM: 1, CM: 0.9, CB: 0.75, WM: 0.6 },
    CM: { CM: 1, DM: 0.85, AM: 0.85, WM: 0.84, WB: 0.55 },
    WM: { WM: 1, W: 0.92, CM: 0.85, AM: 0.82, WB: 0.85, FB: 0.72, DM: 0.6, ST: 0.6 },
    AM: { AM: 1, CM: 0.85, W: 0.8, WM: 0.82, ST: 0.75 },
    W: { W: 1, WM: 0.9, AM: 0.8, WB: 0.75, ST: 0.7, FB: 0.55 },
    ST: { ST: 1, AM: 0.75, W: 0.7 },
  };

  // ---------- Formations (x: 0 own goal → 1 opponent goal, y: 0 left → 1 right) ----------
  const GK = { t: 'GK', x: 0.04, y: 0.5 };
  FM.D.FORMATIONS = {
    '4-3-3': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'DM', x: 0.38, y: 0.5 },
      { t: 'CM', x: 0.5, y: 0.3 },
      { t: 'CM', x: 0.5, y: 0.7 },
      { t: 'W', x: 0.7, y: 0.14 },
      { t: 'ST', x: 0.76, y: 0.5 },
      { t: 'W', x: 0.7, y: 0.86 },
    ],
    '4-2-3-1': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'DM', x: 0.38, y: 0.38 },
      { t: 'DM', x: 0.38, y: 0.62 },
      { t: 'W', x: 0.62, y: 0.15 },
      { t: 'AM', x: 0.6, y: 0.5 },
      { t: 'W', x: 0.62, y: 0.85 },
      { t: 'ST', x: 0.78, y: 0.5 },
    ],
    '4-4-2': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'WM', x: 0.5, y: 0.13 },
      { t: 'CM', x: 0.45, y: 0.38 },
      { t: 'CM', x: 0.45, y: 0.62 },
      { t: 'WM', x: 0.5, y: 0.87 },
      { t: 'ST', x: 0.74, y: 0.4 },
      { t: 'ST', x: 0.74, y: 0.6 },
    ],
    '3-5-2': [
      GK,
      { t: 'CB', x: 0.2, y: 0.27 },
      { t: 'CB', x: 0.17, y: 0.5 },
      { t: 'CB', x: 0.2, y: 0.73 },
      { t: 'WB', x: 0.44, y: 0.09 },
      { t: 'DM', x: 0.36, y: 0.5 },
      { t: 'CM', x: 0.5, y: 0.32 },
      { t: 'CM', x: 0.5, y: 0.68 },
      { t: 'WB', x: 0.44, y: 0.91 },
      { t: 'ST', x: 0.75, y: 0.4 },
      { t: 'ST', x: 0.75, y: 0.6 },
    ],
    '3-4-3': [
      GK,
      { t: 'CB', x: 0.2, y: 0.27 },
      { t: 'CB', x: 0.17, y: 0.5 },
      { t: 'CB', x: 0.2, y: 0.73 },
      { t: 'WB', x: 0.46, y: 0.09 },
      { t: 'CM', x: 0.44, y: 0.38 },
      { t: 'CM', x: 0.44, y: 0.62 },
      { t: 'WB', x: 0.46, y: 0.91 },
      { t: 'W', x: 0.7, y: 0.18 },
      { t: 'ST', x: 0.77, y: 0.5 },
      { t: 'W', x: 0.7, y: 0.82 },
    ],
    '5-3-2': [
      GK,
      { t: 'WB', x: 0.3, y: 0.08 },
      { t: 'CB', x: 0.19, y: 0.3 },
      { t: 'CB', x: 0.16, y: 0.5 },
      { t: 'CB', x: 0.19, y: 0.7 },
      { t: 'WB', x: 0.3, y: 0.92 },
      { t: 'CM', x: 0.44, y: 0.3 },
      { t: 'DM', x: 0.4, y: 0.5 },
      { t: 'CM', x: 0.44, y: 0.7 },
      { t: 'ST', x: 0.7, y: 0.4 },
      { t: 'ST', x: 0.7, y: 0.6 },
    ],
    '4-1-4-1': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'DM', x: 0.36, y: 0.5 },
      { t: 'WM', x: 0.56, y: 0.13 },
      { t: 'CM', x: 0.5, y: 0.36 },
      { t: 'CM', x: 0.5, y: 0.64 },
      { t: 'WM', x: 0.56, y: 0.87 },
      { t: 'ST', x: 0.76, y: 0.5 },
    ],
    '4-4-1-1': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'WM', x: 0.5, y: 0.13 },
      { t: 'CM', x: 0.45, y: 0.38 },
      { t: 'CM', x: 0.45, y: 0.62 },
      { t: 'WM', x: 0.5, y: 0.87 },
      { t: 'AM', x: 0.64, y: 0.5 },
      { t: 'ST', x: 0.78, y: 0.5 },
    ],
    '4-1-2-1-2': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'DM', x: 0.36, y: 0.5 },
      { t: 'CM', x: 0.48, y: 0.28 },
      { t: 'CM', x: 0.48, y: 0.72 },
      { t: 'AM', x: 0.6, y: 0.5 },
      { t: 'ST', x: 0.76, y: 0.4 },
      { t: 'ST', x: 0.76, y: 0.6 },
    ],
    '4-3-1-2': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'CM', x: 0.45, y: 0.28 },
      { t: 'CM', x: 0.42, y: 0.5 },
      { t: 'CM', x: 0.45, y: 0.72 },
      { t: 'AM', x: 0.6, y: 0.5 },
      { t: 'ST', x: 0.76, y: 0.4 },
      { t: 'ST', x: 0.76, y: 0.6 },
    ],
    '3-4-2-1': [
      GK,
      { t: 'CB', x: 0.2, y: 0.27 },
      { t: 'CB', x: 0.17, y: 0.5 },
      { t: 'CB', x: 0.2, y: 0.73 },
      { t: 'WB', x: 0.44, y: 0.09 },
      { t: 'CM', x: 0.44, y: 0.38 },
      { t: 'CM', x: 0.44, y: 0.62 },
      { t: 'WB', x: 0.44, y: 0.91 },
      { t: 'AM', x: 0.64, y: 0.32 },
      { t: 'AM', x: 0.64, y: 0.68 },
      { t: 'ST', x: 0.78, y: 0.5 },
    ],
    '5-4-1': [
      GK,
      { t: 'WB', x: 0.3, y: 0.08 },
      { t: 'CB', x: 0.19, y: 0.3 },
      { t: 'CB', x: 0.16, y: 0.5 },
      { t: 'CB', x: 0.19, y: 0.7 },
      { t: 'WB', x: 0.3, y: 0.92 },
      { t: 'WM', x: 0.5, y: 0.15 },
      { t: 'CM', x: 0.44, y: 0.38 },
      { t: 'CM', x: 0.44, y: 0.62 },
      { t: 'WM', x: 0.5, y: 0.85 },
      { t: 'ST', x: 0.72, y: 0.5 },
    ],
  };
  // Slot labels with the side of the pitch (left/right from y): LB, RCB, LWB, RW, LM, ...
  FM.D.slotSide = (s) => (s.y < 0.4 ? 'L' : s.y > 0.6 ? 'R' : '');
  FM.D.slotLabel = function (s) {
    const side = FM.D.slotSide(s);
    if (s.t === 'FB') return side + 'B';
    if (s.t === 'WB') return side + 'WB';
    if (s.t === 'WM') return side + 'M';
    if (s.t === 'W') return side + 'W';
    if (s.t === 'GK' || !side) return s.t;
    return side + s.t;
  };
  FM.D.shapeOf = (f) => ({ 3: 'Back 3', 4: 'Back 4', 5: 'Back 5' })[f[0]];

  // Roles: engine modifiers (att/mid/def) + positional nudges in possession (dx, dy toward centre if 'in').
  // What each role does in the match engine: shoot = more of the side's shots fall to him, assist = more of its
  // chances are made by him, head = he wins the crosses, win = wins the ball back (the opponent keeps it less),
  // press = presses from the front (the same, at a little extra running), cross = his side crosses more,
  // inv = he wants the opposite flank to his stronger foot (cutting inside). desc = the one-line description.
  FM.D.ROLES = {
    GK: {
      Goalkeeper: { desc: 'Stays on his line and keeps it simple.' },
      'Sweeper Keeper': { mid: 0.02, dx: 0.06, risk: 0.01, desc: 'Comes off his line and starts attacks.' },
    },
    CB: {
      'Centre-Back': { def: 0.02, head: 0.2, desc: 'Defends first; a threat at corners.' },
      'Ball-Playing CB': { mid: 0.02, def: -0.01, assist: 0.1, desc: 'Steps out and breaks lines with his passing.' },
      'No-Nonsense CB': { def: 0.03, mid: -0.01, head: 0.3, desc: 'Heads it, clears it, no risks.' },
      Libero: { mid: 0.03, def: -0.02, dx: 0.12, assist: 0.15, desc: 'Steps into midfield with the ball.' },
    },
    FB: {
      'Full-Back': { def: 0.02, desc: 'Solid defensively, overlaps when it is on.' },
      'Wing-Back': { att: 0.02, def: -0.01, dx: 0.14, assist: 0.15, desc: 'Bombs on and crosses.' },
      'Inverted FB': { mid: 0.03, dx: 0.12, in: 0.28, desc: 'Tucks into midfield in possession.' },
      'No-Nonsense FB': { def: 0.03, att: -0.01, desc: 'Stays home and defends.' },
    },
    WB: {
      'Wing-Back': { att: 0.02, assist: 0.15, desc: 'Covers the whole flank and crosses.' },
      'Complete WB': { att: 0.03, def: -0.02, dx: 0.1, assist: 0.25, desc: 'Lives in the final third.' },
    },
    DM: {
      Anchor: { def: 0.03, att: -0.01, win: 0.01, desc: 'Sits in front of the defence.' },
      'Deep-Lying Playmaker': { mid: 0.03, assist: 0.25, desc: 'Dictates the tempo from deep.' },
      Regista: { mid: 0.04, def: -0.02, assist: 0.45, desc: 'A free role from deep: everything goes through him.' },
      'Ball-Winning Mid': { def: 0.02, win: 0.025, press: 0.03, desc: 'Hunts the ball and breaks up play.' },
      'Segundo Volante': { att: 0.03, def: -0.01, dx: 0.14, shoot: 0.35, desc: 'Arrives late in the box.' },
    },
    CM: {
      'Box-to-Box': { att: 0.01, def: 0.01, mid: 0.01, shoot: 0.15, desc: 'Gets up and down the pitch.' },
      Carrilero: { def: 0.02, mid: 0.01, in: -0.1, win: 0.01, desc: 'Shuttles across to cover the flank.' },
      Mezzala: {
        att: 0.03,
        def: -0.01,
        dx: 0.1,
        in: -0.12,
        shoot: 0.25,
        desc: 'Drifts into the half-space to attack.',
      },
      Playmaker: { mid: 0.03, assist: 0.3, desc: 'Keeps the ball moving and picks the pass.' },
      'Ball-Winning Mid': { def: 0.02, win: 0.025, press: 0.03, desc: 'Hunts the ball and breaks up play.' },
      'Roaming Playmaker': {
        mid: 0.02,
        att: 0.01,
        dx: 0.06,
        assist: 0.35,
        desc: 'Turns up everywhere to make the play.',
      },
    },
    AM: {
      'Advanced Playmaker': { mid: 0.03, assist: 0.4, desc: 'The creator between the lines.' },
      Trequartista: { att: 0.03, def: -0.02, assist: 0.3, shoot: 0.2, desc: 'A free role: creates and scores.' },
      Enganche: { mid: 0.04, def: -0.03, assist: 0.6, desc: 'A classic No. 10: stands still and makes the play.' },
      'Shadow Striker': { att: 0.03, dx: 0.1, shoot: 0.4, desc: 'Ghosts into the box beyond the striker.' },
    },
    W: {
      Winger: { att: 0.02, cross: 0.1, assist: 0.2, desc: 'Hugs the line, beats his man and crosses.' },
      'Inverted Winger': {
        att: 0.02,
        mid: 0.01,
        in: 0.2,
        inv: 1,
        shoot: 0.15,
        desc: 'Cuts inside onto his stronger foot.',
      },
      'Inside Forward': { att: 0.03, in: 0.25, dx: 0.06, inv: 1, shoot: 0.3, desc: 'Cuts inside to shoot.' },
      'Wide Playmaker': { mid: 0.03, in: 0.18, assist: 0.35, desc: 'Starts wide, comes inside to create.' },
      Raumdeuter: { att: 0.03, def: -0.02, dx: 0.08, shoot: 0.5, desc: 'Finds space in the box and finishes.' },
    },
    WM: {
      'Wide Mid': {
        att: 0.01,
        mid: 0.01,
        cross: 0.1,
        assist: 0.15,
        desc: 'Works the whole flank: tracks back, then supplies the box.',
      },
      'Defensive Winger': { def: 0.02, win: 0.015, press: 0.02, desc: 'Tracks back and shields his full-back.' },
      'Wide Playmaker': { mid: 0.03, in: 0.18, assist: 0.35, desc: 'Starts wide, drifts inside to create.' },
      'Inverted Wide Mid': {
        att: 0.01,
        mid: 0.01,
        in: 0.22,
        inv: 1,
        shoot: 0.12,
        desc: 'Drifts inside onto his stronger foot.',
      },
    },
    ST: {
      Poacher: { att: 0.03, dx: 0.04, shoot: 0.4, desc: 'Lives on the last defender and finishes.' },
      'Target Man': { att: 0.02, cross: 0.1, head: 0.8, desc: 'Wins it in the air; the side crosses more.' },
      'Advanced Forward': { att: 0.03, dx: 0.06, shoot: 0.3, desc: 'Runs in behind all game.' },
      'Complete Forward': { att: 0.02, mid: 0.02, shoot: 0.2, assist: 0.2, desc: 'Does everything a striker can.' },
      'False 9': {
        mid: 0.04,
        att: 0.01,
        dx: -0.14,
        assist: 0.35,
        shoot: -0.3,
        desc: 'Drops deep to link play; others score.',
      },
      'Pressing Forward': { att: 0.01, press: 0.05, desc: 'Leads the press from the front.' },
    },
  };

  FM.D.BUILDUP = ['Short', 'Direct', 'Counter', 'Possession', 'Wing Play'];
  FM.D.PRESS = ['High Press', 'Mid Block', 'Low Block'];
  FM.D.WIDTH = ['Narrow', 'Balanced', 'Wide'];

  // ---------- Traits ----------
  FM.D.TRAITS = {
    'Big Game Player': { icon: '⭐', desc: 'Raises his level in derbies and against top sides.' },
    'Injury Prone': { icon: '🩹', desc: 'Picks up knocks more often than most.' },
    'Late Bloomer': { icon: '🌱', desc: 'Keeps improving well into his mid-twenties.' },
    Loyal: { icon: '💙', desc: 'Committed to the club. Ignores outside interest.' },
    Mercenary: { icon: '💰', desc: 'Follows the money. Unsettled by bigger offers.' },
    Leader: { icon: '🎖️', desc: 'Organises and lifts teammates. Natural captain.' },
    'Media Friendly': { icon: '🎙️', desc: 'Handles the press brilliantly. Fans love him.' },
    Temperamental: { icon: '🔥', desc: 'Volatile. More cards, bigger mood swings.' },
    'Derby Specialist': { icon: '⚔️', desc: 'Lives for the derby.' },
    'Fair-Weather': { icon: '🌧️', desc: 'Hates rainy matches. Noticeably worse in the wet.' },
    Consistent: { icon: '📈', desc: 'Rarely has a bad game.' },
    Flair: { icon: '✨', desc: 'Tries the unexpected. Moments of magic.' },
  };

  // ---------- Nations ----------
  FM.D.NATIONS = {
    ENG: {
      name: 'England',
      flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
      region: 'ENG',
      style: 'Hard-working and physical',
      bias: { workRate: 2, strength: 1.5, stamina: 1 },
      fn: [
        'Jack',
        'Harry',
        'Oliver',
        'George',
        'Charlie',
        'Tom',
        'James',
        'Ben',
        'Callum',
        'Kieran',
        'Luke',
        'Ryan',
        'Jordan',
        'Mason',
        'Declan',
        'Jamie',
        'Aaron',
        'Connor',
        'Reece',
        'Lewis',
        'Dan',
        'Sam',
        'Nathan',
        'Joe',
        'Alfie',
        'Archie',
        'Kyle',
        'Marcus',
        'Ollie',
        'Ethan',
        'Tyler',
        'Rhys',
      ],
      ln: [
        'Walker',
        'Hughes',
        'Barnes',
        'Clarke',
        'Wright',
        'Turner',
        'Mitchell',
        'Cooper',
        'Ward',
        'Morris',
        'Bennett',
        'Price',
        'Fletcher',
        'Holloway',
        'Palmer',
        'Shaw',
        'Webb',
        'Gray',
        'Doyle',
        'Harding',
        'Rowe',
        'Pritchard',
        'Sutton',
        'Hale',
        'Kemp',
        'Lowe',
        'Marsh',
        'Bishop',
        'Carver',
        'Dunn',
        'Fox',
        'Goodwin',
        'Heath',
        'Knox',
        'Lambert',
        'Osei',
        'Adeyemi',
        'Campbell',
      ],
    },
    BRA: {
      name: 'Brazil',
      flag: '🇧🇷',
      region: 'SAM',
      style: 'Flair and technique',
      bias: { dribbling: 2.5, technique: 2, finishing: 1 },
      fn: [
        'Lucas',
        'Gabriel',
        'Matheus',
        'João',
        'Pedro',
        'Rafael',
        'Thiago',
        'Vinícius',
        'Caio',
        'Diego',
        'Felipe',
        'Bruno',
        'Igor',
        'Wesley',
        'Everton',
        'Rodrigo',
      ],
      ln: [
        'Silva',
        'Santos',
        'Oliveira',
        'Souza',
        'Lima',
        'Pereira',
        'Costa',
        'Ferreira',
        'Almeida',
        'Carvalho',
        'Ribeiro',
        'Gomes',
        'Barbosa',
        'Rocha',
        'Nascimento',
        'Moura',
      ],
    },
    ARG: {
      name: 'Argentina',
      flag: '🇦🇷',
      region: 'SAM',
      style: 'Street-smart competitors',
      bias: { dribbling: 1.5, vision: 1.5, composure: 1.5, tackling: 1 },
      fn: [
        'Santiago',
        'Matías',
        'Nicolás',
        'Facundo',
        'Lautaro',
        'Julián',
        'Agustín',
        'Franco',
        'Gonzalo',
        'Tomás',
        'Emiliano',
        'Valentín',
      ],
      ln: [
        'González',
        'Rodríguez',
        'Fernández',
        'López',
        'Martínez',
        'Díaz',
        'Romero',
        'Sosa',
        'Álvarez',
        'Acosta',
        'Benítez',
        'Medina',
        'Herrera',
        'Correa',
      ],
    },
    JPN: {
      name: 'Japan',
      flag: '🇯🇵',
      region: 'ASIA',
      style: 'Disciplined technicians',
      bias: { technique: 2, passing: 2, workRate: 2, strength: -1.5 },
      fn: [
        'Haruto',
        'Sota',
        'Yuto',
        'Ren',
        'Kaito',
        'Daiki',
        'Takumi',
        'Shota',
        'Ryo',
        'Kenta',
        'Hiroki',
        'Yuki',
        'Sho',
        'Kaoru',
      ],
      ln: [
        'Tanaka',
        'Suzuki',
        'Takahashi',
        'Watanabe',
        'Ito',
        'Yamamoto',
        'Nakamura',
        'Kobayashi',
        'Kato',
        'Yoshida',
        'Yamada',
        'Sasaki',
        'Matsumoto',
        'Inoue',
        'Kimura',
        'Endo',
      ],
    },
    KOR: {
      name: 'South Korea',
      flag: '🇰🇷',
      region: 'ASIA',
      style: 'Relentless engines',
      bias: { stamina: 2.5, workRate: 2.5, pace: 1 },
      fn: [
        'Ji-ho',
        'Seung-woo',
        'Hyun-jun',
        'Jae-won',
        'Do-yeon',
        'Tae-hyun',
        'Joon-ho',
        'Woo-jin',
        'Sang-hoon',
        'Dong-hyun',
      ],
      ln: ['Kim', 'Lee', 'Park', 'Choi', 'Jung', 'Kang', 'Cho', 'Yoon', 'Jang', 'Lim', 'Han', 'Oh'],
    },
    THA: {
      name: 'Thailand',
      flag: '🇹🇭',
      region: 'ASIA',
      style: 'Quick, nimble dribblers',
      bias: { pace: 1.5, dribbling: 1.5, technique: 1, strength: -2 },
      fn: [
        'Supachai',
        'Chanathip',
        'Theerathon',
        'Ekanit',
        'Suphanat',
        'Kritsada',
        'Thanawat',
        'Nattapong',
        'Pansa',
        'Weerathep',
        'Sarach',
        'Channarong',
      ],
      ln: [
        'Srisuk',
        'Bunmathan',
        'Songkrasin',
        'Chaiyawong',
        'Kaewprom',
        'Phonrat',
        'Mahawong',
        'Saengchan',
        'Thongdee',
        'Wongsa',
        'Rattanakorn',
        'Inthasen',
      ],
    },
    SRB: {
      name: 'Serbia',
      flag: '🇷🇸',
      region: 'EUR',
      style: 'Tough, uncompromising defenders',
      bias: { tackling: 2.5, strength: 2, positioning: 1.5 },
      fn: [
        'Nikola',
        'Luka',
        'Stefan',
        'Marko',
        'Aleksandar',
        'Nemanja',
        'Dušan',
        'Filip',
        'Miloš',
        'Uroš',
        'Lazar',
        'Strahinja',
      ],
      ln: [
        'Jovanović',
        'Petrović',
        'Nikolić',
        'Marković',
        'Đorđević',
        'Stojanović',
        'Ilić',
        'Pavlović',
        'Milošević',
        'Stanković',
        'Kostić',
        'Lukić',
      ],
    },
    FRA: {
      name: 'France',
      flag: '🇫🇷',
      region: 'EUR',
      style: 'Elite athletes',
      bias: { pace: 2.5, strength: 2, stamina: 1.5 },
      fn: [
        'Hugo',
        'Théo',
        'Lucas',
        'Mathis',
        'Nathan',
        'Enzo',
        'Maxime',
        'Antoine',
        'Yanis',
        'Rayan',
        'Moussa',
        'Ibrahima',
        'Jules',
        'Clément',
      ],
      ln: [
        'Martin',
        'Bernard',
        'Dubois',
        'Moreau',
        'Laurent',
        'Lefebvre',
        'Fofana',
        'Diallo',
        'Camara',
        'Traoré',
        'Mendy',
        'Girard',
        'Mercier',
        'Blanc',
      ],
    },
    ESP: {
      name: 'Spain',
      flag: '🇪🇸',
      region: 'EUR',
      style: 'Positional play specialists',
      bias: { passing: 2.5, vision: 2, technique: 2, strength: -1 },
      fn: ['Pablo', 'Sergio', 'Álvaro', 'Javier', 'Iker', 'Hugo', 'Adrián', 'Marcos', 'Rubén', 'Dani'],
      ln: [
        'García',
        'Martín',
        'Sánchez',
        'Ruiz',
        'Moreno',
        'Muñoz',
        'Navarro',
        'Torres',
        'Ramos',
        'Gil',
        'Vidal',
        'Serrano',
      ],
    },
    NGA: {
      name: 'Nigeria',
      flag: '🇳🇬',
      region: 'AFR',
      style: 'Explosive athletes',
      bias: { pace: 2.5, strength: 2, dribbling: 1 },
      fn: [
        'Chidi',
        'Emeka',
        'Samuel',
        'Victor',
        'Ahmed',
        'Tunde',
        'Kelechi',
        'Uche',
        'Ifeanyi',
        'Taiwo',
        'Wilfred',
        'Ademola',
      ],
      ln: [
        'Okafor',
        'Adeyemi',
        'Nwosu',
        'Balogun',
        'Eze',
        'Okonkwo',
        'Obi',
        'Adebayo',
        'Chukwu',
        'Ogunleye',
        'Musa',
        'Ndidi',
      ],
    },
  };
  // More nations so league squads look like real leagues (fictional name combinations)
  const addN = (code, name, flag, region, style, bias, fn, ln) =>
    (FM.D.NATIONS[code] = {
      name,
      flag,
      region,
      style,
      bias,
      fn: fn.split(' '),
      ln: ln.split(',').map((x) => x.trim()),
    });
  // Add first names (space-separated) and surnames (comma-separated) to a nation, skipping ones it already has
  FM.D.addNames = (c, fn, ln) => {
    const N = FM.D.NATIONS[c];
    fn.split(' ').forEach((x) => x && !N.fn.includes(x) && N.fn.push(x));
    ln.split(',')
      .map((x) => x.trim())
      .forEach((x) => x && !N.ln.includes(x) && N.ln.push(x));
  };
  addN(
    'POR',
    'Portugal',
    '🇵🇹',
    'EUR',
    'Technical, inventive',
    { dribbling: 1.5, technique: 1.5, passing: 1 },
    'João Diogo Rúben Tiago Gonçalo André Rafael Nuno Vitor Francisco Pedro Hugo',
    'Pereira, Carvalho, Mendes, Tavares, Correia, Pinto, Moreira, Lopes, Cardoso, Teixeira, Neves, Ramalho, Antunes, Fonseca',
  );
  addN(
    'NED',
    'Netherlands',
    '🇳🇱',
    'EUR',
    'Total-football passers',
    { passing: 2, vision: 1.5, technique: 1 },
    'Daan Sem Lars Bram Thijs Jesse Ruben Stijn Joris Milan Luuk Niels',
    'de Jong, Jansen, de Vries, van den Berg, Bakker, Visser, Smit, Meijer, de Boer, Mulder, Bos, Vos, Hendriks, Kuipers',
  );
  addN(
    'GER',
    'Germany',
    '🇩🇪',
    'EUR',
    'Disciplined and organised',
    { positioning: 1.5, workRate: 1.5, composure: 1.5 },
    'Lukas Leon Jonas Felix Maximilian Niklas Tim Jan Florian Moritz Julian Kai',
    'Schmidt, Schneider, Fischer, Weber, Wagner, Becker, Hoffmann, Koch, Richter, Klein, Wolf, Schröder, Neumann, Braun',
  );
  addN(
    'BEL',
    'Belgium',
    '🇧🇪',
    'EUR',
    'Golden-generation technicians',
    { technique: 1.5, vision: 1 },
    'Arne Wout Jens Thibault Lucas Mathis Siebe Senne Romain Jordan',
    'Peeters, Janssens, Maes, Jacobs, Willems, Claes, Goossens, Wouters, De Smet, Lambrecht, Verbeke, Michiels',
  );
  addN(
    'IRL',
    'Ireland',
    '🇮🇪',
    'ENG',
    'Committed and physical',
    { workRate: 2, strength: 1.5 },
    'Seán Conor Cian Darragh Oisín Ciarán Jamie Evan Adam Kevin Shane Ryan',
    "Murphy, Kelly, O'Brien, Byrne, O'Connor, Walsh, McCarthy, Gallagher, Kennedy, Brennan, Nolan, Duffy, Farrell, Quinn",
  );
  addN(
    'SCO',
    'Scotland',
    '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'ENG',
    'Tenacious competitors',
    { workRate: 2, tackling: 1 },
    'Callum Ross Euan Lewis Fraser Craig Scott Kyle Grant Stuart Jamie Liam',
    'MacDonald, Stewart, Anderson, Fraser, Reid, Ross, Murray, McKenzie, Paterson, Gillespie, Hamilton, Munro, Buchanan, Crawford',
  );
  addN(
    'WAL',
    'Wales',
    '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'ENG',
    'Hard-running and honest',
    { workRate: 1.5, stamina: 1 },
    'Rhys Dylan Gethin Owain Iwan Aled Cai Dafydd Tomos Rhodri',
    'Jones, Williams, Davies, Evans, Thomas, Roberts, Lewis, Morgan, Griffiths, Owen, Pugh, Llewellyn',
  );
  addN(
    'URU',
    'Uruguay',
    '🇺🇾',
    'SAM',
    'Garra charrúa — fierce defenders',
    { tackling: 2, composure: 1, strength: 1 },
    'Facundo Nahitan Maximiliano Agustín Brian Mathías Diego Sebastián Nicolás Gastón',
    'Olivera, Pereiro, Cabrera, Viñas, Silvera, Méndez, Acevedo, Laborda, Gutiérrez, Ferreira, Techera, Rolán',
  );
  addN(
    'COL',
    'Colombia',
    '🇨🇴',
    'SAM',
    'Rhythm and flair',
    { dribbling: 2, pace: 1.5 },
    'Andrés Carlos Jhon Santiago Camilo Daniel Jefferson Wilmar Stiven Kevin Yeison Duván',
    'Castaño, Borja, Arias, Palacios, Mosquera, Valencia, Cardona, Rentería, Quiñones, Hurtado, Guerrero, Murillo',
  );
  addN(
    'SEN',
    'Senegal',
    '🇸🇳',
    'AFR',
    'Powerful and quick',
    { pace: 2, strength: 2 },
    'Moussa Cheikh Pape Mamadou Ibrahima Abdou Youssouf Lamine Ousmane Aliou Babacar Modou',
    'Diop, Ndiaye, Fall, Cissé, Mbaye, Faye, Sow, Seck, Niang, Thiam, Badji, Ba',
  );
  addN(
    'GHA',
    'Ghana',
    '🇬🇭',
    'AFR',
    'Athletic and energetic',
    { pace: 2, strength: 1.5, workRate: 1 },
    'Kwame Kofi Yaw Kwabena Kwasi Samuel Emmanuel Isaac Joseph Abdul Richmond Kojo',
    'Mensah, Asante, Owusu, Appiah, Agyemang, Amoah, Adjei, Darko, Opoku, Ofori, Acheampong, Boakye',
  );
  addN(
    'CIV',
    'Ivory Coast',
    '🇨🇮',
    'AFR',
    'Explosive dribblers',
    { pace: 2, dribbling: 1.5, strength: 1 },
    'Yao Serge Jean Franck Ibrahim Seko Simon Evann Oumar Christian Arsène Hamed',
    'Koné, Kouassi, Bamba, Coulibaly, Ouattara, Diomandé, Kouamé, Doumbia, Gbamin, Konan, Yapi, Zoro',
  );
  addN(
    'MAR',
    'Morocco',
    '🇲🇦',
    'AFR',
    'Silky technicians',
    { technique: 2, dribbling: 1.5 },
    'Youssef Hamza Amine Ilias Soufiane Zakaria Anass Bilal Oussama Ayoub Nayef Adam',
    'El Amrani, Benali, Bennani, El Idrissi, Tazi, Alaoui, Berrada, Chakir, Lamrani, Haddadi, El Fassi, Ouazzani',
  );
  addN(
    'USA',
    'United States',
    '🇺🇸',
    'NAM',
    'Athletic, tireless',
    { stamina: 2, workRate: 1.5, pace: 1 },
    'Tyler Brandon Chris Josh Brenden Caleb Jordan Miles Gio Cole Austin Zack',
    'Johnson, Miller, Smith, Brown, Davis, Wilson, Moore, Taylor, Jackson, Harris, Clark, Parker, Reyes, Bennett',
  );
  addN(
    'DEN',
    'Denmark',
    '🇩🇰',
    'EUR',
    'Smart, composed',
    { positioning: 1.5, passing: 1, strength: 1 },
    'Mads Mikkel Rasmus Frederik Oliver Magnus Emil Jonas Kasper Mathias',
    'Nielsen, Jensen, Hansen, Pedersen, Larsen, Sørensen, Rasmussen, Poulsen, Madsen, Kristensen, Holm, Skov',
  );
  addN(
    'NOR',
    'Norway',
    '🇳🇴',
    'EUR',
    'Strong and durable',
    { strength: 1.5, stamina: 1.5, workRate: 1 },
    'Sander Martin Kristian Magnus Jonas Henrik Eirik Sindre Håkon Tobias Fredrik Ola',
    'Johansen, Olsen, Berg, Haugen, Dahl, Lund, Strand, Solberg, Bakken, Aas, Moen, Nygård',
  );
  addN(
    'CRO',
    'Croatia',
    '🇭🇷',
    'EUR',
    'Midfield masters',
    { technique: 1.5, vision: 1.5, composure: 1 },
    'Ivan Mateo Marko Josip Ante Nikola Dominik Filip Petar Mario Lovro Toma',
    'Horvat, Kovačević, Babić, Marić, Jurić, Knežević, Vuković, Perić, Pavić, Kolar, Božić, Grgić',
  );
  addN(
    'ITA',
    'Italy',
    '🇮🇹',
    'EUR',
    'Tactically astute defenders',
    { positioning: 2, tackling: 1.5, composure: 1 },
    'Lorenzo Matteo Alessandro Davide Andrea Riccardo Giacomo Simone Nicolò Gianluca Tommaso Edoardo',
    'Rossi, Russo, Ferrari, Esposito, Bianchi, Romano, Colombo, Ricci, Marino, Greco, Gallo, Conti',
  );

  FM.D.REGIONS = {
    ENG: 'British Isles',
    EUR: 'Europe',
    SAM: 'South America',
    NAM: 'North America',
    ASIA: 'Asia',
    AFR: 'Africa',
  };

  // Realistic nationality mix per league (weights ≈ % of squads) and per academy
  FM.D.NAT_MIX = {
    D1: {
      ENG: 38,
      FRA: 6,
      ESP: 5,
      POR: 5,
      BRA: 5,
      NED: 4,
      BEL: 3,
      GER: 3,
      ARG: 3,
      IRL: 3,
      SCO: 3,
      WAL: 2,
      NGA: 2,
      GHA: 2,
      SEN: 2,
      CIV: 2,
      DEN: 2,
      NOR: 2,
      JPN: 1.5,
      KOR: 1.5,
      USA: 1.5,
      URU: 1,
      COL: 1,
      MAR: 1,
      CRO: 1,
      SRB: 1,
      ITA: 1,
    },
    D2: {
      ENG: 60,
      IRL: 6,
      SCO: 5,
      WAL: 5,
      NED: 2,
      NGA: 2,
      GHA: 2,
      FRA: 2,
      DEN: 2,
      NOR: 2,
      USA: 2,
      JPN: 1,
      POR: 1,
      ESP: 1,
      BEL: 1,
      CIV: 1,
      SEN: 1,
      KOR: 1,
    },
    D3: { ENG: 72, IRL: 6, SCO: 6, WAL: 6, NGA: 2, GHA: 2, JPN: 1, USA: 1, NED: 1, DEN: 1, NOR: 1, FRA: 1 },
    ES2: { ESP: 76, ARG: 5, URU: 3, COL: 3, MAR: 3, BRA: 3, POR: 2, SEN: 1, FRA: 1, ITA: 1, SRB: 1, CRO: 1 },
    DE1: {
      GER: 52,
      FRA: 5,
      NED: 4,
      DEN: 3,
      NOR: 3,
      SRB: 3,
      CRO: 3,
      BRA: 3,
      JPN: 3,
      POR: 2,
      ESP: 2,
      KOR: 2,
      USA: 2,
      SEN: 2,
      CIV: 2,
      GHA: 2,
      ENG: 2,
      BEL: 2,
      ITA: 1,
      MAR: 1,
    },
    FR1: {
      FRA: 55,
      SEN: 5,
      CIV: 5,
      MAR: 4,
      BRA: 3,
      POR: 3,
      BEL: 3,
      ARG: 2,
      NGA: 2,
      GHA: 2,
      ESP: 2,
      NED: 1,
      GER: 1,
      CRO: 1,
      SRB: 1,
      JPN: 1,
      KOR: 1,
      USA: 1,
      URU: 1,
      COL: 1,
      ITA: 1,
    },
    BR1: { BRA: 86, ARG: 5, URU: 3, COL: 3, POR: 1, USA: 1, JPN: 1 },
    ES1: {
      ESP: 60,
      ARG: 6,
      BRA: 5,
      FRA: 4,
      URU: 3,
      POR: 3,
      COL: 3,
      MAR: 3,
      SEN: 1.5,
      NGA: 1,
      GER: 1,
      NED: 1,
      JPN: 1,
      KOR: 1,
      CRO: 1,
      SRB: 1,
      ITA: 1,
      ENG: 1,
      BEL: 1,
    },
  };
  FM.D.YOUTH_MIX = {
    ENG: { ENG: 84, IRL: 4, SCO: 3, WAL: 3, NGA: 1.5, GHA: 1.5, FRA: 1, POR: 1, JPN: 0.5, KOR: 0.5 },
    ESP: { ESP: 86, ARG: 3, MAR: 3, BRA: 2, COL: 2, URU: 1.5, POR: 1.5, SEN: 1 },
    GER: { GER: 88, CRO: 2, SRB: 2, GHA: 2, NED: 1, DEN: 1, USA: 1, KOR: 1, ITA: 1, FRA: 1 },
    FRA: { FRA: 82, SEN: 4, CIV: 4, MAR: 3, GHA: 2, POR: 2, BEL: 2, NGA: 1 },
    BRA: { BRA: 96, ARG: 2, URU: 1, COL: 1 },
  };

  // Hispanic naming uses two surnames when a combination is taken; others use a double-barrelled name
  FM.D.TWO_SURNAMES = ['ESP', 'ARG', 'URU', 'COL', 'POR', 'BRA'];

  FM.D.pickNat = (mix) => FM.U.wpick(Object.keys(mix), (k) => mix[k]);

  // Pre-season: friendlies and camps (3 pre-season slots)
  FM.D.CAMPS = {
    fitness: {
      name: 'Alpine fitness camp',
      icon: '🏔️',
      cost: 6e5,
      desc: 'Sharpens fitness and stamina. Everyone starts the season at 100%.',
    },
    tactical: {
      name: 'Tactical camp',
      icon: '🧠',
      cost: 4e5,
      desc: 'Drills your system. Big boost to tactical familiarity.',
    },
    youth: {
      name: 'Youth development camp',
      icon: '🌱',
      cost: 3e5,
      desc: 'Intensive coaching for players aged 21 and under.',
    },
    tour: {
      name: 'Commercial tour of Asia',
      icon: '✈️',
      cost: -2.5e6,
      desc: 'Earns money and new fans, but the travel tires the squad.',
    },
  };
  FM.D.PRESEASON_DAYS = 3;

  FM.D.STAFF_ROLES = {
    'Assistant Manager': { key: 'assistant', effect: 'Sharper advice on selection, tactics and the squad' },
    'First-Team Coach': { key: 'coach', effect: 'Faster player development' },
    'Head of Analytics': { key: 'analyst', effect: 'Moneyball insights and deeper post-match analysis' },
    'Head Physio': { key: 'physio', effect: 'Shorter injury layoffs' },
    'Sporting Director': { key: 'director', effect: 'Negotiates lower fees and wages' },
    Scout: { key: 'scout', effect: 'Finds and assesses players' },
  };

  // ---------- Club identities (drive board objectives + fan culture) ----------
  FM.D.IDENTITY = {
    oil: {
      label: 'Oil-Backed',
      icon: '🛢️',
      fans: 'Trophies. Nothing else matters.',
      budget: 2.0,
      sell: 1.6,
      obj: 'title',
    },
    giant: {
      label: 'Historic Giant',
      icon: '🏛️',
      fans: 'Expect to challenge for the title every season.',
      budget: 1.6,
      sell: 1.3,
      obj: 'top2',
    },
    historic: {
      label: 'Proud History',
      icon: '📜',
      fans: 'Want European nights and a top-half finish.',
      budget: 1.1,
      sell: 1.1,
      obj: 'tophalf',
    },
    fan: {
      label: 'Fan-Owned',
      icon: '🤝',
      fans: 'Demand attacking football and a club that lives within its means.',
      budget: 0.8,
      sell: 1.0,
      obj: 'attack',
    },
    youth: {
      label: 'Youth-Focused',
      icon: '🌱',
      fans: 'Love seeing academy kids get their chance.',
      budget: 0.8,
      sell: 1.0,
      obj: 'youth',
    },
    selling: {
      label: 'Selling Club',
      icon: '💼',
      fans: 'Accept sales — if you find the next gem.',
      budget: 0.9,
      sell: 0.85,
      obj: 'profit',
    },
    fallen: {
      label: 'Fallen Giant',
      icon: '🏚️',
      fans: 'Desperate for a return to former glory.',
      budget: 1.2,
      sell: 1.2,
      obj: 'rise',
    },
  };

  // National team kit colours
  FM.D.NT_COLORS = {
    ENG: ['#FFFFFF', '#CE1124'],
    BRA: ['#FFDF00', '#009C3B'],
    ARG: ['#75AADB', '#FFFFFF'],
    JPN: ['#1B2A6B', '#FFFFFF'],
    KOR: ['#C60C30', '#003478'],
    THA: ['#241D4F', '#A51931'],
    SRB: ['#C6363C', '#0C4076'],
    FRA: ['#002654', '#ED2939'],
    ESP: ['#AA151B', '#F1BF00'],
    NGA: ['#008751', '#FFFFFF'],
    POR: ['#8B0000', '#006600'],
    NED: ['#FF6600', '#FFFFFF'],
    GER: ['#FFFFFF', '#000000'],
    BEL: ['#E30613', '#000000'],
    IRL: ['#169B62', '#FFFFFF'],
    SCO: ['#0065BF', '#FFFFFF'],
    WAL: ['#C8102E', '#00B140'],
    URU: ['#5CBFEB', '#000000'],
    COL: ['#FCD116', '#003893'],
    SEN: ['#FFFFFF', '#00853F'],
    GHA: ['#FFFFFF', '#006B3F'],
    CIV: ['#F77F00', '#009E60'],
    MAR: ['#C1272D', '#006233'],
    USA: ['#FFFFFF', '#0A3161'],
    DEN: ['#C8102E', '#FFFFFF'],
    NOR: ['#BA0C2F', '#00205B'],
    CRO: ['#FF0000', '#FFFFFF'],
    ITA: ['#0066B3', '#FFFFFF'],
  };

  FM.D.CHANTS = [
    '"We\'re the pride of {city}, we\'ll never be moved!"',
    '"{short} till I die!"',
    '"Oh {city}, we love you!"',
    '"Glory, glory {nick}!"',
    '"Stand up for the {nick}!"',
  ];
  FM.D.TRADITIONS = [
    'Players walk out to a brass band',
    'Fans hold up scarves for the anthem before kick-off',
    'The home end sings through the whole 12th minute',
    "A minute's applause for every departing legend",
    'Kids get in for next to nothing on derby day',
  ];

  // Staff
  FM.D.STAFF_PERSONALITY = ['Pragmatic', 'Old-School', 'Innovative', 'Outspoken', 'Loyal', 'Cautious', 'Ambitious'];

  FM.D.WEATHER = [
    ['Clear', '☀️', 0.55],
    ['Cloudy', '☁️', 0.2],
    ['Rain', '🌧️', 0.2],
    ['Snow', '❄️', 0.05],
    ['Hot', '🥵', 0],
  ];
  // Climate by nation: wet (more rain), cold (snow in midwinter), warm (hot at the start and end of the
  // season), tropical (often hot, never snow)
  FM.D.CLIMATE = {
    wet: ['ENG', 'SCO', 'WAL', 'IRL', 'NED', 'BEL', 'NOR', 'DEN', 'GER'],
    cold: ['NOR', 'DEN', 'POL', 'CZE', 'AUT', 'SUI', 'SRB', 'GER', 'KOR', 'SCO', 'USA', 'HUN'],
    warm: ['ESP', 'POR', 'ITA', 'GRE', 'TUR', 'MAR', 'ARG', 'URU', 'USA', 'JPN', 'KOR', 'FRA', 'AUS'],
    tropical: ['BRA', 'THA', 'NGA', 'MEX', 'COL', 'GHA', 'CIV', 'SEN'],
  };

  FM.D.SEASON_START = 2026;
  FM.D.WINDOW_ROUNDS = [0, 1, 2, 3, 11, 12, 13]; // transfer window open around these league rounds
  FM.D.YOUTH_ROUND = 16;
  // Calendar: cup days slot in after these league rounds (0-based)
  FM.D.CUP_AFTER = { 1: 'DC', 4: 'DC', 7: 'DC', 11: 'DC', 15: 'DC', 19: 'DC' }; // six rounds: 36 English clubs need a first round
  // Knockout stages are two-legged when the world rule is on (QF1/QF2, SF1/SF2); otherwise the "2" days are dropped
  FM.D.CC_AFTER = {
    2: 'G1',
    5: 'G2',
    8: 'G3',
    10: 'G4',
    13: 'G5',
    16: 'G6',
    17: 'QF1',
    18: 'QF2',
    19: 'SF1',
    20: 'SF2',
    21: 'F',
  };
  FM.D.CWC_AFTER = { 9: 'QF', 12: 'SF', 14: 'F' }; // Club World Cup, mid-season
  // Every international break has two matchdays
  FM.D.INTL_AFTER = { 7: ['I1a', 'I1b'], 15: ['I2a', 'I2b'] };
  // Wages were tuned against a 43-day season; longer calendars pay the same season total
  FM.D.WAGE_WEEKS = 43;

  // ---------- Alpha 1: Mexico ----------
  addN(
    'MEX',
    'Mexico',
    '🇲🇽',
    'NAM',
    'Quick, combative technicians',
    { technique: 1.5, pace: 1, workRate: 1 },
    'José Luis Carlos Juan Miguel Diego Jesús Héctor Andrés Edson Hirving Raúl Orbelín Uriel Alexis Santiago Érick César Julián Fernando Emilio Rodrigo Iván Gerardo Marco Víctor Omar Ángel',
    'Hernández, García, Martínez, López, González, Rodríguez, Sánchez, Ramírez, Cruz, Flores, Gómez, Morales, Vázquez, Reyes, Jiménez, Torres, Díaz, Gutiérrez, Ruiz, Mendoza, Aguilar, Ortiz, Castillo, Romero, Chávez, Rivera, Juárez, Domínguez, Vargas, Guzmán, Salazar, Esquivel, Orozco, Cervantes, Navarro, Montes',
  );
  FM.D.NT_COLORS.MEX = ['#006847', '#FFFFFF'];
  FM.D.TWO_SURNAMES.push('MEX');

  // ---------- More nations: the next European leagues by coefficient ----------
  addN(
    'TUR',
    'Turkey',
    '🇹🇷',
    'EUR',
    'Passionate, direct and aggressive',
    { workRate: 1.5, strength: 1, dribbling: 1 },
    'Emre Burak Mert Can Arda Kerem Oğuz Barış Cengiz Hakan Ozan Yusuf Berkay Serdar Umut Ömer Kaan Efe Alper Onur Tolga Cenk Volkan Egemen Selim Furkan Batuhan Enes Doğukan Halil Semih Kerim Ahmet Mehmet Ali Deniz Tuna Uğur Eren Irfan',
    'Yılmaz, Kaya, Demir, Şahin, Çelik, Yıldız, Yıldırım, Öztürk, Aydın, Özdemir, Arslan, Doğan, Kılıç, Aslan, Çetin, Kara, Koç, Kurt, Özkan, Şimşek, Polat, Korkmaz, Karaca, Erdem, Güneş, Aktaş, Bulut, Keskin, Ünal, Tekin, Akın, Uçar, Gül, Avcı, Taş, Sarı, Coşkun, Bozkurt, Kaplan, Özer, Tunç, Durmaz, Başaran, Karagöz, Ekici, Ateş, Işık, Soylu',
  );
  addN(
    'CZE',
    'Czechia',
    '🇨🇿',
    'EUR',
    'Industrious and well-drilled',
    { workRate: 1.5, positioning: 1, stamina: 1 },
    'Jan Jakub Tomáš Lukáš Ondřej Adam Matěj Filip Vojtěch David Petr Martin Michal Pavel Daniel Václav Josef Radim Tadeáš Šimon Dominik Marek Vladimír Antonín Štěpán Jiří Roman Aleš Libor Patrik Denis Robin Kryštof Vít Zdeněk Karel Hynek Mojmír Dalibor Bořek',
    'Novák, Svoboda, Novotný, Dvořák, Černý, Procházka, Kučera, Veselý, Horák, Němec, Pokorný, Marek, Pospíšil, Hájek, Jelínek, Král, Růžička, Beneš, Fiala, Sedláček, Doležal, Zeman, Kolář, Navrátil, Čermák, Urban, Vaněk, Blažek, Kříž, Kovář, Bartoš, Vlček, Polák, Musil, Kopecký, Šimek, Konečný, Malý, Holub, Štěpánek, Kadlec, Staněk, Soukup, Holý, Bureš, Jaroš, Richter, Moravec',
  );
  addN(
    'GRE',
    'Greece',
    '🇬🇷',
    'EUR',
    'Organised, resilient defenders',
    { positioning: 1.5, tackling: 1.5, strength: 1 },
    'Giorgos Dimitris Nikos Kostas Giannis Christos Vasilis Panagiotis Thanasis Michalis Stelios Sotiris Antonis Manolis Lefteris Apostolos Charalampos Konstantinos Alexandros Stavros Spyros Andreas Petros Pavlos Ilias Theodoros Fotis Marios Anastasios Evangelos Tasos Vangelis Lazaros Savvas Aris Achilleas Zisis Orestis Anestis Prodromos',
    'Papadopoulos, Papadakis, Georgiou, Oikonomou, Pappas, Vlachos, Nikolaidis, Dimitriou, Konstantinidis, Karagiannis, Athanasiou, Christodoulou, Ioannidis, Makris, Vasileiou, Antoniou, Papanikolaou, Alexiou, Stavrou, Kyriakidis, Theodorou, Michailidis, Economou, Lazaridis, Panagiotou, Spanos, Katsaros, Mavridis, Tsakalos, Zervas, Anagnostou, Sotiriou, Galanis, Petridis, Chatzis, Rigas, Voulgaris, Kontos, Tzavaras, Liakos, Marinos, Kalogeropoulos, Lamprou',
  );
  addN(
    'POL',
    'Poland',
    '🇵🇱',
    'EUR',
    'Strong, honest and direct',
    { strength: 1.5, workRate: 1.5, finishing: 1 },
    'Jakub Kacper Szymon Mateusz Bartosz Kamil Michał Paweł Piotr Krzysztof Tomasz Łukasz Dawid Adrian Marcin Patryk Damian Sebastian Przemysław Grzegorz Wojciech Maciej Filip Karol Hubert Oskar Igor Mikołaj Dominik Antoni Wiktor Jan Adam Konrad Rafał Arkadiusz Norbert Kornel Bartłomiej Radosław',
    'Nowak, Kowalski, Wiśniewski, Wójcik, Kowalczyk, Kamiński, Lewandowicz, Zieliński, Szymański, Woźniak, Dąbrowski, Kozłowski, Jankowski, Mazur, Kwiatkowski, Krawczyk, Kaczmarek, Piotrowski, Grabowski, Zając, Pawłowski, Michalski, Król, Wieczorek, Jabłoński, Wróbel, Nowakowski, Majewski, Olszewski, Stępień, Malinowski, Jaworski, Adamczyk, Dudek, Nowicki, Pawlak, Górski, Witkowski, Walczak, Sikora, Baran, Rutkowski, Michalak, Szewczyk, Ostrowski, Tomaszewski, Pietrzak, Duda',
  );
  addN(
    'AUT',
    'Austria',
    '🇦🇹',
    'EUR',
    'High-energy pressers',
    { workRate: 2, stamina: 1.5, pace: 0.5 },
    'Lukas David Florian Tobias Julian Stefan Christoph Dominik Philipp Matthias Andreas Michael Patrick Alexander Marco Kevin Fabian Maximilian Simon Sebastian Raphael Nicolas Konrad Leopold Valentin Moritz Jakob Elias Felix Samuel Benedikt Lorenz Clemens Paul Nico Marcel Manuel Thomas Georg Severin',
    'Gruber, Huber, Bauer, Wagner, Müller, Pichler, Steiner, Moser, Mayer, Hofer, Leitner, Berger, Fuchs, Eder, Fischer, Schmid, Winkler, Weber, Schwarz, Maier, Schneider, Reiter, Mayr, Schmidt, Wimmer, Egger, Brunner, Lang, Baumgartner, Auer, Binder, Lechner, Wolf, Wallner, Aigner, Ebner, Koller, Lehner, Haas, Schuster, Holzer, Kogler, Resch, Strasser, Pölzl, Grill, Posch, Seidl',
  );
  addN(
    'SUI',
    'Switzerland',
    '🇨🇭',
    'EUR',
    'Tidy, versatile and composed',
    { composure: 1.5, passing: 1, positioning: 1 },
    'Luca Noah Leon Nico Jan Fabian Kevin Yannick Cédric Florian Joël Silvan Remo Dario Marco Loris Nils Andrin Gian Ramon Mauro Samuel Timo Reto Beat Michel Simon Jonas Elias Lars Levin Aurèle Matteo Bastien Gaël Théo Kilian Ruben Dominik Pascal',
    'Müller, Meier, Schmid, Keller, Weber, Huber, Schneider, Meyer, Steiner, Fischer, Gerber, Brunner, Baumann, Frei, Zimmermann, Moser, Widmer, Wyss, Graf, Roth, Suter, Baumgartner, Kälin, Bühler, Aebischer, Zbinden, Marti, Lüthi, Gisler, Egli, Imhof, Studer, Ammann, Hofmann, Kunz, Blaser, Bachmann, Hess, Rossier, Favre, Perrin, Bonvin, Morand, Rochat, Chappuis, Bernasconi, Rossi, Bianchi',
  );
  addN(
    'AUS',
    'Australia',
    '🇦🇺',
    'ASIA',
    'Athletic and direct',
    { stamina: 1.5, strength: 1.5, workRate: 1 },
    'Jack Riley Harrison Mitchell Connor Cooper Lachlan Tom Nathan Jordan Ryan Callum Josh Mathew Aiden Kye Brandon Daniel Ben Bailey Liam Lucas Cameron Noah Kai Jayden Dylan Trent Corey Tyrese Marco Ajdin Keanu Kusini Alessandro Garang Nestory Awer Apostolos',
    'Smith, Jones, Williams, Brown, Wilson, Taylor, Anderson, Thompson, Walker, White, Harris, Martin, Robinson, Clarke, Scott, Young, Mitchell, Ryan, Kelly, Evans, Murray, Hughes, Russo, Rossi, Santos, Nikolic, Ivanovic, Kovac, Petrovic, Papadopoulos, Tran, Nguyen, Wang, Singh, Cummings, McGree, Irvine, Boyle, Souttar, Hrustic, Duke, Metcalfe, Degenek, Burgess, Atkinson, Circati, Deng, Yengi',
  );
  addN(
    'HUN',
    'Hungary',
    '🇭🇺',
    'EUR',
    'Technical and disciplined',
    { technique: 1.5, passing: 1, positioning: 1 },
    'Bence Dominik Ádám Péter Máté Zsolt Gergő Dávid Balázs Levente Kristóf Márk Attila Roland Norbert Tamás Richárd Martin Csaba Zoltán László Krisztián Milán Botond Barnabás Olivér Patrik Szabolcs Gábor Bálint Zalán Áron Benedek Kornél Ákos András István Viktor Dénes Soma',
    'Nagy, Kovács, Tóth, Szabó, Horváth, Varga, Kiss, Molnár, Németh, Farkas, Balogh, Papp, Takács, Juhász, Lakatos, Mészáros, Oláh, Simon, Rácz, Fekete, Szilágyi, Török, Fehér, Balázs, Gál, Kis, Szűcs, Kocsis, Pintér, Fodor, Orsós, Szalai, Sipos, Magyar, Lukács, Gulyás, Biró, Király, László, Katona, Jakab, Bogdán, Vass, Hegedűs, Bognár, Sándor, Kerekes, Lengyel',
  );
  Object.assign(FM.D.NT_COLORS, {
    AUS: ['#FFCD00', '#00843D'],
    HUN: ['#CD2A3E', '#FFFFFF'],
  });
  Object.assign(FM.D.NT_COLORS, {
    TUR: ['#E30A17', '#FFFFFF'],
    CZE: ['#D7141A', '#11457E'],
    GRE: ['#0D5EAF', '#FFFFFF'],
    POL: ['#FFFFFF', '#DC143C'],
    AUT: ['#ED2939', '#FFFFFF'],
    SUI: ['#D52B1E', '#FFFFFF'],
  });
  // ---------- Bigger name pools: more combinations, fewer repeats across a 10,000-player world ----------
  // (unique-name enforcement in world.js). First names space-separated, surnames comma-separated.
  const MORE_NAMES = {
    ENG: [
      'William Henry Freddie Theo Max Louis Joshua Luca Toby Isaac Adam Elliot Harvey Finley Oscar Jacob Liam Zach Ashley Matt Josh Curtis Dominic Reuben Kian Leon Jayden Bailey Morgan Rory Scott Jake Sonny Rico Tobias Leo Bradley Craig Dean Ellis Gary Jason Kai Kieran Lee Neil Owen Paul Reggie Rob Sean Stuart Wes Ricky',
      'Robinson, Thompson, Lawrence, Chapman, Hodgson, Patterson, Whitaker, Ellis, Hartley, Newton, Burton, Sharp, Hayes, Cole, Fisher, Russell, Barker, Spencer, Webster, Atkinson, Holt, Parkes, Buckley, Mason, Nash, Gibbs, Porter, Reeve, Stone, Tate, Wheeler, Yates, Booth, Dixon, Frost, Hurst, Kirby, Lodge, Moss, Pearce, Rhodes, Shepherd, Summers, Watts, Addo, Asante, Okoye, Richards, Allen, Bailey, Baker, Bates, Bell, Bradley, Brooks, Collins, Cox, Dale, Dawson, Farrell, Ford, Foster, Graham, Grant, Hall, Harper, Hart, Hill, Holmes, Hunt, Hunter, Jennings, Kay, Kerr, Lane, Lawson, Lloyd, Miles, Nicholls, Norris, Parsons, Payne, Perry, Pope, Reid, Reynolds, Robson, Saunders, Simpson, Slater, Thornton, Tucker, Vaughan, Wade, Wells, Whitehead, Wilkinson, Woods',
    ],
    BRA: [
      'Gustavo Leonardo Guilherme Vitor Eduardo Marcelo Renan Danilo Paulo Anderson Douglas Fabrício Luan Murilo Otávio Raul Samuel Yuri Arthur Henrique Enzo Davi Heitor Bernardo Miguel Alisson Gérson Hugo Jean Kauã Marcos Nathan Rafinha Ronaldo Tales Wendel Yago Ygor Emerson Juninho Lucca Andrey Kaique',
      'Araújo, Cardoso, Martins, Freitas, Teixeira, Correia, Azevedo, Monteiro, Mendes, Batista, Cavalcanti, Duarte, Farias, Lacerda, Macedo, Nogueira, Peixoto, Queiroz, Siqueira, Vieira, Fonseca, Andrade, Castro, Cunha, Fernandes, Nunes, Pinto, Ramos, Reis, Rodrigues, Santana, Soares, Campos, Figueiredo, Lopes, Machado, Marques, Medeiros, Melo, Miranda, Moreira, Pires, Sales, Tavares',
    ],
    ARG: [
      'Ezequiel Leandro Joaquín Ramiro Maximiliano Bruno Thiago Alan Ignacio Federico Lucas Mateo Marcos Rodrigo Cristian Hernán Alejandro Carlos Damián Fernando Germán Guido Juan Luciano Martín Mauro Nahuel Pablo Axel Benjamín Bautista Brian Claudio Enzo Exequiel Gastón Jonathan Lisandro Milton Walter Luca',
      'Gómez, Pérez, Sánchez, Ramírez, Torres, Flores, Ruiz, Castro, Ortiz, Molina, Rojas, Vega, Giménez, Aguirre, Cabrera, Ledesma, Quiroga, Ponce, Villalba, Peralta, Godoy, Suárez, Silva, Morales, Núñez, Ríos, Ramos, Luna, Ferreyra, Paz, Juárez, Figueroa, Coronel, Arce, Bustos, Carrizo, Maidana, Ojeda, Páez, Rivero, Toledo, Vera, Zárate, Cáceres',
    ],
    JPN: [
      'Takuma Kazuki Ryota Naoki Shun Yusuke Kenji Tomoya Hayato Riku Sora Itsuki Kosuke Taichi Genki Shuto Asahi Daichi Eita Fumiya Hikaru Hinata Hiroto Jun Kazuya Keisuke Koki Kyosuke Makoto Masaki Minato Naoya Reo Ryusei Satoshi Shinji Shunsuke Soma Taiga Takeru Tatsuya Tomoki Tsubasa Wataru Yamato Yudai Yuma Yusei Akira Ayumu Haruki Issei Kento Rikuto Shinya',
      'Hayashi, Shimizu, Yamaguchi, Mori, Ikeda, Hashimoto, Ishikawa, Ogawa, Okada, Fujita, Goto, Kondo, Murakami, Nishimura, Sakamoto, Aoki, Fukuda, Maeda, Abe, Arai, Fujii, Hasegawa, Hirano, Honda, Ishii, Iwasaki, Kaneko, Kikuchi, Kinoshita, Kubo, Maruyama, Masuda, Matsuda, Miura, Miyazaki, Morita, Nakagawa, Nakano, Nakajima, Noguchi, Ota, Saito, Sakai, Sato, Shibata, Sugiyama, Takagi, Takeda, Tamura, Ueda, Uchida, Wada, Yamazaki, Yano, Yokoyama, Kojima, Hayashida, Nagai',
    ],
    KOR: [
      'Min-ho Hyun-woo Seung-min Jin-su Tae-yang Dong-won Kyung-ho Young-jae Sung-hoon Jun-seo Ha-neul Si-woo Chan-woo Dae-hyun Eun-su Gi-hyun Gyu-min Hae-won Ho-jun Hyeon-seok In-beom Ja-cheol Jae-sung Jeong-ho Ji-hwan Jin-woo Jong-hyun Joo-won Kyu-ri Min-jae Min-kyu Myung-jae Sang-min Se-hun Seok-ju Seung-ho Sung-min Tae-hwan Won-jun Woo-young Yeong-jae Yong-woo Young-min Hyung-min Chul-soo Kwang-hyun Jun-young',
      'Kwon, Song, Shin, Ahn, Seo, Moon, Bae, Baek, Nam, Ryu, Jeon, Hong, Hwang, Im, Heo, Yoo, Go, Yang, Son, Noh, Ha, Kwak, Sung, Cha, Joo, Woo, Min, Jin, Na, Ji, Um, Byun, Chae, Pyo, Gil, Ma, Do, Yeo, Ok, Seol',
    ],
    THA: [
      'Anon Apichat Chaiwat Jakkaphan Kittipong Nopphon Prasit Sittichok Thanakorn Wattana Yodsak Phakin Adisak Anucha Apisit Boonsong Chakrit Chalermchai Ekkachai Jirawat Kasem Kiattisak Korrawit Manop Nattawut Niran Panupong Pattara Phichit Pongsakorn Rattapong Sakda Somchai Sompong Sukree Surachet Tanaboon Teerasil Thitiphan Tossapol Umpol Vorawut Wanchai Wisarut Yutthana Charyl Poramet Kritsana',
      'Boonmee, Chaiyasit, Jaidee, Kongsri, Maneerat, Phromphan, Sukjai, Wongsawat, Yodchai, Pongsak, Sriwan, Thammarat, Anantasak, Buakhao, Chanthong, Charoensuk, Duangkaew, Intharat, Jantarasuk, Kaewkla, Khamsing, Lertsak, Meesuk, Nakprasert, Onsri, Panyasiri, Phetchara, Prasertsri, Ruangsri, Saelim, Sangthong, Siriwat, Somboon, Suwannarat, Tangsakul, Thongchai, Udomsak, Wattanachai, Wiriya, Yenphan, Kaewmanee, Boonkerd',
    ],
    SRB: [
      'Đorđe Milan Vladimir Bogdan Petar Dragan Ognjen Vuk Andrija Veljko Mihajlo Nenad Aleksa Andrej Bojan Branko Darko Dejan Dimitrije Goran Ivan Jovan Lazar Luka Marko Matija Miloš Mladen Nemanja Novak Pavle Radoš Relja Sava Srđan Stefan Uroš Vasilije Vukašin Zoran Željko Danilo Igor Ljubomir Mirko',
      'Popović, Živković, Janković, Radović, Obradović, Simić, Todorović, Vasić, Zdravković, Nedeljković, Filipović, Ristić, Aleksić, Antić, Bogdanović, Cvetković, Despotović, Đurić, Gajić, Jevtić, Krstić, Lazić, Maksimović, Mladenović, Novaković, Pantić, Perić, Radonjić, Rakić, Savić, Spasić, Stevanović, Stojković, Tomić, Veljković, Vukić, Zečević, Živanović, Jović, Marinković, Milovanović, Radenković',
    ],
    FRA: [
      'Louis Arthur Raphaël Tom Noah Adam Evan Axel Mathéo Baptiste Samuel Mamadou Adrien Benjamin Killian Wesley Alexis Aurélien Bastien Cédric Corentin Damien Dylan Florian Gaëtan Guillaume Jordan Julien Kévin Lenny Loïc Malo Marius Nicolas Olivier Quentin Rémi Romain Sacha Tanguy Valentin Victor Yann Youssouf Ismaël Kylian Warren Désiré Randal Eduardo Boubacar Souleymane Amadou',
      'Durand, Leroy, Roux, Fontaine, Chevalier, Robin, Garnier, Faure, Rousseau, Lemaire, Sylla, Sissoko, Cissé, Gomis, Picard, Gauthier, Bonnet, Lacroix, Barbier, Bertrand, Blanchard, Boyer, Brun, Caron, Clément, Colin, David, Denis, Dumont, Dupont, Fabre, Fournier, Gaillard, Guerin, Henry, Joly, Lambert, Lefèvre, Lemoine, Marchand, Masson, Mathieu, Meunier, Michel, Muller, Nicolas, Perrin, Petit, Renard, Richard, Rivière, Roussel, Roy, Simon, Thomas, Vidal, Kanté, Koné, Touré, Konaté, Doucouré, Sakho, Coulibaly, Keita',
    ],
    ESP: [
      'Carlos David Diego Jorge Raúl Víctor Alberto Fernando Luis Mario Óscar Alejandro Miguel Ángel Borja Gonzalo Nacho Unai Aitor Mikel Jon Asier Íñigo Gerard Pau Marc Jordi Eric Aleix Oriol Aarón Adrián Andrés Antonio Arnau Brais Cristian Enrique Ernesto Francisco Gerardo Guillermo Héctor Ismael Jaime José Juanma Julen Lucas Manuel Mateo Nico Rafa Ramón Rodrigo Samu Santi Tomás Xabi Yeray Ander Beñat Gorka Iñaki Joan Martí Pol Roger Xavi Hugo',
      'López, Pérez, González, Rodríguez, Fernández, Gómez, Díaz, Hernández, Álvarez, Jiménez, Romero, Alonso, Castro, Ortega, Rubio, Molina, Delgado, Suárez, Iglesias, Garrido, Cortés, Castillo, Santos, Lozano, Guerrero, Cano, Prieto, Méndez, Calvo, Gallego, Herrera, Peña, León, Márquez, Cabrera, Flores, Campos, Vega, Fuentes, Aguirre, Pascual, Blanco, Arias, Ibáñez, Lorente, Iturralde, Etxeberria, Zubiría, Aguilar, Bravo, Caballero, Cámara, Carmona, Crespo, Domínguez, Durán, Escudero, Esteban, Ferrer, Gallardo, Giménez, Guzmán, Hidalgo, Lara, Luque, Manzano, Marín, Mora, Nieto, Ortiz, Pastor, Quintero, Ramírez, Reyes, Robles, Rojas, Sáez, Salas, Sanz, Soler, Soto, Varela, Vázquez, Velasco, Zamora, Arrieta, Goikoetxea, Larrañaga',
    ],
    NGA: [
      'Chukwuemeka Obinna Olamide Femi Segun Yusuf Bright Frank Moses Kenneth Paul Sunday Abdullahi Akinwale Babatunde Chidera Chinedu Daniel David Ebuka Ejike Friday Godwin Ibrahim Innocent Jamiu Kingsley Kunle Michael Nnamdi Obafemi Oluwaseun Promise Raphael Rasheed Sadiq Seun Simeon Stanley Terem Tobi Umar Wale Yakubu Zaidu Calvin Cyriel Ademola Alhassan',
      'Ogbu, Ibe, Onyeka, Akinola, Okoro, Uzor, Bello, Lawal, Ajayi, Oladipo, Nnamdi, Afolabi, Abubakar, Adeleke, Afolayan, Agu, Aina, Akinyemi, Amadi, Anyanwu, Dike, Ekwueme, Ibekwe, Igwe, Kalu, Mohammed, Nwachukwu, Nwankwo, Obasi, Odion, Ogbonna, Okeke, Oyelaran, Sule, Umar, Yusuf, Ezenwa, Adeniyi, Chima, Emenike, Ogundipe, Olatunji, Onyeama, Uzoma, Babalola, Ezeh, Nnadi',
    ],
    POR: [
      'Bruno Rui Miguel Ricardo Luís Afonso Martim Tomás Alexandre Álvaro Artur Bernardo Carlos Daniel Duarte Eduardo Fábio Filipe Gabriel Henrique Hélder Ivo Joaquim Jorge Leonardo Lourenço Manuel Marco Mário Paulo Renato Rodrigo Salvador Samuel Sérgio Simão Tomé Vasco Xavier Gustavo Dinis Otávio',
      'Santos, Ferreira, Costa, Gomes, Martins, Rodrigues, Sousa, Oliveira, Ribeiro, Rocha, Matos, Barros, Almeida, Alves, Amaral, Andrade, Araújo, Azevedo, Batista, Borges, Brito, Campos, Castro, Cruz, Cunha, Dias, Esteves, Faria, Fernandes, Freitas, Guerreiro, Henriques, Leal, Leite, Loureiro, Macedo, Machado, Magalhães, Marques, Monteiro, Nogueira, Nunes, Pacheco, Paiva, Reis, Salgado, Seixas, Silva, Simões, Vaz, Vieira',
    ],
    NED: [
      'Tim Jasper Koen Tom Wout Sven Rick Kevin Dennis Jordy Bart Boy Calvin Cody Dirk Emil Gijs Hidde Jan Jens Jort Jurriën Kenneth Lucas Mats Max Micky Nathan Owen Pepijn Quinten Rens Robin Roel Ruud Sepp Sjoerd Teun Thom Tijjani Vincent Wessel Xavi Youri Zeno',
      'de Wit, Kramer, van Leeuwen, Dekker, Brouwer, Vermeulen, Willems, van der Meer, Prins, Postma, Boer, Bosch, van Dijk, van der Linden, Hoekstra, Huisman, Jacobs, de Graaf, de Groot, de Haan, de Koning, de Leeuw, Maas, Martens, Peters, Post, Scholten, Timmermans, van Beek, van Dam, van Dongen, van Loon, van Vliet, Verbeek, Verhoeven, Vink, Zwart, Koster, Evers, Brand, Veenstra, Wolters, Schouten',
    ],
    GER: [
      'Paul Lennard David Tobias Philipp Marco Luca Erik Noah Fabian Alexander Andreas Anton Ben Christian Daniel Dennis Dominik Elias Emil Finn Frederik Hannes Jakob Janik Johannes Jonathan Justin Karl Kevin Lars Lennart Linus Malte Mats Matthias Max Nils Ole Oskar Pascal Robin Sebastian Simon Stefan Thomas Timo Tom Vincent Yannick',
      'Zimmermann, Krüger, Hartmann, Lange, Schmitt, Meyer, Walter, König, Kaiser, Vogel, Peters, Frank, Albrecht, Arnold, Baumann, Beck, Böhm, Brandt, Busch, Dietrich, Engel, Friedrich, Fuchs, Graf, Günther, Haas, Hahn, Heinrich, Herrmann, Horn, Jung, Keller, Kraus, Kühn, Lehmann, Lorenz, Ludwig, Maier, Martin, Möller, Otto, Pohl, Roth, Sauer, Schäfer, Scholz, Schubert, Schulz, Schwarz, Seidel, Simon, Sommer, Stein, Thomas, Vogt, Werner, Winkler, Ziegler',
    ],
    BEL: [
      'Tibo Maxime Robbe Kobe Nathan Victor Brent Jelle Stef Lander Aster Bram Charles Cyriel Dante Dries Elias Emile Ferre Hugo Ilias Jarne Jonas Julien Kevin Leander Loïs Louis Mats Mauro Michiel Noah Olivier Pieter Quinten Rune Simon Tom Toon Warre Xander Yari Zeno Arthur Alexis',
      'Vermeersch, Declercq, Van Damme, Hermans, Aerts, Pauwels, Desmet, Vandenberghe, Coppens, Martens, Bogaert, Claeys, Cools, De Backer, De Clercq, De Cock, De Coster, Dewaele, De Wilde, Dubois, Dupont, Geerts, Hendrickx, Lemmens, Leroy, Lambert, Mertens, Moens, Nys, Segers, Simons, Smets, Stevens, Van Acker, Van den Broeck, Van Hoof, Vandamme, Verhaegen, Verstraete, Vervoort, Wuyts, Lefebvre, Mathieu',
    ],
    IRL: [
      'Aaron Dara Eoin Niall Liam Patrick Tadhg Ronan Cathal Fionn Adam Ben Bobby Callum Cillian Colm Conal Dáire Darren Declan Diarmuid Donal Eamon Fiachra Gavin James Jake John Kyle Luke Mark Mikey Odhran Padraig Peter Rian Rory Seamus Tiernan Tom Troy',
      'Lynch, Doherty, Moran, Hayes, Power, Reilly, Hogan, Kavanagh, Fitzgerald, Keane, Daly, Sheridan, Boyle, Brady, Burke, Carroll, Clarke, Coleman, Collins, Connolly, Cullen, Cunningham, Dempsey, Doyle, Dunne, Egan, Flanagan, Flynn, Foley, Gorman, Harrington, Healy, Hennessy, Horgan, Joyce, Keogh, Lawlor, Maguire, Mahon, McGrath, Molloy, Mulligan, Nugent, Regan, Ryan, Sweeney, Tierney, Whelan',
    ],
    SCO: [
      'Andrew Ryan Connor Jack Blair Calum Aidan Robbie Greg Dylan Aaron Alan Allan Barry Billy Brian Cammy Chris Colin Darren David Declan Gary Gordon Hamish Iain Jamie John Kenny Kevin Kieran Lawrence Lyall Malcolm Neil Rory Ruaridh Shaun Stephen Steven Stewart Tommy',
      'Thomson, Wilson, Scott, Cameron, Gordon, Kerr, Morrison, Duncan, Sinclair, Watson, Burns, Graham, Adam, Bain, Black, Brown, Campbell, Christie, Cooper, Dickson, Docherty, Donaldson, Ferguson, Forrest, Gray, Johnston, Kelly, Kennedy, Lawson, Mackay, Maclean, McLean, Miller, Mitchell, Taylor, Boyd, Craig, Dunlop, Fleming, Hay, Kirk, Lindsay, Ogilvie, Rennie, Wallace',
    ],
    WAL: [
      'Harry Joel Lewis Morgan Tom Elis Gareth Wyn Macsen Osian Aaron Ben Brennan Chris Connor Daniel David Ethan Gethin Harri Iolo Jac Jonny Jordan Kieffer Lloyd Mark Neco Nathan Rabbi Sion Sorba Wes Joe Ellis Rubin',
      'Rees, Phillips, Edwards, Parry, James, Powell, Hopkins, Bevan, Vaughan, Pritchard, Allen, Collins, Cooper, Davies, Hughes, Jenkins, King, Lawrence, Moore, Price, Roberts, Taylor, Thomas, Watkins, Wilson, Richards, Bowen, Howells, Jarvis, Lloyd, Meredith, Nash, Probert, Rowlands',
    ],
    URU: [
      'Martín Joaquín Rodrigo Mauricio Santiago Franco Emiliano Gonzalo Agustín Álvaro Bruno Carlos Cristian Damián Diego Felipe Fernando Gabriel Guillermo Ignacio Jonathan Juan Leonardo Lucas Luis Manuel Marcelo Nahuel Pablo Ronald Thiago Valentín Walter Alexis Christian Kevin Federico',
      'Pereira, Fernández, Martínez, Castro, Álvarez, Sosa, Benítez, Da Silva, Rivero, Correa, Acosta, Aguirre, Cáceres, Canobbio, Cardozo, Giménez, González, Hernández, López, Olivera, Rodríguez, Rosas, Sánchez, Silva, Torres, Varela, Viera, Villar, Zalazar, Bueno, Cabrera, Duarte, Etchegaray, Lemos, Machado, Nández, Pintos, Quintana',
    ],
    COL: [
      'Juan Sebastián Luis Felipe Alejandro Óscar Mateo Brayan Alexis Andrés Carlos Cristian Daniel David Deiver Diego Duván Edwin Eduardo Faustino Frank Gustavo Harold Jaminton Jhon Jhonatan Johan Jorge José Kevin Miguel Nicolás Richard Santiago Steven Wílmar Yerson',
      'Gómez, Hernández, Ramírez, Rojas, Ortiz, Moreno, Serna, Balanta, Cuesta, Perea, Barrios, Campaz, Carrascal, Castillo, Durán, Fabra, Guerrero, Hurtado, Lerma, Machado, Montero, Muñoz, Palacios, Quintero, Ríos, Rodríguez, Sánchez, Uribe, Valoy, Vargas, Arboleda, Bermúdez, Cárdenas, Escobar, Gaitán, Londoño, Mejía, Osorio, Restrepo, Zuluaga',
    ],
    SEN: [
      'Saliou Habib Assane Omar Malick Serigne Demba Khadim Abdoulaye Alioune Amadou Bamba Boulaye Cherif Dame Djibril Édouard El Hadji Fodé Formose Habibou Ismaïla Kalidou Krépin Lamine Mame Mbaye Moustapha Nampalys Nicolas Pathé Sadio Salif Samba Seydou Souleymane Youssouf Idrissa Iliman',
      'Dieng, Diatta, Diallo, Camara, Diédhiou, Mendy, Sy, Gning, Touré, Kouyaté, Baldé, Cissokho, Coly, Diagne, Diakhaby, Diarra, Diaw, Dieye, Diouf, Gassama, Gueye, Kanté, Keïta, Ndoye, Sabaly, Sall, Sané, Sène, Sidibé, Sonko, Tall, Wagué, Ndour, Ngom, Samb, Seye, Thiaw, Tine, Wade',
    ],
    GHA: [
      'Nana Kwaku Ebenezer Michael Daniel Prince Felix Collins Abdul Alexander Andrew Antoine Baba Benjamin Bernard Christopher Dennis Derrick Elisha Enoch Eric Ernest Evans Francis Frederick Gideon Ibrahim Inaki Jonathan Jordan Kamaldeen Kingsley Majeed Mohammed Mubarak Osman Patrick Razak Salis Thomas Tariq',
      'Kyei, Quaye, Tetteh, Nkrumah, Bonsu, Antwi, Sarpong, Yeboah, Owusu-Ansah, Donkor, Addo, Aidoo, Ampem, Annan, Asamoah, Badu, Bukari, Nuamah, Nyarko, Ofosu, Frimpong, Gyasi, Issahaku, Lamptey, Sulemana, Amankwah, Boahen, Dankwa, Fosu, Kusi, Manu, Nketiah, Obeng, Sarfo, Tawiah, Twumasi, Wiredu, Yamoah, Zakari',
    ],
    CIV: [
      'Wilfried Moussa Axel Nicolas Jérémie Kouadio Aboubacar Idriss Abdoul Adama Alain Amad Arthur Bakary Christian Didier Emmanuel Éric Evann Franck Gervais Guéla Hamed Ibrahim Jean-Michaël Jonathan Karim Lassina Maxwel Odilon Oumar Salomon Sébastien Sékou Simon Willy Yaya',
      "Traoré, Cissé, Diaby, Sangaré, Tiéné, Akpa, Seri, Kanga, Boli, Gradel, Adingra, Aké, Boga, Deli, Diakité, Fofana, Konan, Kouamé, Ouattara, Singo, Soumahoro, Touré, Yao, Agba, Assi, Beugré, Dago, Ehui, Gnahoré, Kacou, Loba, N'Guessan, Tanoh, Yeboué, Zadi",
    ],
    MAR: [
      'Mehdi Karim Rayane Omar Reda Nabil Walid Taha Abdelhamid Abderrazak Achraf Adil Ahmed Anas Azzedine Brahim Chadi Driss Eliesse Hakim Ibrahim Imran Ismael Jawad Khalid Mounir Mohamed Munir Nordin Noussair Othmane Rachid Romain Sofiane Selim Yahia Yassine Younes Zakaria',
      'Ziani, Kaddouri, Mansouri, Benjelloun, Tahiri, Chraibi, Rachidi, Slimani, Bouzidi, Naciri, Aboukhlal, Adli, Attiat-Allah, Chair, Dari, El Khannouss, El Yamiq, Ezzalzouli, Ouahabi, Rahimi, Sabiri, Zaroury, Belhanda, Fajr, Louza, Amrani, Bakkali, Cherkaoui, El Ouardi, Fikri, Hamdaoui, Jabri, Kharbouch, Mouline, Nejjari, Sefrioui, Tounsi, Zeroual',
    ],
    USA: [
      'Ryan Kyle Matt Nick Tanner Hunter Jesse Diego Aidan Luke Alex Andrew Anthony Benjamin Blake Brian Cameron Carter Chase Christian Clint Daniel DeAndre Dylan Eric Ethan Gabriel Jacob Jalen Jonathan Joshua Julian Justin Landon Logan Malik Mark Owen Paxten Reggie Ricardo Sergiño Timothy Walker Weston Yunus',
      'Thomas, White, Lopez, Walker, Young, King, Wright, Scott, Green, Carter, Mitchell, Rivera, Anderson, Cannon, Evans, Ferreira, Hall, Horvath, Lewis, Long, Martinez, Morris, Nelson, Robinson, Scally, Turner, Zimmerman, Barnes, Cooper, Brooks, Campbell, Collins, Edwards, Fisher, Graham, Hughes, Kelly, Murphy, Perez, Ross, Sanders, Stewart, Ward, Wood',
    ],
    DEN: [
      'Christian Viktor Anders Nicolai Rune Jeppe Victor Tobias Alexander Andreas Casper Daniel Elias Gustav Jacob Jens Joakim Jonas Kristoffer Lasse Lucas Malthe Marcus Martin Morten Nikolaj Oliver Pierre-Emile Rasmus Sebastian Simon Thomas Troels William Yussuf Asger Silas Mathias',
      'Thomsen, Mortensen, Jørgensen, Knudsen, Lauridsen, Dalsgaard, Bech, Vestergaard, Friis, Bruun, Andersen, Christensen, Damsgaard, Frandsen, Gregersen, Isaksen, Jakobsen, Kristiansen, Lindstrøm, Olesen, Stryger, Winther, Østergaard, Hermansen, Mikkelsen, Bang, Dam, Enevoldsen, Fog, Gade, Holst, Juhl, Krogh, Lund, Mogensen, Nørregaard, Overgaard, Riis, Schou, Thygesen',
    ],
    NOR: [
      'Ole Stian Even Mats Aksel Vegard Jørgen Petter Alexander Andreas Anders Birger Bjørn Daniel Erling Fredrik Gustav Hans Harald Jens Jo Johannes Julian Kasper Kristoffer Leo Lars Marius Martin Morten Oscar Patrick Per Sebastian Sondre Stefan Thomas Tor Torbjørn Vetle',
      'Nilsen, Pettersen, Karlsen, Kristiansen, Jacobsen, Halvorsen, Eide, Thorsen, Brekke, Myhre, Aasgaard, Ajer, Berge, Bjørkan, Hanche-Olsen, Hauge, Holm, Jensen, Larsen, Meling, Nyland, Pedersen, Selvik, Solbakken, Strandberg, Thorsby, Tangvik, Skaug, Eggen, Aune, Bakke, Brenden, Fjeld, Grønli, Hovland, Lie, Ness, Rønning, Sæther, Tveit',
    ],
    CRO: [
      'Borna Duje Joško Stipe Tin Kristijan Matej Ante Andrej Antonio Bruno Damir Darko Dario Davor Domagoj Hrvoje Igor Ivo Josip Lovro Luka Marin Martin Mateo Matija Mislav Niko Nikola Robert Roko Stjepan Tomislav Vedran Zvonimir Petar',
      'Šimić, Radić, Lovrić, Petković, Barić, Matić, Galić, Bašić, Rukavina, Jelić, Blažević, Bošnjak, Brajković, Bralić, Crnković, Čović, Dragić, Filipović, Galović, Grubišić, Herceg, Ivanković, Jakovljević, Jukić, Katić, Klarić, Kovač, Lončar, Lukić, Mikulić, Novak, Pavlović, Perković, Polić, Radošević, Sertić, Šarić, Tomić, Vidović, Vrdoljak, Zovko',
    ],
    ITA: [
      'Marco Luca Francesco Stefano Pietro Filippo Emanuele Manuel Leonardo Giorgio Alberto Alessio Antonio Carlo Claudio Cristiano Daniele Diego Enrico Fabio Federico Gabriele Gaetano Giovanni Giuseppe Jacopo Luigi Mattia Michele Mirko Nicola Paolo Raffaele Roberto Salvatore Samuele Sandro Tommaso Umberto Valerio Vincenzo Christian Destiny',
      "Costa, Fontana, Moretti, Barbieri, Lombardi, Rinaldi, Caruso, Ferri, Galli, Martini, Leone, Longo, Gentile, Villa, Amato, Barone, Basile, Benedetti, Bernardi, Bruno, Cattaneo, Coppola, D'Angelo, De Luca, De Rosa, Farina, Fiore, Giordano, Grasso, Guerra, Mancini, Mariani, Marchetti, Messina, Monti, Morelli, Neri, Orlando, Palumbo, Parisi, Pellegrini, Riva, Rizzo, Ruggiero, Sala, Santoro, Serra, Silvestri, Testa, Valentini, Vitale",
    ],
    MEX: [
      'Adrián Alan Alejandro Armando Brian César Christian Daniel Eduardo Efraín Emmanuel Érick Fidel Gilberto Guillermo Hugo Isaac Israel Jesús Jonathan Jorge Kevin Luis Manuel Mario Osvaldo Pablo Rogelio Sebastián Tomás Ulises',
      'Aguirre, Arteaga, Ayala, Beltrán, Cabrera, Campos, Delgado, Espinoza, Estrada, Fuentes, Galindo, Herrera, Lara, Leyva, Lozano, Macías, Medina, Montes, Navarro, Ochoa, Pérez, Quiñones, Ramos, Ríos, Rosales, Salcedo, Sandoval, Tapia, Valdez, Vega, Zavala',
    ],
  };
  for (const code in MORE_NAMES) FM.D.addNames(code, ...MORE_NAMES[code]);

  // Every league, data-driven, at its real size. repBand = the reputation range a league's clubs drift toward.
  // rules.rounds caps the fixture list where the real format isn't a full double round-robin (MLS: 34 games; Argentina: one round-robin).
  // Continental places: Europe 16 (ENG/ESP/GER/ITA 3, FRA 2, POR 1, NED 1); South America 8; Asia, Africa, North America 8 each.
  FM.D.LEAGUES = [
    {
      id: 'D1',
      nat: 'ENG',
      name: 'English Top Division',
      short: 'ENG1',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_D1',
      repBand: [88, 61],
      rules: { relegate: { to: 'D2', n: 3 }, qualify: { to: 'CC', n: 3 } },
    },
    {
      id: 'D2',
      nat: 'ENG',
      name: 'English Division One',
      short: 'ENG2',
      tier: 2,
      sim: 'full',
      clubs: 'CLUBS_D2',
      repBand: [61, 47],
      rules: { promote: { to: 'D1', auto: 2, playoff: [3, 6] }, relegate: { to: 'D3', n: 3 } },
    },
    {
      id: 'D3',
      nat: 'ENG',
      name: 'English Division Two',
      short: 'ENG3',
      tier: 3,
      sim: 'light',
      clubs: 'CLUBS_D3',
      repBand: [49, 39],
      rules: { promote: { to: 'D2', auto: 2, playoff: [3, 6] }, relegate: { to: 'D4', n: 4 } },
    },
    {
      id: 'D4',
      nat: 'ENG',
      name: 'English Division Three',
      short: 'ENG4',
      tier: 4,
      sim: 'light',
      clubs: 'CLUBS_D4',
      repBand: [42, 33],
      rules: { promote: { to: 'D3', auto: 3, playoff: [4, 7] } },
    },
    {
      id: 'ES1',
      nat: 'ESP',
      name: 'Spanish Liga de Honor',
      short: 'ES1',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_ES1',
      repBand: [89, 58],
      rules: { relegate: { to: 'ES2', n: 3 }, qualify: { to: 'CC', n: 3 } },
    },
    {
      id: 'ES2',
      nat: 'ESP',
      name: 'Sable Liga de Plata',
      short: 'ES2',
      tier: 2,
      sim: 'light',
      clubs: 'CLUBS_ES2',
      repBand: [56, 45],
      rules: { promote: { to: 'ES1', auto: 2, playoff: [3, 6], finalLegs: 2 }, relegate: { to: 'ES3', n: 4 } },
    },
    {
      id: 'ES3',
      nat: 'ESP',
      name: 'Spanish Liga Federal',
      short: 'ES3',
      tier: 3,
      sim: 'light',
      clubs: 'CLUBS_ES3',
      repBand: [46, 36],
      rules: { promote: { to: 'ES2', auto: 3, playoff: [4, 7] } },
    },
    {
      id: 'DE1',
      nat: 'GER',
      name: 'Opaline Meisterliga',
      short: 'DE1',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_DE1',
      repBand: [89, 58],
      rules: { qualify: { to: 'CC', n: 3 }, relegate: { to: 'DE2', n: 2, playoff: true } }, // 16th plays the 3rd of the 2. Bundesliga
    },
    {
      id: 'DE2',
      nat: 'GER',
      name: 'Jadestone Aufstiegsliga',
      short: 'DE2',
      tier: 2,
      sim: 'light',
      clubs: 'CLUBS_DE2',
      repBand: [60, 48],
      rules: { promote: { to: 'DE1', auto: 2, tie: true }, relegate: { to: 'DE3', n: 2, playoff: true } },
    },
    {
      id: 'DE3',
      nat: 'GER',
      name: 'German Nordliga',
      short: 'DE3',
      tier: 3,
      sim: 'light',
      clubs: 'CLUBS_DE3',
      repBand: [46, 38],
      rules: { promote: { to: 'DE2', auto: 2, tie: true } },
    },
    {
      id: 'FR1',
      nat: 'FRA',
      name: 'French Championnat de France',
      short: 'FR1',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_FR1',
      repBand: [90, 57],
      rules: { qualify: { to: 'CC', n: 2 }, relegate: { to: 'FR2', n: 2 } },
    },
    {
      id: 'FR2',
      nat: 'FRA',
      name: 'French Division Deux',
      short: 'FR2',
      tier: 2,
      sim: 'light',
      clubs: 'CLUBS_FR2',
      repBand: [58, 44],
      rules: { promote: { to: 'FR1', auto: 2 } },
    },
    {
      id: 'BR1',
      nat: 'BRA',
      name: 'Yonder Série Nacional',
      short: 'BR1',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_BR1',
      repBand: [85, 62],
      rules: { qualify: { to: 'CL', n: 5 } },
    },
    {
      id: 'IT1',
      nat: 'ITA',
      name: 'Nettlefield Lega Nazionale',
      short: 'IT1',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_IT1',
      repBand: [86, 58],
      rules: { qualify: { to: 'CC', n: 3 }, relegate: { to: 'IT2', n: 3 } },
    },
    {
      id: 'IT2',
      nat: 'ITA',
      name: 'Italian Lega Cadetta',
      short: 'IT2',
      tier: 2,
      sim: 'light',
      clubs: 'CLUBS_IT2',
      repBand: [58, 45],
      rules: { promote: { to: 'IT1', auto: 2, playoff: [3, 6], finalLegs: 2 } },
    },
    {
      id: 'PT1',
      nat: 'POR',
      name: 'Lionheart Superliga',
      short: 'PT1',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_PT1',
      repBand: [83, 53],
      rules: { qualify: { to: 'CC', n: 1 } },
    },
    {
      id: 'NL1',
      nat: 'NED',
      name: 'Dutch Eerste Klasse',
      short: 'NL1',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_NL1',
      repBand: [81, 54],
      rules: { qualify: { to: 'CC', n: 1 } },
    },
    {
      id: 'AR1',
      nat: 'ARG',
      name: 'Momentum Superliga',
      short: 'AR1',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_AR1',
      repBand: [79, 53],
      rules: { rounds: 27, qualify: { to: 'CL', n: 3 } },
    },
    {
      id: 'US1',
      nat: 'USA',
      name: 'Zinc Super League',
      short: 'US1',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_US1',
      repBand: [67, 55],
      rules: { rounds: 34, qualify: { to: 'NC', n: 4 } },
    },
    {
      id: 'JP1',
      nat: 'JPN',
      name: 'Japanese Premier League',
      short: 'JP1',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_JP1',
      repBand: [64, 53],
      rules: { qualify: { to: 'AC', n: 4 } },
    },
    {
      id: 'MX1',
      nat: 'MEX',
      name: 'Mexican Liga Mayor',
      short: 'MX1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_MX1',
      repBand: [70, 55],
      rules: { qualify: { to: 'NC', n: 4 } },
    },
    {
      id: 'KR1',
      nat: 'KOR',
      name: 'Polaris Premier League',
      short: 'KR1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_KR1',
      repBand: [60, 51],
      rules: { qualify: { to: 'AC', n: 2 } },
    },
    {
      id: 'TH1',
      nat: 'THA',
      name: 'Thai Super League',
      short: 'TH1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_TH1',
      repBand: [56, 44],
      rules: { qualify: { to: 'AC', n: 2 } },
    },
    {
      id: 'NG1',
      nat: 'NGA',
      name: 'Nigerian Top Division',
      short: 'NG1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_NG1',
      repBand: [55, 45],
      rules: { qualify: { to: 'AF', n: 4 } },
    },
    {
      id: 'MA1',
      nat: 'MAR',
      name: 'Moroccan Ligue Nationale',
      short: 'MA1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_MA1',
      repBand: [59, 46],
      rules: { qualify: { to: 'AF', n: 4 } },
    },
    {
      id: 'RS1',
      nat: 'SRB',
      name: 'Brightway Prva Liga',
      short: 'RS1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_RS1',
      repBand: [64, 46],
      rules: {},
    },
    {
      id: 'BE1',
      nat: 'BEL',
      name: 'Birchfield Eerste Klasse',
      short: 'BE1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_BE1',
      repBand: [68, 50],
      rules: {},
    },
    {
      id: 'TR1',
      nat: 'TUR',
      name: 'Turkish Birinci Lig',
      short: 'TR1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_TR1',
      repBand: [72, 50],
      rules: {},
    },
    {
      id: 'CZ1',
      nat: 'CZE',
      name: 'Czech První Liga',
      short: 'CZ1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_CZ1',
      repBand: [64, 46],
      rules: {},
    },
    {
      id: 'GR1',
      nat: 'GRE',
      name: 'Bramwell Alfa Liga',
      short: 'GR1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_GR1',
      repBand: [68, 48],
      rules: {},
    },
    {
      id: 'NO1',
      nat: 'NOR',
      name: 'Norwegian Topliga',
      short: 'NO1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_NO1',
      repBand: [63, 46],
      rules: {},
    },
    {
      id: 'PL1',
      nat: 'POL',
      name: 'Halcyon Liga Główna',
      short: 'PL1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_PL1',
      repBand: [62, 46],
      rules: {},
    },
    {
      id: 'DK1',
      nat: 'DEN',
      name: 'Thornfield Topliga',
      short: 'DK1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_DK1',
      repBand: [64, 48],
      rules: {},
    },
    {
      id: 'AT1',
      nat: 'AUT',
      name: 'Kingsley Bundesstaffel',
      short: 'AT1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_AT1',
      repBand: [64, 46],
      rules: {},
    },
    {
      id: 'CH1',
      nat: 'SUI',
      name: 'Swiss Super Liga',
      short: 'CH1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_CH1',
      repBand: [63, 48],
      rules: {},
    },
    {
      id: 'SC1',
      nat: 'SCO',
      name: 'Scottish Premier Division',
      short: 'SC1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_SC1',
      repBand: [70, 46],
      rules: {},
    },
    {
      id: 'AU1',
      nat: 'AUS',
      name: 'Australian Premier Division',
      short: 'AU1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_AU1',
      repBand: [58, 46],
      rules: { qualify: { to: 'AC', n: 2 } },
    },
    {
      id: 'HU1',
      nat: 'HUN',
      name: 'Marlowe Első Osztály',
      short: 'HU1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_HU1',
      repBand: [62, 45],
      rules: {},
    },
    {
      id: 'IE1',
      nat: 'IRL',
      name: 'Quorum Premier Union',
      short: 'IE1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_IE1',
      repBand: [52, 41],
      rules: {},
    },
    {
      id: 'WA1',
      nat: 'WAL',
      name: 'Welsh Premier Union',
      short: 'WA1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_WA1',
      repBand: [49, 37],
      rules: {},
    },
  ];
  FM.D.CONTINENTALS = [
    { id: 'CC', region: 'Europe', name: 'European Champions Cup', short: 'EUR1', prize: 15e6 },
    { id: 'CL', region: 'South America', name: 'South American Champions Cup', short: 'SAM1', prize: 8e6 },
    {
      id: 'AC',
      region: 'Asia',
      name: 'Asian Champions Cup',
      short: 'ASI1',
      prize: 5e6,
      legs: { qf: 1, sf: 1, f: 1 }, // the knockouts are single matches at one centralised venue
      central: true,
    },
    { id: 'AF', region: 'Africa', name: 'African Champions Cup', short: 'AFR1', prize: 3e6, legs: { f: 2 } }, // a two-legged final
    {
      id: 'NC',
      region: 'North America',
      name: 'North American Champions Cup',
      short: 'NAM1',
      prize: 4e6,
      legs: { f: 2 },
    },
    // Second-tier cups: the next places after each league's main continental spots (feeders: league → clubs)
    {
      id: 'EL',
      region: 'Europe',
      name: 'European Shield',
      short: 'EUR2',
      prize: 5e6,
      tier: 2,
      feeders: { D1: 2, ES1: 2, DE1: 2, IT1: 2, FR1: 2, PT1: 1, NL1: 1, BE1: 1, TR1: 1, AT1: 1, GR1: 1 },
    },
    {
      id: 'SA',
      region: 'South America',
      name: 'South American Shield',
      short: 'SAM2',
      prize: 2.5e6,
      tier: 2,
      feeders: { BR1: 4, AR1: 4 },
    },
    // Third-tier European cup: the places after the Europa League's (a league's clubs skip the places above)
    {
      id: 'UC',
      region: 'Europe',
      name: 'European Trophy',
      short: 'EUR3',
      prize: 3e6,
      tier: 3,
      feeders: {
        D1: 1,
        ES1: 1,
        DE1: 1,
        IT1: 1,
        FR1: 1,
        PT1: 1,
        NL1: 1,
        BE1: 2,
        TR1: 1,
        SC1: 2,
        CZ1: 1,
        GR1: 1,
        PL1: 1,
        DK1: 1,
      },
    },
    {
      id: 'A2',
      region: 'Asia',
      name: 'Asian Shield',
      short: 'ASI2',
      prize: 2e6,
      tier: 2,
      feeders: { JP1: 2, KR1: 2, TH1: 2, AU1: 2 },
    },
    {
      id: 'AX',
      region: 'Africa',
      name: 'African Shield',
      short: 'AFR2',
      prize: 1.5e6,
      tier: 2,
      feeders: { NG1: 2, MA1: 2 },
      legs: { f: 2 },
    },
  ];
  // How each league splits clubs level on points, in order (the real rules): gd = goal difference, gf = goals
  // scored, wins = number of wins, h2h = head-to-head among the clubs level (points, then goal difference, then goals).
  // Anything after these falls to the club's name (a real league would hold a play-off or draw lots).
  FM.D.TIEBREAK_DEFAULT = ['gd', 'gf'];
  FM.D.TIEBREAK = {
    ES1: ['h2h', 'gd', 'gf'], // LaLiga: head-to-head first
    ES2: ['h2h', 'gd', 'gf'],
    ES3: ['h2h', 'gd', 'gf'],
    IT1: ['h2h', 'gd', 'gf'], // Serie A and B: head-to-head first
    IT2: ['h2h', 'gd', 'gf'],
    PT1: ['h2h', 'gd', 'gf'],
    TR1: ['h2h', 'gd', 'gf'],
    GR1: ['h2h', 'gd', 'gf'],
    PL1: ['h2h', 'gd', 'gf'],
    DE1: ['gd', 'gf', 'h2h'],
    DE2: ['gd', 'gf', 'h2h'],
    DE3: ['gd', 'gf', 'h2h'],
    FR1: ['gd', 'gf', 'h2h'],
    FR2: ['gd', 'gf', 'h2h'],
    NL1: ['gd', 'gf', 'h2h'],
    JP1: ['gd', 'gf', 'h2h'],
    BR1: ['wins', 'gd', 'gf', 'h2h'], // Brasileirão: wins, then goal difference
    US1: ['wins', 'gd', 'gf'], // MLS: wins first
    KR1: ['gf', 'gd'], // K League: goals scored before goal difference
  };
  // The smallest stadium (capacity) each continental competition licenses for home games; a club below it plays them
  // at a neutral ground until it is built up
  FM.D.GROUND_MIN = {
    CC: 8000,
    EL: 5000,
    UC: 4500,
    CL: 10000,
    SA: 8000,
    AC: 8000,
    A2: 5000,
    AF: 5000,
    AX: 5000,
    NC: 8000,
  };
  // The headline numbers, counted from the data: the title screen, the world screen and the docs check
  // (tools/check-docs.mjs) all read these, so they can't drift apart
  FM.D.facts = () => ({
    clubs: FM.D.LEAGUES.reduce((n, l) => n + FM.D[l.clubs].length, 0),
    leagues: FM.D.LEAGUES.length,
    nations: new Set(FM.D.LEAGUES.map((l) => l.nat)).size,
    nationalTeams: Object.keys(FM.D.NATIONS).length,
    domesticCups: FM.D.DOMESTIC_CUPS.length,
    continentalCups: FM.D.CONTINENTALS.length,
  });
  // The one line the title screen and the store page lead with
  FM.D.HOOK = 'The deepest football management experience built for mobile. Your club. Your stories. Your history.';
  // Domestic cups: single-leg knockouts for every club of the nation that is fully or lightly simulated
  // [id, nation, name, short, format]. Format, as in real life: legs = the rounds (by clubs left: 4 = semi-finals)
  // played over two legs, neutral = the rounds played at a neutral ground ('all' for every round). The rest are
  // single matches at the home of the club drawn first (the lower-division club, in the real draws), with extra
  // time and penalties. Away goals do not count anywhere: no competition has used them since 2021–22.
  FM.D.DOMESTIC_CUPS = [
    ['CUPENG', 'ENG', 'English National Cup', 'ENGC', { neutral: [4, 2] }], // semi-finals and final at Wembley
    ['CUPESP', 'ESP', 'Spanish Copa del Rey Fundador', 'ESPC', { neutral: [2] }], // single-leg semi-finals since 2019–20
    ['CUPGER', 'GER', 'German Bundespokal Neu', 'GERC', { neutral: [2] }], // final in Berlin
    ['CUPFRA', 'FRA', 'French Coupe Nationale', 'FRAC', { neutral: [2] }],
    ['CUPBRA', 'BRA', 'Brazilian Copa dos Campeões', 'BRAC', { legs: [8, 4, 2], neutral: [] }], // two legs from the later rounds, home-and-away final
    ['CUPITA', 'ITA', 'Italian Coppa Nazionale', 'ITAC', { legs: [4], neutral: [2] }],
    ['CUPPOR', 'POR', 'Portuguese Taça Nacional', 'PORC', { legs: [4], neutral: [2] }],
    ['CUPNED', 'NED', 'Dutch Kampioensbeker', 'NEDC', { neutral: [2] }],
    ['CUPARG', 'ARG', 'Argentine Copa de la Federación', 'ARGC', { neutral: 'all' }], // every tie at a neutral ground
    ['CUPUSA', 'USA', 'American Football Cup', 'USAC', { neutral: [] }], // the final at the better seed's ground
    ['CUPJPN', 'JPN', 'Japanese National Cup', 'JPNC', { neutral: [2] }],
  ];
  // Club World Cup: last season's continental finalists (winners only from Africa and North America)
  // [competition, 0 = winner / 1 = runner-up], in seed order
  FM.D.CWC_SEEDS = [
    ['CC', 0],
    ['CL', 0],
    ['CC', 1],
    ['CL', 1],
    ['AC', 0],
    ['AF', 0],
    ['NC', 0],
    ['AC', 1],
  ];
  // Squad sizes per tier (+ academy prospects)
  FM.D.SQUAD_TIER = {
    // deep enough to cover injuries, suspensions and rotation (full: 26 senior players, three of them keepers)
    full: { GK: 3, CB: 5, FB: 3, WB: 1, DM: 2, CM: 4, WM: 2, AM: 2, W: 2, ST: 2 },
    light: { GK: 2, CB: 3, FB: 2, WB: 1, DM: 2, CM: 3, WM: 1, AM: 2, W: 2, ST: 2 },
    minimal: { GK: 2, CB: 3, FB: 2, DM: 1, CM: 2, WM: 1, AM: 1, W: 1, ST: 2 },
  };
  FM.D.ACADEMY_TIER = { full: 2, light: 2, minimal: 1 };

  // Nationality mixes for the new leagues
  Object.assign(FM.D.NAT_MIX, {
    IT1: {
      ITA: 58,
      ARG: 4,
      BRA: 4,
      FRA: 4,
      SRB: 3,
      CRO: 3,
      NED: 2,
      POR: 2,
      ESP: 2,
      DEN: 2,
      NOR: 2,
      SEN: 2,
      NGA: 2,
      MAR: 2,
      URU: 2,
      COL: 2,
      GER: 2,
      BEL: 2,
    },
    NL1: {
      NED: 64,
      BEL: 6,
      MAR: 4,
      DEN: 3,
      NOR: 3,
      GHA: 2,
      NGA: 2,
      SEN: 2,
      BRA: 2,
      SRB: 2,
      CRO: 2,
      JPN: 2,
      GER: 2,
      KOR: 1,
      USA: 1,
      POR: 1,
    },
    PT1: {
      POR: 55,
      BRA: 18,
      ARG: 4,
      URU: 3,
      COL: 3,
      ESP: 3,
      SEN: 2,
      CIV: 2,
      NGA: 2,
      FRA: 2,
      MAR: 2,
      GHA: 2,
      SRB: 1,
      JPN: 1,
    },
    AR1: { ARG: 88, URU: 5, COL: 4, BRA: 1, USA: 1, ESP: 1 },
    US1: {
      USA: 60,
      MEX: 8,
      COL: 4,
      ARG: 4,
      ENG: 3,
      GHA: 3,
      NGA: 2,
      JPN: 2,
      KOR: 2,
      BRA: 2,
      URU: 2,
      FRA: 2,
      GER: 2,
      ESP: 2,
      SCO: 1,
      IRL: 1,
    },
    JP1: { JPN: 88, KOR: 5, BRA: 4, THA: 2, SRB: 1 },
    MX1: { MEX: 70, ARG: 8, COL: 6, URU: 5, USA: 4, BRA: 3, ESP: 2 },
    NG1: { NGA: 95, GHA: 3, CIV: 1, SEN: 1 },
    KR1: { KOR: 88, BRA: 6, JPN: 3, SRB: 1, USA: 1 },
    TH1: { THA: 80, BRA: 7, JPN: 5, KOR: 5, SRB: 2, NGA: 1 },
    RS1: { SRB: 80, CRO: 4, GHA: 3, NGA: 3, BRA: 3, MAR: 2, SEN: 2, JPN: 1 },
    MA1: { MAR: 88, SEN: 4, CIV: 3, GHA: 2, NGA: 2, FRA: 1 },
  });

  Object.assign(FM.D.NAT_MIX, {
    BE1: {
      BEL: 60,
      NED: 6,
      FRA: 5,
      SEN: 3,
      CIV: 3,
      GHA: 3,
      NGA: 3,
      MAR: 3,
      DEN: 2,
      NOR: 2,
      JPN: 2,
      COL: 2,
      BRA: 2,
      CRO: 2,
      SRB: 2,
    },
    TR1: {
      TUR: 62,
      BRA: 4,
      NGA: 3,
      SEN: 3,
      CIV: 2,
      GHA: 2,
      POR: 3,
      NED: 2,
      SRB: 2,
      CRO: 2,
      ARG: 2,
      COL: 2,
      FRA: 2,
      GER: 2,
      MAR: 2,
      POL: 2,
      CZE: 1,
      GRE: 1,
      BEL: 1,
    },
    CZ1: { CZE: 80, POL: 3, SRB: 2, CRO: 2, NGA: 2, GHA: 2, AUT: 2, GER: 1, SEN: 2, CIV: 2, BRA: 1, TUR: 1 },
    GR1: {
      GRE: 58,
      SRB: 4,
      POR: 4,
      BRA: 4,
      ARG: 3,
      ESP: 3,
      CRO: 3,
      NGA: 2,
      SEN: 2,
      CIV: 2,
      NED: 2,
      POL: 2,
      MAR: 2,
      FRA: 2,
      COL: 2,
      URU: 2,
      CZE: 1,
      TUR: 1,
    },
    NO1: { NOR: 80, DEN: 4, GHA: 3, NGA: 3, SEN: 2, USA: 2, CIV: 2, NED: 1, BEL: 1, POL: 1, SUI: 1 },
    PL1: {
      POL: 70,
      CZE: 3,
      SRB: 3,
      CRO: 3,
      POR: 3,
      ESP: 3,
      BRA: 2,
      NGA: 2,
      GHA: 2,
      SEN: 2,
      NOR: 1,
      DEN: 1,
      GRE: 1,
      AUT: 1,
      TUR: 1,
      NED: 1,
      GER: 1,
    },
    DK1: {
      DEN: 74,
      NOR: 4,
      NGA: 3,
      GHA: 3,
      SEN: 2,
      NED: 2,
      BEL: 2,
      USA: 2,
      CIV: 2,
      JPN: 1,
      KOR: 1,
      SUI: 1,
      POL: 1,
      AUT: 1,
      CZE: 1,
    },
    AT1: {
      AUT: 64,
      GER: 8,
      SUI: 3,
      CRO: 3,
      SRB: 2,
      CZE: 2,
      POL: 2,
      NGA: 2,
      GHA: 2,
      CIV: 2,
      SEN: 2,
      MAR: 2,
      BRA: 2,
      JPN: 2,
      KOR: 2,
      DEN: 1,
      NOR: 1,
    },
    CH1: {
      SUI: 62,
      FRA: 6,
      GER: 4,
      ITA: 4,
      AUT: 3,
      CRO: 2,
      SRB: 2,
      POR: 2,
      SEN: 2,
      CIV: 2,
      GHA: 2,
      NGA: 2,
      BRA: 2,
      COL: 2,
      CZE: 1,
      POL: 1,
      TUR: 1,
    },
    SC1: {
      SCO: 58,
      ENG: 12,
      IRL: 6,
      WAL: 2,
      JPN: 3,
      KOR: 2,
      NOR: 2,
      DEN: 2,
      NED: 2,
      BEL: 1,
      NGA: 2,
      GHA: 2,
      USA: 2,
      CIV: 1,
      CRO: 1,
      POL: 1,
    },
  });

  Object.assign(FM.D.NAT_MIX, {
    AU1: {
      AUS: 62,
      ENG: 5,
      SCO: 2,
      BRA: 4,
      JPN: 3,
      KOR: 3,
      ESP: 3,
      ARG: 2,
      USA: 2,
      NED: 2,
      ITA: 2,
      CRO: 2,
      SRB: 2,
      NGA: 1,
      GHA: 1,
      MAR: 1,
      FRA: 1,
    },
    HU1: {
      HUN: 72,
      SRB: 4,
      CRO: 3,
      POL: 2,
      CZE: 2,
      AUT: 2,
      GER: 2,
      BRA: 2,
      NGA: 2,
      GHA: 2,
      SEN: 1,
      CIV: 1,
      POR: 1,
      ESP: 1,
      NED: 1,
      TUR: 1,
    },
    IE1: {
      IRL: 78,
      ENG: 6,
      SCO: 2,
      WAL: 1,
      NGA: 2,
      GHA: 2,
      FRA: 1,
      ESP: 1,
      POR: 1,
      BRA: 1,
      USA: 2,
      JPN: 1,
      NED: 1,
      CIV: 1,
    },
    WA1: { WAL: 70, ENG: 20, IRL: 3, SCO: 2, NGA: 1, GHA: 1, ESP: 1, POR: 1, FRA: 1 },
  });

  // ---------- Alpha 1: contracts, agents, promises, badges ----------
  FM.D.AGENTS = {
    Shark: {
      icon: '🦈',
      desc: 'Squeezes every dollar. Walks away quickly.',
      demand: 1.12,
      patience: 2,
      fee: 0.08,
      bonusW: 1,
    },
    Pragmatic: { icon: '🤝', desc: 'Reasonable, wants a fair deal.', demand: 1.0, patience: 4, fee: 0.05, bonusW: 1 },
    Family: {
      icon: '🏡',
      desc: 'A relative looking after him. Values security and long deals.',
      demand: 0.95,
      patience: 5,
      fee: 0.03,
      bonusW: 0.9,
      longDeal: true,
    },
    Showman: {
      icon: '🎤',
      desc: 'Loves a headline number — big signing bonuses.',
      demand: 1.04,
      patience: 3,
      fee: 0.06,
      bonusW: 1.6,
    },
    Rookie: {
      icon: '🧢',
      desc: 'New to the game. Easy to deal with.',
      demand: 0.92,
      patience: 5,
      fee: 0.03,
      bonusW: 1,
    },
  };
  FM.D.AGENT_FIRMS = [
    'Apex Sports',
    'Stellar Group',
    'Blue Line Mgmt',
    'Goldfoot Agency',
    'Pinnacle Talent',
    'Northstar Football',
    'Premier Reps',
    'Crest & Co.',
    'Touchline Talent',
    'Wembley Mgmt',
  ];
  // Squad status: promised starts per season share, and what players expect relative to the squad
  FM.D.STATUS = {
    key: { label: 'Key player', share: 0.75, apps: 38 },
    regular: { label: 'Regular starter', share: 0.55, apps: 30 },
    rotation: { label: 'Rotation', share: 0.3, apps: 18 },
    backup: { label: 'Backup', share: 0.1, apps: 8 },
    prospect: { label: 'Prospect', share: 0.05, apps: 4 },
  };
  FM.D.BADGES = ['National C', 'Continental B', 'Continental A', 'Continental Pro'];
  FM.D.BADGE_COURSE = {
    'Continental A': { cost: 6e4, days: 12, rep: 3 },
    'Continental Pro': { cost: 1.5e5, days: 18, rep: 5 },
  };
})();
