// More nationalities: 52 further nations whose players turn up in the world's squads and play for their own national
// teams (js/intl.js builds a team for every nation that has enough players). None of them has a league in the game;
// their players are spread through the existing leagues by where emigrants really go (France and Belgium for the
// French-speaking African nations, Germany and Austria for the Balkans, Spain and Italy for the Latin Americans ...).
// Each nation brings its own name culture (js/names.js has the older pools, the new ones are here).
(function () {
  const FM = window.FM,
    D = FM.D,
    P = D.mkPool;

  // ---------- Name pools for the cultures the first set did not cover ----------
  Object.assign(D.NAME_POOLS, {
    // Spain's own regional cultures: players with a Basque or Catalan family (the clubs that sign only them are in D.CLUB_POLICY)
    basque: P(
      `Iker Aitor Unai Xabier Mikel Gorka Asier Ander Jon Iñigo Oier Beñat Eneko Julen Markel Haritz Imanol Koldo Peru Ibai Aimar Ekain Gaizka Josu Urko Igor Endika Gari Joseba Aritz Kepa Aner Arkaitz Eder Eñaut Gontzal Hodei Iñaki Jokin Kerman Lander Maialen Mattin Naia Odei Paul Sendoa Txomin Unax Xabi Yeray Zigor Aitzol Alain Arnaitz Danel Gaizka Ixaka Lizar Mugurutza Nerea Oihan Sabin Telmo Urtzi Xuban`,
      `Etxeberria Goikoetxea Iturbe Larrañaga Zubizarreta Aguirre Urrutia Mendizabal Arrieta Echevarría Olazabal Zabala Garmendia Irigoyen Lasa Ugarte Uriarte Aranburu Elorza Ibarra Otegi Berasategi Agirre Altuna Beitia Bengoetxea Galdos Idiakez Lekue Mendiola Oyarzabal Sagarna Zugasti Aizpurua Aramburu Arana Arregi Astigarraga Azkue Bilbao Elizondo Eguren Etxaniz Gabilondo Garaikoetxea Goenaga Iraola Iriondo Jauregi Lazkano Letamendi Maiztegi Mugica Orbegozo Salaberria San Sebastian Sarasola Telleria Txapartegi Unanue Urkiza Zabaleta Zubeldia Zulaika`,
    ),
    catalan: P(
      `Jordi Pau Marc Oriol Arnau Roger Pol Joan Xavi Sergi Albert Genís Guillem Ferran Biel Aleix Adrià Cesc Èric Joel Lluc Nil Quim Ramon Bernat Eduard Jaume Martí Narcís Raül Sebastià Abel Aitor Bru Carles Dídac Enric Gerard Hugo Iu Jofre Magí Miquel Oleguer Pere Pep Ricard Roc Salvador Tià Toni Vicenç Arnau Biel Cristià Eloi Francesc Isidre Jan Lluís Oriol Quirze Xènia`,
      `Puig Soler Serra Vila Ferrer Roca Mas Pujol Vidal Casals Torrent Camps Ribas Font Bosch Carbonell Casanovas Castells Costa Fabregat Girbau Grau Jover Marsal Molins Planas Prat Riera Rovira Sala Subirats Vallès Vendrell Alsina Anglada Argemí Balaguer Barceló Boada Bonet Cabré Calvet Capdevila Clavé Colomer Comas Domènech Escudé Fàbregas Garriga Gasull Guardiola Illa Llobet Maresma Montserrat Moragues Noguera Oller Parés Pla Pons Rius Salvadó Tarrés Terrades Tortosa Urpí Valls Viladomat Xicota`,
    ),
    eastslavic: P(
      `Oleksandr Andriy Serhiy Dmytro Vitaliy Mykola Ivan Artem Bohdan Yaroslav Roman Taras Vasyl Maksym Denys Yuriy Ihor Oleh Pavlo Viktor Volodymyr Anatoliy Danylo Kyrylo Mykhailo Stanislav Vladyslav Yevhen Zakhar Alexei Sergei Dmitri Nikolai Vladimir Andrei Pavel Mikhail Igor Artyom Ilya Kirill Maxim Evgeny Konstantin Anton Vyacheslav Gleb Daniil Timofei Egor Ruslan Rostislav Valentin Boris Leonid Oleg Grigory Fyodor Semyon Arseniy Matvey Lev Timur Stepan Gennady Vasily`,
      `Ivanov Petrov Smirnov Kuznetsov Popov Sokolov Lebedev Kozlov Novikov Morozov Volkov Solovyov Vasiliev Zaitsev Pavlov Semyonov Golubev Vinogradov Bogdanov Vorobyov Fyodorov Mikhailov Belyaev Tarasov Belov Komarov Orlov Kiselyov Makarov Andreev Kovalev Ilyin Gusev Titov Kuzmin Kudryavtsev Baranov Kulikov Alekseev Stepanov Yakovlev Sorokin Sergeev Romanov Zakharov Borisov Korolev Gerasimov Ponomarev Grigoriev Lazarev Medvedev Ershov Nikitin Sobolev Ryabov Polyakov Tsvetkov Danilov Zhukov Frolov Zhuravlev Nikolaev Krylov Maksimov Sidorov Osipov Belousov Fedotov Dorofeev Egorov Matveev Bobrov Kovalenko Bondarenko Tkachenko Kravchenko Boyko Melnyk Shevchuk Kovalchuk Polishchuk Savchenko Rudenko Lysenko Marchenko Petrenko Moroz Pavlenko Kharchenko Koval Oliynyk Sydorenko Zaporozhets Hrytsenko Havrylenko Honcharenko Ivashchenko Klymenko Kuzmenko Lytvynenko Martynenko Nesterenko Panchenko Romanenko Semenenko Tereshchenko Vasylenko Yaremenko`,
    ),
    romanian: P(
      `Andrei Alexandru Mihai Cristian Florin Ionuț Gabriel Daniel Marius Radu Bogdan Costin Răzvan Adrian Vlad Dorin Nicolae George Ștefan Eugen Cătălin Claudiu Dragoș Emil Sorin Valentin Viorel Liviu Narcis Robert Sebastian Silviu Tudor Octavian Paul Lucian Laurențiu Ovidiu Remus Teodor Virgil Horia Iosif Petru Vasile`,
      `Popescu Ionescu Popa Stan Dumitru Gheorghe Stoica Constantin Marin Mihai Rusu Radu Matei Munteanu Dinu Ilie Vasile Georgescu Ene Preda Tudor Barbu Lazăr Florea Dobre Nistor Oprea Moldovan Toma Cristea Lupu Pavel Stancu Tănase Neagu Manole Dragomir Ciobanu Șerban Ardelean Coman Diaconu Voicu Zamfir Avram Albu Iordache Bălan Cojocaru Crăciun Dima Enache Grigore Hanganu Iancu Luca Marinescu Nedelcu Olteanu Pârvu Sandu Trifan Ungureanu Vlad`,
    ),
    albanian: P(
      `Arben Besnik Dritan Erion Fatos Gazmend Jetmir Kujtim Lorik Mentor Nderim Olti Përparim Qëndrim Redon Shkëlzen Tefik Valon Ylber Altin Arlind Bardhyl Drilon Endrit Florian Genc Granit Hysen Ilir Klodian Leotrim Mirlind Naim Orges Pellumb Rinor Sokol Taulant Ujkan Valdet Xhevat Besart Bujar Eldon Flamur Gentian Ismet Lirim`,
      `Hoxha Shehu Gjoni Krasniqi Berisha Morina Gashi Kelmendi Bytyqi Hasani Dervishi Prifti Marku Leka Basha Dibra Xhafa Rama Kola Cela Gjika Haxhiu Kastrati Lleshi Mema Nushi Osmani Peci Qosja Rexha Sadiku Tafa Ukaj Vata Zogu Ahmeti Bajrami Curri Demaj Elezi Fetahu Gega Halili Isufi Jashari Kryeziu Lika Mulaj`,
    ),
    finnish: P(
      `Juho Mikko Antti Jukka Matti Timo Tuomas Sami Ville Petri Jari Lauri Eero Olli Aleksi Elias Onni Leevi Eetu Veeti Oskari Santeri Joonas Aatu Jesse Niko Teemu Miika Kalle Jaakko Toni Henri Tommi Perttu Kasper Samuli Valtteri Roope Topias Otto Arttu Lassi Jere Aku Esa Heikki Pasi Raimo Seppo Tapio Veikko`,
      `Korhonen Virtanen Mäkinen Nieminen Mäkelä Hämäläinen Laine Heikkinen Koskinen Järvinen Lehtonen Lehtinen Saarinen Salminen Heinonen Niemi Heiskanen Kinnunen Salonen Turunen Salo Laitinen Tuominen Rantanen Karjalainen Jokinen Mattila Savolainen Lahtinen Ahonen Kallio Leppänen Hiltunen Mustonen Pitkänen Aaltonen Väisänen Lindholm Pesonen Manninen Koivisto Lehto Hirvonen Räsänen Kettunen Oksanen Kemppainen Ojala`,
    ),
    icelandic: P(
      `Jón Gunnar Sigurður Guðmundur Ólafur Kristján Einar Magnús Bjarni Árni Stefán Þórður Ragnar Hörður Aron Alfreð Birkir Emil Hólmar Rúnar Viðar Arnór Jóhann Kolbeinn Sverrir Ari Mikael Elías Orri Daníel Hákon Ísak Kári Víkingur Þorsteinn Brynjar Atli Haukur Hannes Rafn Tómas Valur Egill`,
      `Jónsson Gunnarsson Sigurðsson Guðmundsson Ólafsson Kristjánsson Einarsson Magnússon Bjarnason Árnason Stefánsson Þórðarson Ragnarsson Haraldsson Helgason Ingason Jóhannsson Karlsson Pétursson Snorrason Steinarsson Víkingsson Þorvaldsson Ásgeirsson Björnsson Davíðsson Eiríksson Finnbogason Gíslason Halldórsson Ísaksson Kjartansson Lárusson Njálsson Óskarsson Rúnarsson Sveinsson Tómasson`,
    ),
    mashriq: P(
      `Mohamed Ahmed Mahmoud Mostafa Ali Hassan Hussein Omar Khaled Karim Tarek Amr Walid Sherif Hossam Ayman Essam Ibrahim Yousef Abdullah Faisal Fahad Salman Nasser Saud Turki Sultan Mansour Saleh Majed Rashid Bandar Haitham Hamza Kareem Zaid Samer Basil Ammar Mazen Nabil Wael Imad Jamal Sami Yasser Marwan Adel`,
      `Hassan Ibrahim Mahmoud Abdelrahman Said Saleh Salem Mansour Ali Khalil Naser Hamdy Fathy Zaki Ramadan Gamal Soliman Shaker Farag Moussa Nassar Awad Sabry Hegazy Elsayed Abdallah Al-Harbi Al-Ghamdi Al-Qahtani Al-Dosari Al-Shehri Al-Otaibi Al-Zahrani Al-Mutairi Al-Anazi Al-Subaie Al-Rashidi Al-Tamimi Al-Khalidi Al-Jubouri Al-Obaidi Al-Hashimi Al-Saadi Al-Maliki Al-Shammari Al-Dulaimi Abbas Younis Kamel Latif Haddad Rifai`,
    ),
    persian: P(
      `Mehdi Ali Reza Hossein Mohammad Amir Saeed Majid Ehsan Karim Alireza Sardar Omid Milad Masoud Payam Kaveh Arash Behnam Farhad Hamed Iman Javad Kamran Nima Peyman Shahin Siavash Vahid Yasin Younes Danial Mojtaba Morteza Saman Soheil Shervin Taha Ramin Pouria Farid Navid Babak Cyrus Dariush`,
      `Hosseini Mohammadi Ahmadi Rezaei Karimi Moradi Jafari Ghorbani Mousavi Hashemi Rahimi Kazemi Abbasi Zare Sadeghi Rostami Mirzaei Shahbazi Akbari Taheri Yazdani Bagheri Ebrahimi Khosravi Farhadi Nazari Ranjbar Zamani Soltani Heidari Mahdavi Jalali Fallah Daneshvar Shirazi Tabrizi Esfahani Ghasemi Habibi Karami Mehrabi Najafi Pourali Safavi`,
    ),
    sahel: P(
      `Mamadou Moussa Ibrahima Seydou Souleymane Boubacar Adama Abdoulaye Lassana Drissa Modibo Cheick Oumar Amadou Bakary Salif Sidiki Yacouba Aboubacar Mohamed Ousmane Karim Issa Idrissa Mahamadou Sékou Fodé Alpha Naby Sory Mory Kaba Lansana Facinet Daouda Tidiane Siaka Zakaria Hamidou Brehima Dramane`,
      `Traoré Keïta Coulibaly Diarra Konaté Diallo Sidibé Doumbia Sissoko Camara Dembélé Touré Cissé Koné Sangaré Bagayoko Sylla Soumaré Cissokho Kouyaté Diakité Fofana Bah Barry Baldé Sow Soumah Condé Bangoura Kourouma Tounkara Yattara Maïga Samaké Ouattara Sawadogo Zongo Kaboré Ouédraogo Compaoré Tapsoba Sanou Nikiema Sankara Bambara Zoungrana Yaméogo`,
    ),
    southafrican: P(
      `Thabo Sipho Themba Siyabonga Bongani Lungelo Mandla Sibusiso Thulani Lwazi Tshepo Kagiso Katlego Kabelo Lerato Neo Pule Teboho Tumelo Zola Vusi Mpho Itumeleng Lebohang Sandile Andile Luyanda Zakhele Bheki Dumisani Xolani Johan Pieter Francois Willem Hendrik Jaco Riaan Ruan Wian Dewald Mark Brandon Dylan Kyle Craig Gareth Dean`,
      `Dlamini Nkosi Khumalo Zulu Ndlovu Mokoena Mahlangu Sithole Mthembu Ngcobo Cele Radebe Mabaso Molefe Ntuli Zwane Mkhize Nxumalo Shabalala Mabena Tshabalala Maluleke Modise Mahlaba Sibiya Buthelezi Mazibuko Mdluli Msimang Ngwenya Nene Nhlapo Pillay Naidoo Govender van_der_Merwe Botha Pretorius du_Plessis Venter Coetzee Steyn Joubert Kruger Nel Swanepoel Fourie Jacobs Smit`,
    ),
    centralasian: P(
      `Jasur Sherzod Bobur Dostonbek Eldor Farrukh Otabek Rustam Shokhrukh Timur Sardor Azizbek Jamshid Javlon Odil Ulugbek Zafar Akmal Anvar Bekzod Davron Husan Islom Jahongir Komil Mirzo Nodir Sanjar Sultan Umid Ravshan Aziz Bakhtiyor Doniyor Elyor Ilkhom Kamol Laziz Murod Nurbek Oybek`,
      `Karimov Rashidov Yusupov Abdullayev Ismoilov Rakhimov Tursunov Nazarov Aliyev Mirzayev Saidov Kholmatov Umarov Sobirov Ergashev Khasanov Ibragimov Normatov Pulatov Qodirov Sultonov Turgunov Usmonov Valiyev Yuldashev Zokirov Azimov Boboev Davlatov Fayziev Gafurov Haydarov Jurayev Kadyrov Latipov Mamatov Narzullayev`,
    ),
    hebrew: P(
      `Yossi Moshe David Avi Eli Itay Omer Noam Eyal Guy Tomer Shahar Amit Yuval Ori Nir Dor Tal Lior Oren Ran Ido Idan Barak Gal Elad Ben Matan Roi Shlomi Rotem Eden Daniel Yoav Asaf Ofir Uri Rami Doron Nadav Ilan Tamir Yonatan`,
      `Cohen Levi Mizrahi Peretz Biton Dahan Avraham Friedman Malka Azoulay Katz Yosef Amar Shapira Hadad Gabay Ben_David Ohayon Dayan Bar Shalom Sasson Segal Nachmani Ashkenazi Golan Weiss Edri Mor Klein Stern Tal Barak Peled Navon Meir Zohar Rosen Biran Elkayam Hazan Ziv Alon Tamir Sharabi`,
    ),
    vietnamese: P(
      `Quang Hai Van Hau Cong Phuong Tien Linh Duc Chinh Hoang Duc Minh Vuong Tuan Anh Thanh Trung Hung Dung Nam Long Son Hieu Khanh Binh Dat Phuc Thang Tri Viet Bao Huy Kien Loc Nghia Quoc Tai Thinh Vinh Hoa Huynh Khoa Lam Phat Quan Tung Hoai Nhan Thien`,
      `Nguyen Tran Le Pham Hoang Huynh Phan Vu Vo Dang Bui Do Ho Ngo Duong Ly Dinh Doan Trinh Mai Truong Lam Luong Ta Dao Cao Ha Lu Tong Chau Quach Thai Kieu Phung Han To Tang Lac Diep Trieu Giang Banh Kim`,
    ),
    indonesian: P(
      `Egy Witan Evan Rizky Asnawi Pratama Marselino Ramadhan Elkan Justin Jordi Thom Ivar Rafael Shayne Yakob Ricky Marc Nadeo Sandy Arhan Ernando Zulfiandi Hansamu Fachruddin Bagas Dimas Rizal Hokky Ramai Beckham Ilham Andhika Arif Bayu Dedi Eko Fajar Gilang Hendra Irfan Joko Kurniawan Lukman Muhammad Nur Putra Rendy Syahrul Taufik Yudha Zaenal`,
      `Wijaya Santoso Saputra Pratama Kurniawan Nugroho Hidayat Setiawan Wibowo Susanto Firmansyah Ramadhan Hakim Permana Gunawan Maulana Putra Siregar Lubis Nasution Harahap Sitompul Simanjuntak Pane Hutagalung Sinaga Tambunan Manullang Purnomo Utomo Prasetyo Hartono Kusuma Lesmana Budiman Rahman Fauzi Salim Aziz Syahputra Mahendra Ardiansyah Prakoso Suryadi`,
    ),
    malay: P(
      `Safawi Faisal Syafiq Arif Aiman Dion Brendan Stuart Matthew Junior La'Vere Safuwan Syazwan Azam Hadi Akhyar Mukhairi Muhammad Danial Hakimi Irfan Zaquan Faiz Hafiz Shahrul Khairul Zulkifli Azri Amirul Rahim Nazmi Farhan Haziq Imran Luqman Norshahrul Rodzi Shamil Wan Zulhilmi Aidil Baddrol Hariss Kamal Mohd Nasrullah Syukur Zamir`,
      `Abdullah Ismail Rahman Hassan Ahmad Ibrahim Yusof Othman Aziz Hamid Karim Latif Mahmud Musa Omar Razak Salleh Salim Samad Zakaria Zain Daud Hashim Jamal Kassim Lazim Mansor Osman Rashid Saad Tahir Wahab Yahya Zulkifli Che Awang Bakar Hussein Idris Jaafar Kadir Lim Tan Wong Chong Raj Kumar Singh`,
    ),
    filipino: P(
      `Neil Stephan Javier Oliver Kevin Patrick Diego Michael Jesse Sandro Mike Daisuke Ruben Jaime Manny Paolo Carlo Marco Angelo Dennis Jerome Mark Jeric Jovelle Rhandy Raphael Adrian Bryan Christian Gerald Joshua Lorenz Nathan Ramon Ricardo Rodel Santiago Tomas Victor Alfonso Benedict Cedric Emilio Francis Gabriel Jericho`,
      `Reyes Santos Cruz Bautista Ocampo Garcia Mendoza Torres Tomas Andrada Castillo Flores Villanueva Ramos Aquino Dela_Cruz De_Leon Gonzales Hernandez Lopez Perez Rivera Salazar Soriano Aguilar Alvarez Bernardo Cabrera Domingo Enriquez Fernandez Guevarra Ignacio Javier Lim Magno Navarro Ortega Padilla Quizon Rosales Sison Tolentino Valdez Zamora`,
    ),
    // Singapore: Chinese, Malay and Indian families in the proportions of the island
    singaporean: P(
      `Ikhsan Hariss Safuwan Faris Irfan Shahdan Zulqarnaen Hafiz Amirul Danish Haziq Jun Wei Kai Jia Zhi Ryan Kieran Daniel Joshua Marcus Aaron Prakash Arun Vikram Sanjay Muhammad Ahmad Aiman Khairul Syafiq Adam Gabriel Nazrul Hami Song Yong Jordan Shawal Zulfahmi Harhys Lionel Bryan Darren Brandon Raj Dhanesh`,
      `Tan Lim Lee Ng Goh Teo Chua Koh Ong Wong Chong Yeo Ho Sim Chan Abdullah Rahman Ismail Hassan Yusof Ibrahim Sulaiman Ahmad Mohamed Pillai Nair Krishnan Singh Kumar Menon Sharma Fandi Bakar Said Zainal Lau Foo Quek Sng Ang Tay`,
    ),
    georgian: P(
      `Giorgi Davit Nikoloz Luka Levan Irakli Zurab Merab Vakhtang Tornike Lasha Mikheil Temur Aleksandre Beka Guram Revaz Shota Konstantine Tamaz Otar Badri Gela Gocha Kakha Soso Nika Saba Data Giga Mamuka Bidzina Archil Tengiz Zaza`,
      `Abashidze Bagrationi Chavchavadze Dadiani Eristavi Gurieli Japaridze Jgenti Khubuluri Kobakhidze Lordkipanidze Mgaloblishvili Nadiradze Orbeliani Pirtskhalava Qipiani Rurua Sanikidze Tabidze Tsereteli Ugrekhelidze Vachnadze Zhvania Meladze Svanidze Tvauri Chkheidze Davitashvili Mikeladze Khutsishvili Beridze Maisuradze Kapanadze Giorgadze Gelashvili Lomidze Tsiklauri Kiknadze Gogoladze Bregadze Chikovani Gogiashvili Janelidze`,
    ),
  });

  // ---------- The nations ----------
  // [code, name, flag, region, style, bias, culture, weight (% of the mix of a league abroad), ties (league nations their
  // players go to), colours, extra culture]
  const N = (code, name, flag, region, style, bias, pool, weight, ties, colors, extra) => ({
    code,
    name,
    flag,
    region,
    style,
    bias,
    pool,
    weight,
    ties,
    colors,
    extra,
  });
  const LIST = [
    N(
      'SWE',
      'Sweden',
      '🇸🇪',
      'EUR',
      'Organised and athletic',
      { strength: 1.5, stamina: 1, workRate: 1 },
      'nordic',
      0.9,
      ['DEN', 'NOR', 'ENG', 'GER', 'NED', 'BEL'],
      ['#FECC02', '#006AA7'],
    ),
    N(
      'UKR',
      'Ukraine',
      '🇺🇦',
      'EUR',
      'Technical and disciplined',
      { technique: 1.5, passing: 1, positioning: 1 },
      'eastslavic',
      0.8,
      ['GER', 'POL', 'ENG', 'CZE', 'TUR', 'BEL'],
      ['#FFD500', '#005BBB'],
    ),
    N(
      'ROU',
      'Romania',
      '🇷🇴',
      'EUR',
      'Skilful and streetwise',
      { technique: 1.5, dribbling: 1.2, composure: 0.8 },
      'romanian',
      0.6,
      ['ITA', 'ESP', 'GER', 'GRE', 'TUR'],
      ['#FCD116', '#002B7F'],
    ),
    N(
      'SVK',
      'Slovakia',
      '🇸🇰',
      'EUR',
      'Compact and hard-working',
      { workRate: 1.5, stamina: 1, tackling: 1 },
      'czech',
      0.35,
      ['CZE', 'AUT', 'POL', 'HUN', 'ITA'],
      ['#FFFFFF', '#0B4EA2'],
    ),
    N(
      'SVN',
      'Slovenia',
      '🇸🇮',
      'EUR',
      'Organised and resilient',
      { positioning: 1.5, stamina: 1, composure: 1 },
      'southslav',
      0.3,
      ['ITA', 'AUT', 'CRO', 'GER'],
      ['#FFFFFF', '#005DA4'],
    ),
    N(
      'BIH',
      'Bosnia and Herzegovina',
      '🇧🇦',
      'EUR',
      'Technical and proud',
      { technique: 1.5, vision: 1, passing: 1 },
      'southslav',
      0.6,
      ['GER', 'AUT', 'SUI', 'TUR', 'ITA', 'SRB', 'CRO'],
      ['#002F6C', '#FECB00'],
      'turkish',
    ),
    N(
      'ALB',
      'Albania',
      '🇦🇱',
      'EUR',
      'Fiery and physical',
      { strength: 1.5, workRate: 1.5, tackling: 1 },
      'albanian',
      0.45,
      ['ITA', 'GRE', 'SUI', 'GER', 'TUR'],
      ['#E41E20', '#000000'],
    ),
    N(
      'MKD',
      'North Macedonia',
      '🇲🇰',
      'EUR',
      'Wiry and combative',
      { workRate: 1.5, stamina: 1, tackling: 0.8 },
      'southslav',
      0.4,
      ['SRB', 'GRE', 'AUT', 'ITA', 'TUR'],
      ['#D20000', '#F8E92E'],
    ),
    N(
      'MNE',
      'Montenegro',
      '🇲🇪',
      'EUR',
      'Tall and tenacious',
      { strength: 1.5, stamina: 1, positioning: 1 },
      'southslav',
      0.4,
      ['SRB', 'CRO', 'ITA', 'AUT'],
      ['#C40308', '#D4AF37'],
    ),
    N(
      'BUL',
      'Bulgaria',
      '🇧🇬',
      'EUR',
      'Tough and combative',
      { strength: 1.2, tackling: 1, workRate: 1 },
      'eastslavic',
      0.45,
      ['GRE', 'TUR', 'ITA', 'CZE', 'ESP'],
      ['#FFFFFF', '#00966E'],
    ),
    N(
      'FIN',
      'Finland',
      '🇫🇮',
      'EUR',
      'Disciplined and willing',
      { stamina: 1.5, workRate: 1.5, composure: 0.8 },
      'finnish',
      0.35,
      ['SWE', 'NOR', 'DEN', 'ENG', 'GER'],
      ['#FFFFFF', '#003580'],
    ),
    N(
      'ISL',
      'Iceland',
      '🇮🇸',
      'EUR',
      'Fit and fearless',
      { stamina: 1.8, strength: 1.2, workRate: 1.2 },
      'icelandic',
      0.2,
      ['DEN', 'NOR', 'NED', 'BEL', 'ENG'],
      ['#02529C', '#DC1E35'],
    ),
    N(
      'NIR',
      'Northern Ireland',
      '🇬🇧',
      'ENG',
      'Spirited and physical',
      { workRate: 2, strength: 1.2, stamina: 1 },
      'irish',
      0.35,
      ['ENG', 'SCO', 'IRL'],
      ['#0B8043', '#FFFFFF'],
      'english',
    ),
    N(
      'GEO',
      'Georgia',
      '🇬🇪',
      'EUR',
      'Skilful and quick',
      { dribbling: 1.5, pace: 1, technique: 1 },
      'georgian',
      0.25,
      ['TUR', 'GER', 'GRE', 'POL', 'CZE'],
      ['#FFFFFF', '#E8112D'],
    ),
    N(
      'ISR',
      'Israel',
      '🇮🇱',
      'EUR',
      'Clever and combative',
      { vision: 1.2, workRate: 1.2, composure: 1 },
      'hebrew',
      0.3,
      ['ENG', 'GER', 'GRE', 'TUR', 'NED', 'BEL', 'AUT'],
      ['#FFFFFF', '#0038B8'],
    ),
    N(
      'RUS',
      'Russia',
      '🇷🇺',
      'EUR',
      'Strong and methodical',
      { strength: 1.5, positioning: 1, passing: 1 },
      'eastslavic',
      0.45,
      ['TUR', 'GER', 'ENG', 'POL', 'CZE', 'ESP'],
      ['#FFFFFF', '#D52B1E'],
    ),
    N(
      'CYP',
      'Cyprus',
      '🇨🇾',
      'EUR',
      'Technical and patient',
      { technique: 1, passing: 1, vision: 1 },
      'greek',
      0.3,
      ['GRE', 'ENG', 'TUR'],
      ['#FFFFFF', '#D57800'],
    ),
    N(
      'ALG',
      'Algeria',
      '🇩🇿',
      'AFR',
      'Skilful and quick',
      { dribbling: 2, technique: 1.5, pace: 1 },
      'maghrebi',
      0.8,
      ['FRA', 'BEL', 'ESP', 'ENG', 'POR', 'TUR'],
      ['#006233', '#FFFFFF'],
    ),
    N(
      'TUN',
      'Tunisia',
      '🇹🇳',
      'AFR',
      'Disciplined and compact',
      { positioning: 1.5, workRate: 1.2, tackling: 1 },
      'maghrebi',
      0.5,
      ['FRA', 'BEL', 'ITA', 'GER', 'TUR'],
      ['#E70013', '#FFFFFF'],
    ),
    N(
      'EGY',
      'Egypt',
      '🇪🇬',
      'AFR',
      'Technical and clever',
      { technique: 1.5, vision: 1.2, passing: 1 },
      'mashriq',
      0.5,
      ['ENG', 'TUR', 'BEL', 'ITA', 'GRE'],
      ['#CE1126', '#000000'],
    ),
    N(
      'CMR',
      'Cameroon',
      '🇨🇲',
      'AFR',
      'Powerful and athletic',
      { strength: 2, pace: 1.5, stamina: 1 },
      'centralafrican',
      0.7,
      ['FRA', 'BEL', 'ESP', 'ITA', 'POR', 'TUR', 'ENG'],
      ['#007A5E', '#CE1126'],
      'french',
    ),
    N(
      'COD',
      'DR Congo',
      '🇨🇩',
      'AFR',
      'Athletic and expressive',
      { pace: 1.8, strength: 1.5, dribbling: 1 },
      'centralafrican',
      0.7,
      ['BEL', 'FRA', 'ENG', 'TUR', 'POR'],
      ['#007FFF', '#F7D618'],
      'french',
    ),
    N(
      'MLI',
      'Mali',
      '🇲🇱',
      'AFR',
      'Quick and technical',
      { pace: 1.8, dribbling: 1.5, stamina: 1 },
      'sahel',
      0.6,
      ['FRA', 'BEL', 'ESP', 'ENG', 'TUR'],
      ['#14B53A', '#FCD116'],
    ),
    N(
      'BFA',
      'Burkina Faso',
      '🇧🇫',
      'AFR',
      'Tireless and quick',
      { stamina: 1.8, pace: 1.5, workRate: 1.2 },
      'sahel',
      0.45,
      ['FRA', 'BEL', 'TUR', 'ITA'],
      ['#EF2B2D', '#009E49'],
    ),
    N(
      'GUI',
      'Guinea',
      '🇬🇳',
      'AFR',
      'Athletic and direct',
      { pace: 1.5, strength: 1.5, stamina: 1 },
      'sahel',
      0.35,
      ['FRA', 'BEL', 'ENG', 'TUR', 'POR'],
      ['#CE1126', '#FCD116'],
    ),
    N(
      'CPV',
      'Cape Verde',
      '🇨🇻',
      'AFR',
      'Technical and tidy',
      { technique: 1.5, passing: 1.2, dribbling: 1 },
      'portuguese',
      0.25,
      ['POR', 'NED', 'ENG', 'FRA'],
      ['#003893', '#CF2027'],
    ),
    N(
      'RSA',
      'South Africa',
      '🇿🇦',
      'AFR',
      'Rhythmic and committed',
      { pace: 1.2, technique: 1.2, workRate: 1 },
      'southafrican',
      0.3,
      ['ENG', 'POR', 'ESP', 'USA'],
      ['#FFB81C', '#007A4D'],
      'english',
    ),
    N(
      'ANG',
      'Angola',
      '🇦🇴',
      'AFR',
      'Quick and creative',
      { pace: 1.5, dribbling: 1.5, technique: 1 },
      'portuguese',
      0.25,
      ['POR', 'BEL', 'BRA', 'FRA'],
      ['#CC092F', '#000000'],
    ),
    N(
      'CAN',
      'Canada',
      '🇨🇦',
      'NAM',
      'Fit and direct',
      { pace: 1.5, stamina: 1.2, strength: 1 },
      'english',
      0.4,
      ['ENG', 'USA', 'GER', 'FRA'],
      ['#D80621', '#FFFFFF'],
      'french',
    ),
    N(
      'CHI',
      'Chile',
      '🇨🇱',
      'SAM',
      'Pressing and fearless',
      { workRate: 1.8, stamina: 1.5, tackling: 1 },
      'latin',
      0.55,
      ['ESP', 'ITA', 'ARG', 'MEX', 'BRA', 'ENG'],
      ['#D52B1E', '#0039A6'],
    ),
    N(
      'PAR',
      'Paraguay',
      '🇵🇾',
      'SAM',
      'Gritty and defiant',
      { tackling: 1.5, strength: 1.2, workRate: 1.2 },
      'latin',
      0.45,
      ['ARG', 'BRA', 'ESP', 'MEX', 'ITA'],
      ['#D52B1E', '#0038A8'],
    ),
    N(
      'ECU',
      'Ecuador',
      '🇪🇨',
      'SAM',
      'Athletic and quick',
      { pace: 1.8, stamina: 1.5, strength: 1 },
      'latin',
      0.5,
      ['ESP', 'ARG', 'MEX', 'BRA', 'USA', 'BEL', 'ITA'],
      ['#FFD100', '#034EA2'],
    ),
    N(
      'PER',
      'Peru',
      '🇵🇪',
      'SAM',
      'Technical and patient',
      { technique: 1.5, passing: 1.2, vision: 1 },
      'latin',
      0.35,
      ['ESP', 'ARG', 'MEX', 'BRA', 'POR'],
      ['#D91023', '#FFFFFF'],
    ),
    N(
      'VEN',
      'Venezuela',
      '🇻🇪',
      'SAM',
      'Spirited and organised',
      { workRate: 1.5, stamina: 1.2, composure: 1 },
      'latin',
      0.35,
      ['ESP', 'ARG', 'MEX', 'ITA', 'BRA'],
      ['#7C0A02', '#FFCC00'],
    ),
    N(
      'CRC',
      'Costa Rica',
      '🇨🇷',
      'NAM',
      'Compact and quick',
      { pace: 1.2, stamina: 1.2, positioning: 1 },
      'latin',
      0.2,
      ['ESP', 'USA', 'MEX', 'ENG'],
      ['#CE1126', '#002B7F'],
    ),
    N(
      'JAM',
      'Jamaica',
      '🇯🇲',
      'NAM',
      'Powerful and rhythmic',
      { pace: 2, strength: 1.5, finishing: 0.8 },
      'caribbean',
      0.3,
      ['ENG', 'USA', 'SCO'],
      ['#FED100', '#009B3A'],
    ),
    N(
      'HON',
      'Honduras',
      '🇭🇳',
      'NAM',
      'Quick and direct',
      { pace: 1.5, stamina: 1, strength: 1 },
      'latin',
      0.3,
      ['USA', 'MEX', 'ESP'],
      ['#0073CF', '#FFFFFF'],
    ),
    N(
      'PAN',
      'Panama',
      '🇵🇦',
      'NAM',
      'Physical and organised',
      { strength: 1.5, tackling: 1, stamina: 1 },
      'latin',
      0.3,
      ['USA', 'MEX', 'ESP', 'BEL'],
      ['#D21034', '#005293'],
    ),
    N(
      'IRN',
      'Iran',
      '🇮🇷',
      'ASIA',
      'Organised and strong',
      { strength: 1.5, positioning: 1.2, composure: 1 },
      'persian',
      0.45,
      ['BEL', 'GER', 'ENG', 'TUR', 'POR', 'NED'],
      ['#FFFFFF', '#239F40'],
    ),
    N(
      'KSA',
      'Saudi Arabia',
      '🇸🇦',
      'ASIA',
      'Quick and technical',
      { pace: 1.2, technique: 1.5, dribbling: 1.2 },
      'mashriq',
      0.35,
      ['ESP', 'POR'],
      ['#006C35', '#FFFFFF'],
    ),
    N(
      'UZB',
      'Uzbekistan',
      '🇺🇿',
      'ASIA',
      'Disciplined and technical',
      { technique: 1.2, passing: 1.2, stamina: 1 },
      'centralasian',
      0.2,
      ['TUR', 'KOR', 'JPN', 'POL', 'CZE'],
      ['#1EB53A', '#0099B5'],
    ),
    N(
      'CHN',
      'China',
      '🇨🇳',
      'ASIA',
      'Hard-working and disciplined',
      { workRate: 1.5, stamina: 1.2, passing: 1 },
      'chinese',
      0.25,
      ['ENG', 'ESP', 'GER', 'JPN', 'KOR'],
      ['#DE2910', '#FFDE00'],
    ),
    N(
      'NZL',
      'New Zealand',
      '🇳🇿',
      'ASIA',
      'Direct and physical',
      { strength: 1.5, stamina: 1.2, workRate: 1.2 },
      'english',
      0.2,
      ['ENG', 'AUS', 'USA'],
      ['#FFFFFF', '#000000'],
      'pacific',
    ),
    N(
      'IRQ',
      'Iraq',
      '🇮🇶',
      'ASIA',
      'Skilful and passionate',
      { dribbling: 1.5, technique: 1.2, finishing: 0.8 },
      'mashriq',
      0.2,
      ['NED', 'GER', 'ENG', 'TUR', 'SWE'],
      ['#CE1126', '#007A3D'],
    ),
    N(
      'VIE',
      'Vietnam',
      '🇻🇳',
      'ASIA',
      'Quick and tireless',
      { pace: 1.2, stamina: 1.5, workRate: 1.2 },
      'vietnamese',
      0.15,
      ['THA', 'JPN', 'KOR', 'ENG'],
      ['#DA251D', '#FFCD00'],
    ),
    N(
      'IDN',
      'Indonesia',
      '🇮🇩',
      'ASIA',
      'Energetic and passionate',
      { pace: 1.2, stamina: 1.2, dribbling: 1.2 },
      'indonesian',
      0.18,
      ['NED', 'THA', 'JPN', 'KOR'],
      ['#CE1126', '#FFFFFF'],
    ),
    N(
      'MYS',
      'Malaysia',
      '🇲🇾',
      'ASIA',
      'Neat and enterprising',
      { pace: 1.2, passing: 1.2, workRate: 1 },
      'malay',
      0.12,
      ['THA', 'ENG', 'JPN', 'KOR'],
      ['#FFCC00', '#010066'],
    ),
    N(
      'PHI',
      'Philippines',
      '🇵🇭',
      'ASIA',
      'Resourceful and hard-working',
      { workRate: 1.5, stamina: 1.2, passing: 1 },
      'filipino',
      0.12,
      ['THA', 'ENG', 'USA', 'JPN'],
      ['#0038A8', '#CE1126'],
    ),
    N(
      'SGP',
      'Singapore',
      '🇸🇬',
      'ASIA',
      'Neat and disciplined',
      { passing: 1.2, composure: 1, workRate: 1.2 },
      'singaporean',
      0.1,
      ['MYS', 'THA', 'JPN', 'AUS'],
      ['#EF3340', '#FFFFFF'],
    ),
    N(
      'BLR',
      'Belarus',
      '🇧🇾',
      'EUR',
      'Disciplined and physical',
      { strength: 1.2, stamina: 1, workRate: 1 },
      'eastslavic',
      0.3,
      ['GER', 'POL', 'TUR', 'ENG', 'CZE'],
      ['#CF101A', '#007C30'],
    ),
    N(
      'BOL',
      'Bolivia',
      '🇧🇴',
      'SAM',
      'Hardy at altitude',
      { stamina: 1.5, strength: 1, workRate: 1 },
      'latin',
      0.3,
      ['ARG', 'ESP', 'BRA', 'MEX', 'POR'],
      ['#007934', '#F9E300'],
    ),
    N(
      'IND',
      'India',
      '🇮🇳',
      'ASIA',
      'Quick and technical',
      { technique: 1.2, pace: 1, dribbling: 1.2 },
      'southasian',
      0.3,
      ['ENG', 'ESP', 'POR', 'JPN', 'KOR', 'AUS'],
      ['#FF9933', '#138808'],
    ),
    N(
      'QAT',
      'Qatar',
      '🇶🇦',
      'ASIA',
      'Technical and well-drilled',
      { technique: 1.5, passing: 1, composure: 1 },
      'mashriq',
      0.3,
      ['ESP', 'POR', 'BEL', 'TUR'],
      ['#8A1538', '#FFFFFF'],
    ),
    N(
      'UAE',
      'United Arab Emirates',
      '🇦🇪',
      'ASIA',
      'Fast and attacking',
      { pace: 1.2, technique: 1.2, dribbling: 1 },
      'mashriq',
      0.3,
      ['ESP', 'POR', 'ENG', 'BEL'],
      ['#CE1126', '#FFFFFF'],
    ),
  ];

  // The nations join the game (a first-name and surname pool each, widened from the culture's)
  for (const n of LIST) {
    D.NATIONS[n.code] = { name: n.name, flag: n.flag, region: n.region, style: n.style, bias: n.bias, fn: [], ln: [] };
    D.NATIVE_POOL[n.code] = n.pool;
    if (n.extra) D.NATIVE_EXTRA[n.code] = [n.extra];
    D.NT_COLORS[n.code] = n.colors;
  }
  D.widenNames();

  // Their players are spread through the leagues with a mix: weight × where emigrants go (the ties count four times,
  // a league in the same part of the world a bit more than the rest)
  const regionOfLeagueNation = (nat) => (D.NATIONS[nat] ? D.NATIONS[nat].region : 'EUR');
  for (const l of D.LEAGUES) {
    const mix = D.NAT_MIX[l.id];
    if (!mix) continue;
    for (const n of LIST) {
      const same =
        regionOfLeagueNation(l.nat) === n.region || (n.region === 'ENG' && regionOfLeagueNation(l.nat) === 'EUR');
      const w = n.weight * (n.ties.includes(l.nat) ? 4 : same ? 1.2 : 0.35);
      mix[n.code] = Math.round(w * 100) / 100;
    }
  }
  D.NEW_NATIONS = LIST.map((n) => n.code);
})();
