// The name library behind tools/worldgen.mjs: how towns sound in each language group, how clubs and grounds are
// named there, and the native words for divisions and cups. Everything here is invented material in the manner of
// each language; none of it is a real club's name.
const words = (s) => s.trim().split(/\s+/);
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const rep = (list, n) => Array.from({ length: n }, () => list).flat(); // (weights: a pattern listed twice is twice as likely)
const VOWELS = 'aeiouyáéíóúàèìòùâêîôûäöüåæøãõ';
const isVowel = (c) => VOWELS.includes((c || '').toLowerCase());

export const LANG = {
  eng: {
    nations: 'ENG SCO WAL IRL AUS USA RSA GHA NGA',
    a: words(
      `Abing Ald Ames Ash Aston Bar Bay Beck Bed Bever Bex Birk Black Bourn Brad Bran Brent Brid Brom Buck Bur Bux Cal Cam
      Cans Car Chal Chel Chip Clay Cleve Clif Cob Col Cran Crew Croy Dal Dar Dart Dav Den Der Dor Dun Eden Elm Ep Ever Ex
      Fair Fal Farn Fen Fil Flit Fol Gain Gil Glas Glen Glos Gran Gren Had Hal Har Hart Has Hat Hay Hel Her Hex High Hin Hol
      Hor How Huck Hun Hyde Ing Ket Kes Kil Kirk Lam Lan Lang Lea Led Lew Lich Lin Lit Lud Lyme Mal Mans Mar Mel Mer Mid Mil
      Mor Nan Nor Oak Ol Ot Ox Pad Pen Pet Pick Ply Pres Pud Quar Rad Ram Rea Red Rey Rich Rip Rod Rom Ros Roth Rug Rus Rye
      Sal Sand Saw Scar Sed Sel Shaf Shep Shir Sop Spald Stam Stan Staf Sto Stow Strat Sud Sut Swan Tad Tam Tarn Tav Tet Thir
      Thorn Til Tiv Tod Tor Tun Tut Wad Wal War Wat Wed Wel Wend Wes Wex Whit Wick Wil Win Wis Wit Wok Wor Wrex Wyn Yar Yeo`,
    ),
    b: words(
      `ford ham ton bury field wick mouth chester worth by ley stead brook dale port minster wood combe bridge thorpe mere wold
      cliff haven gate borough well hurst don ney sea stow holm castle pool wich sey shall caster ington ingham`,
    ),
    elide: false,
    pre: [
      ...rep(['North', 'South', 'East', 'West'], 2),
      'Upper',
      'Lower',
      'Great',
      'Little',
      'Market',
      'Castle',
      'Church',
      "King's",
      "Bishop's",
      'Saint',
      'New',
      'Old',
    ],
    preGap: ' ',
    joins: ['-on-Sea', '-in-the-Marsh', '-le-Moors', '-by-the-Sea', '-on-the-Hill', '-on-Wold', '-under-Wood'],
    club: [
      ...rep(['{c} Town', '{c} City', '{c} United'], 3),
      ...rep(['{c} Athletic', '{c} Rovers'], 2),
      '{c} Albion',
      '{c} Wanderers',
      '{c} Rangers',
      '{c} County',
      '{c} Borough',
      '{c} Victoria',
      '{c} Orient',
      '{c} Argyle',
      '{c} Alexandra',
      '{c} Wednesday',
      '{c} Harriers',
      '{c} Villa',
      '{c} Rovers',
      'Athletic Club {c}',
    ],
    ground: [
      '{c} Park',
      '{x} Road',
      '{x} Lane',
      '{c} Ground',
      'The {x} Stadium',
      '{p} Park',
      '{x} Field',
      '{x} Park',
      '{x} Green',
    ],
    colours: {
      red: 'Reds',
      blue: 'Blues',
      white: 'Whites',
      black: 'Blacks',
      yellow: 'Yellows',
      green: 'Greens',
      orange: 'Oranges',
      claret: 'Maroons',
      sky: 'Sky Blues',
      navy: 'Navy',
    },
    misc: words(
      'Lions Eagles Wolves Rams Stags Kestrels Otters Badgers Herons Mariners Miners Ironmen Drovers Foresters Chargers Spartans Falcons',
    ),
    tiers: ['Premier Division', 'First Division', 'Second Division', 'Third Division', 'Fourth Division'],
    cup: 'Challenge Cup',
  },
  spa: {
    nations: 'ESP CHI COL VEN PER ECU BOL',
    link: 'aeo',
    a: words(
      `Alcal Almaz Arroy Benav Cabr Calat Casti Cerv Cord Corv Cuen Escal Frag Fresn Fuent Gand Guad Jarand Lerm Lior Mayor
      Medi Mont Nav Olm Oñat Orih Ped Peñ Pied Plas Pozo Quint Riba Robl Sepúlv Sor Tal Tord Torr Val Valde Vill Zafr Alba
      Aranj Bail Bena Calp Elch Gand Hinoj Luc Marb Moral Nerj Osun Palom Rond Salam Segov Tarif Úbed Valdem Yeste Zam`,
    ),
    b: words('a ara edo osa ares illa eda ejo ón al era ana ena ero ino anes ete ar ador ero iel'),
    elide: true,
    pre: [
      ...rep(['San', 'Santa', 'Villa', 'Puerto'], 2),
      'Alto',
      'Nueva',
      'Los',
      'Las',
      'El',
      'La',
      'Cerro',
      'Monte',
      'Torre',
      'Campo',
    ],
    preGap: ' ',
    preDe: 0.35, // "Villa de Navares"
    joins: [' del Mar', ' de la Sierra', ' del Valle', ' de Abajo', ' de Arriba'],
    club: [
      ...rep(['{c} CF', 'Deportivo {c}', 'Atlético {c}'], 2),
      'Sporting {c}',
      'Racing {c}',
      'Unión {c}',
      'Club {c}',
      'Real {c}',
      '{c} Balompié',
      'CD {c}',
      'UD {c}',
      '{c} Atlético',
      'Real Club {c}',
      '{c} Sporting Club',
      'Juventud {c}',
    ],
    ground: [
      'Estadio Municipal de {c}',
      'Estadio {x}',
      'Campo de {c}',
      'Estadio {p}',
      'Estadio La {x}',
      'Nuevo Estadio {c}',
      'Ciudad Deportiva {c}',
    ],
    colours: {
      red: 'Rojos',
      blue: 'Azules',
      white: 'Blancos',
      black: 'Negros',
      yellow: 'Amarillos',
      green: 'Verdes',
      orange: 'Naranjas',
      claret: 'Granates',
      sky: 'Celestes',
      navy: 'Azulones',
    },
    misc: words(
      'Leones Águilas Lobos Halcones Tiburones Toros Cóndores Jaguares Gladiadores Alacranes Mineros Marineros Venados',
    ),
    tiers: ['Liga de Honor', 'Liga de Plata', 'Liga Federal', 'Liga Regional', 'Liga Provincial'],
    cup: 'Copa de la Federación',
  },
  por: {
    nations: 'POR',
    link: 'aeo',
    a: words(
      `Alcob Alent Arga Ave Barc Bragan Cast Cov Elv Estr Fig Gouv Guim Lam Leir Lous Marv Matos Mir Moncor Ovar Pen Port Sant
      Sert Tom Torr Vil Alvor Amar Cart Ferr Gaia Lag Monch Nazar Oliv Paiv Pomb Sesim Tavir Valen Vend Vidig`,
    ),
    b: words('a ela ais eiro inha ouro ães al ão ares ura ada eira ela'),
    elide: true,
    pre: [...rep(['São', 'Santa', 'Vila', 'Porto'], 2), 'Nova', 'Praia', 'Serra', 'Ribeira', 'Alto', 'Campo', 'Boa'],
    preGap: ' ',
    preDe: 0.3,
    joins: [' do Mar', ' da Serra', ' do Vale', ' de Cima'],
    club: [
      ...rep(['{c} FC', 'Sporting {c}', 'Atlético {c}'], 2),
      'Clube {c}',
      '{c} EC',
      'Associação {c}',
      'Esporte Clube {c}',
      'Grémio {c}',
      'União {c}',
      'Racing {c}',
      '{c} Atlético Clube',
      'Sport Clube {c}',
      '{c} Futebol Clube',
    ],
    ground: [
      'Estádio {x}',
      'Estádio Municipal de {c}',
      'Arena {x}',
      'Estádio {p}',
      'Estádio Nova {x}',
      'Complexo Desportivo {c}',
    ],
    colours: {
      red: 'Rubro-Negros',
      blue: 'Azuis',
      white: 'Brancos',
      black: 'Pretos',
      yellow: 'Amarelos',
      green: 'Verdes',
      orange: 'Laranjas',
      claret: 'Grenás',
      sky: 'Celestes',
      navy: 'Azuis-Marinho',
    },
    misc: words('Leões Águias Lobos Tubarões Falcões Tigres Gaviões Onças Corvos Mineiros Marinheiros Veados'),
    tiers: ['Liga de Honra', 'Liga de Prata', 'Liga Federal', 'Liga Regional', 'Liga Distrital'],
    cup: 'Taça da Federação',
  },
  bra: {
    nations: 'BRA',
    link: 'aeo',
    a: words(
      `Ita Ipi Ibi Pira Jacar Gua Itapi Cari Mara Para Tiju Arapi Ubatu Guara Pindo Capi Cata Aracat Biri Camb Itaj Ipat Jabot Mogi
      Nhan Pitang Sant Tabo Uruc Vass`,
    ),
    b: words('ba pe ú ara ma iba guá ópolis ina tuba rama mirim açu ia ão ai'),
    elide: true,
    pre: [...rep(['São', 'Santa'], 3), 'Nova', 'Vila', 'Porto', 'Campo', 'Barra'],
    preGap: ' ',
    preDe: 0.2,
    joins: [' do Sul', ' do Norte', ' das Pedras', ' da Serra'],
    club: [
      ...rep(['{c} EC', 'Sport Clube {c}', 'Atlético {c}'], 2),
      '{c} FC',
      'Esporte Clube {c}',
      'Clube {c}',
      'Associação Atlética {c}',
      'Grêmio {c}',
      'União {c}',
      'Sociedade Esportiva {c}',
      'Racing {c}',
      '{c} Futebol Clube',
    ],
    ground: ['Estádio {x}', 'Arena {x}', 'Estádio Municipal de {c}', 'Estádio {p}', 'Estádio Novo {x}', 'Complexo {x}'],
    colours: {
      red: 'Rubro-Negros',
      blue: 'Azuis',
      white: 'Alvinegros',
      black: 'Pretos',
      yellow: 'Amarelos',
      green: 'Verdões',
      orange: 'Laranjas',
      claret: 'Grenás',
      sky: 'Celestes',
      navy: 'Azuis-Marinho',
    },
    misc: words('Leões Águias Lobos Tubarões Falcões Tigres Gaviões Onças Corvos Galos Jaguares Tucanos'),
    tiers: ['Liga Nacional', 'Liga Nacional B', 'Liga Nacional C', 'Liga Nacional D', 'Liga Nacional E'],
    cup: 'Copa da Federação',
  },
  mex: {
    nations: 'MEX',
    link: 'aeoi',
    a: words('Tlax Cuau Xal Teo Ahu Zac Tepo Ixt Chal Mix Tec Coat Hui Ocot Papan Tamp Uru Yau Zap Cuer Jil Pach Tul'),
    b: words('tlán pan co tepec hua lco catl chitlán pa tzin lán cán ec'),
    elide: true,
    pre: [...rep(['San', 'Santa'], 3), 'Villa', 'Nueva', 'Puerto', 'Ciudad'],
    preGap: ' ',
    preDe: 0.15,
    joins: [' de Allende', ' del Valle', ' de las Flores'],
    club: [
      ...rep(['Club {c}', 'Atlético {c}', 'Deportivo {c}'], 2),
      '{c} FC',
      'Unión {c}',
      'Club Deportivo {c}',
      '{c} Atlético',
      'Santos {c}',
      'Real {c}',
      'Halcones de {c}',
    ],
    ground: ['Estadio {x}', 'Estadio Municipal de {c}', 'Estadio {p}', 'Estadio Olímpico de {c}', 'Estadio La {x}'],
    colours: {
      red: 'Rojos',
      blue: 'Azules',
      white: 'Blancos',
      black: 'Negros',
      yellow: 'Amarillos',
      green: 'Verdes',
      orange: 'Naranjas',
      claret: 'Guindas',
      sky: 'Celestes',
      navy: 'Azulones',
    },
    misc: words('Leones Águilas Lobos Tigres Toros Jaguares Venados Alacranes Mineros Gallos Panteras Tuzos'),
    tiers: ['Liga Mayor', 'Liga de Ascenso', 'Liga de Expansión', 'Liga Regional', 'Liga Estatal'],
    cup: 'Copa de la Federación',
  },
  arg: {
    nations: 'ARG URU PAR',
    link: 'aeo',
    a: words(
      'Alver Bel Cabr Dorr Esc Fer Gar Her Lav Mir Pell Quir Rod Sar Tor Urq Vel Arr Bust Cast Dom Fran Lez Mol Ort Pues',
    ),
    b: words('ez o as ia ini ano ón ero ona illa eda ar ui'),
    elide: true,
    pre: [...rep(['General', 'Coronel'], 2), 'Presidente', 'Doctor', 'Villa', 'San', 'Santa', 'Puerto'],
    preGap: ' ',
    joins: [' del Plata', ' de los Arroyos', ' del Sur'],
    club: [
      ...rep(['Club Atlético {c}', 'Club Deportivo {c}', 'Atlético {c}'], 2),
      '{c} FC',
      'Club Social y Deportivo {c}',
      'Sportivo {c}',
      'Gimnasia de {c}',
      'Estudiantes de {c}',
      'Unión de {c}',
      'Racing de {c}',
      'Defensores de {c}',
      'Independiente {c}',
    ],
    ground: ['Estadio {x}', 'Estadio Municipal de {c}', 'Estadio {p}', 'Estadio Monumental {x}', 'Cancha de {c}'],
    colours: {
      red: 'Rojos',
      blue: 'Azules',
      white: 'Albos',
      black: 'Negros',
      yellow: 'Amarillos',
      green: 'Verdes',
      orange: 'Naranjas',
      claret: 'Granates',
      sky: 'Celestes',
      navy: 'Azulones',
    },
    misc: words('Leones Gauchos Lobos Halcones Pumas Toros Cóndores Tigres Pampas Arrieros Matadores'),
    tiers: ['Liga Mayor', 'Primera B Nacional', 'Primera C', 'Primera D', 'Liga Federal'],
    cup: 'Copa de la Federación',
  },
  ger: {
    nations: 'GER AUT SUI',
    a: words(
      `Alt Bach Berg Bran Dorn Eich Els Frei Furt Gold Grün Hag Heid Hohen Holz Kirch Kron Lind Lüt Mühl Nieder Ober Rhein Rot
      Schwarz Stein Thal Wald Wester Wies Zell Burg Hirsch Ahr Bruch Dill Eber Fels Greif Hain Imm Kal Lang Marien Neckar`,
    ),
    b: words(
      'burg berg stadt feld bach dorf heim hafen au kirchen tal hausen see ingen furt stein brück hof wald horst weiler',
    ),
    elide: false,
    pre: ['Bad', 'Neu', 'Alt', 'Ober', 'Unter', 'Hohen', 'Groß', 'Klein'],
    preGap: ' ',
    joins: [' am See', ' im Tal', ' an der Au', ' am Berg'],
    club: [
      ...rep(['SV {c}', 'FC {c}', 'TSV {c}'], 2),
      '{c} SC',
      'FSV {c}',
      'VfB {c}',
      'VfL {c}',
      'Sportfreunde {c}',
      'SpVgg {c}',
      '{c} 04',
      'Fortuna {c}',
      'Eintracht {c}',
      'Union {c}',
      'Viktoria {c}',
      'Teutonia {c}',
      '{c} 1899',
      'Germania {c}',
    ],
    ground: [
      '{c}-Arena',
      'Stadion {x}',
      '{x}-Stadion',
      'Sportpark {x}',
      'Stadion am {x}',
      '{p}-Stadion',
      'Waldstadion {c}',
    ],
    colours: {
      red: 'Roten',
      blue: 'Blauen',
      white: 'Weißen',
      black: 'Schwarzen',
      yellow: 'Gelben',
      green: 'Grünen',
      orange: 'Orangen',
      claret: 'Weinroten',
      sky: 'Himmelblauen',
      navy: 'Dunkelblauen',
    },
    misc: words('Löwen Adler Wölfe Füchse Falken Bären Bergleute Hirsche Schmiede Fischer Ritter Pioniere'),
    tiers: ['Hauptliga', 'Zweite Hauptliga', 'Dritte Liga', 'Vierte Liga', 'Fünfte Liga'],
    cup: 'Verbandspokal',
  },
  nld: {
    nations: 'NED BEL',
    a: words(
      'Oost West Noord Zuid Hoog Laag Groot Klein Nieuw Oud Berg Dijk Veen Haar Wage Zaan Bred Alk Deven Gron Hoorn Leid Maas Sneek Til Vlaar Zwol',
    ),
    b: words('dam burg hoven stad dijk veen wijk brug horst kerk lo rade zand voort waard hout beek'),
    elide: false,
    pre: ['Oud', 'Nieuw', 'Groot', 'Klein', 'Sint'],
    preGap: ' ',
    joins: [' aan Zee', ' aan de Maas'],
    club: [
      ...rep(['FC {c}', 'SC {c}', 'VV {c}'], 2),
      'RKC {c}',
      'KV {c}',
      'Sparta {c}',
      'AFC {c}',
      'ADO {c}',
      '{c} Boys',
      'Victoria {c}',
      'Racing {c}',
      '{c} Vooruit',
      'Eendracht {c}',
    ],
    ground: ['{x} Stadion', 'Stadion {x}', '{c} Arena', 'De {x}', '{p} Stadion', 'Sportpark {x}'],
    colours: {
      red: 'Rooien',
      blue: 'Blauwen',
      white: 'Witten',
      black: 'Zwarten',
      yellow: 'Geelen',
      green: 'Groenen',
      orange: 'Oranjes',
      claret: 'Bordeauxen',
      sky: 'Hemelsblauwen',
      navy: 'Donkerblauwen',
    },
    misc: words('Leeuwen Arenden Wolven Valken Stieren Zwanen Ruiters Kikkers Spechten Bijen'),
    tiers: ['Eerste Klasse', 'Tweede Klasse', 'Derde Klasse', 'Vierde Klasse', 'Vijfde Klasse'],
    cup: 'Federatiebeker',
  },
  nor: {
    nations: 'DEN NOR SWE FIN ISL',
    a: words(
      'Nord Syd Øst Vest Stor Lille Ny Gammel Fjord Skov Berg Dal Strand Bro Hav Sol Ring Sønder Lang Hol Ål Ask Bjørn Dyr Fre Hed Kil Mar Nes',
    ),
    b: words('by borg sund vik næs holm lund strup gård løkke fors dal vang stad rud ø'),
    elide: false,
    pre: ['Nord', 'Sønder', 'Øster', 'Vester', 'Ny', 'Gamle'],
    preGap: '',
    joins: [],
    club: [
      ...rep(['{c} IF', '{c} FK', 'FC {c}'], 2),
      'IK {c}',
      '{c} BK',
      '{c} Boldklub',
      'BK {c}',
      '{c} IL',
      'Fremad {c}',
      '{c} Fotball',
    ],
    ground: ['{x} Stadion', '{c} Arena', '{x} Park', '{p} Stadion', '{x} Idrætspark', '{c} Idrætsanlæg'],
    colours: {
      red: 'De Røde',
      blue: 'De Blå',
      white: 'De Hvide',
      black: 'De Sorte',
      yellow: 'De Gule',
      green: 'De Grønne',
      orange: 'De Orange',
      claret: 'De Mørkerøde',
      sky: 'De Lyseblå',
      navy: 'De Mørkeblå',
    },
    misc: words('Løver Ørne Ulve Bjørne Falke Elge Vikinger Svaner Rever Bæverne'),
    tiers: ['Topliga', 'Første Division', 'Anden Division', 'Tredje Division', 'Fjerde Division'],
    cup: 'Forbundspokal',
  },
  fra: {
    nations: 'FRA MAR ALG TUN SEN CIV CMR COD MLI BFA GUI',
    a: words(
      `Aub Bel Cha Dur Fon Lan Mon Nan Pon Roc Tour Vil Val Mar Bour Beau Cler Cour Lav Mont Cher Ar Dam Blan Cass Dieu Gren
      Joy Lun Mir Pau Quim Rib Sar Tho Vend`,
    ),
    b: words('ville mont eau court ac ens ay on lac gnan lieu bourg ières ac ault ange'),
    elide: false,
    pre: [...rep(['Saint-', 'Sainte-'], 3), 'Mont-', 'Pont-', 'Château-', 'Port-', 'Beau-', 'Villeneuve-'],
    preGap: '',
    joins: ['-sur-Mer', '-les-Bains', '-sur-Aure', '-en-Vallée', '-lès-Bois'],
    club: [
      ...rep(['FC {c}', 'AS {c}', 'US {c}'], 2),
      'Stade {c}',
      '{c} FC',
      'RC {c}',
      'AJ {c}',
      'SC {c}',
      'Athlétic {c}',
      'ES {c}',
      'Étoile de {c}',
      'Racing {c}',
      'Union {c}',
    ],
    ground: [
      'Stade {x}',
      'Stade Municipal de {c}',
      'Parc des Sports de {c}',
      'Stade {p}',
      'Stade de la {x}',
      'Complexe {x}',
    ],
    colours: {
      red: 'Rouges',
      blue: 'Bleus',
      white: 'Blancs',
      black: 'Noirs',
      yellow: 'Jaunes',
      green: 'Verts',
      orange: 'Oranges',
      claret: 'Grenats',
      sky: 'Ciel et Blancs',
      navy: 'Marines',
    },
    misc: words('Lions Aigles Loups Faucons Cerfs Lynx Cigognes Mineurs Dragons Marins Forgerons Pionniers'),
    tiers: [
      'Division Nationale',
      'Division Nationale 2',
      'Division Nationale 3',
      'Division Nationale 4',
      'Division Nationale 5',
    ],
    cup: 'Coupe de la Fédération',
  },
  ita: {
    nations: 'ITA',
    link: 'aeo',
    a: words(
      `Alba Bor Cas Fer Gal Lan Mon Pie Rav Sant Tor Ven Vil Ser Mar San Val Bel Pon Rocca Cor Mir Fos Frasc Mod Pad
      Amal Arez Cest Fabri Gubb Lecc Orvi Pesc Sass Tren`,
    ),
    b: words('ino ara ento ola etto ate ana ello ona ezia ago ia ano ale one ucci ara'),
    elide: true,
    pre: [...rep(['San', 'Santa', 'Monte', 'Castel'], 2), 'Porto', 'Villa', 'Borgo', 'Torre'],
    preGap: ' ',
    joins: [' sul Mare', ' di Sotto', ' al Monte'],
    club: [
      ...rep(['{c} Calcio', 'AC {c}', 'US {c}'], 2),
      'Unione {c}',
      '{c} 1908',
      'Virtus {c}',
      'ASD {c}',
      'Atletico {c}',
      'SSC {c}',
      'FC {c}',
      'Sporting {c}',
      'Pro {c}',
      'Audace {c}',
    ],
    ground: [
      'Stadio {x}',
      'Stadio Comunale di {c}',
      'Stadio {p}',
      'Stadio Nuovo {x}',
      'Arena {x}',
      'Stadio Civico di {c}',
    ],
    colours: {
      red: 'Rossi',
      blue: 'Azzurri',
      white: 'Bianchi',
      black: 'Neri',
      yellow: 'Gialli',
      green: 'Verdi',
      orange: 'Arancioni',
      claret: 'Granata',
      sky: 'Celesti',
      navy: 'Blu',
    },
    misc: words('Leoni Aquile Lupi Falchi Grifoni Tori Cavalieri Minatori Marinai Cervi Fabbri Pionieri'),
    tiers: ['Campionato Nazionale', 'Campionato Cadetto', 'Terza Divisione', 'Quarta Divisione', 'Quinta Divisione'],
    cup: 'Coppa della Federazione',
  },
  pol: {
    nations: 'POL',
    a: words(
      'Biał Brzez Chełm Dąbr Gnie Jaros Kal Lub Mław Nowo Opol Pił Rad Siedl Tarn Wło Zam Brodn Czar Gorz Kost Ostr Płoc Rybn Słup Wiel',
    ),
    b: words('ów ice in ka ówka owice ewo ów sk no a ec'),
    elide: true,
    link: 'oe',
    pre: ['Nowy', 'Stary', 'Górny', 'Dolny', 'Wielki'],
    preGap: ' ',
    joins: [],
    club: [
      ...rep(['KS {c}', 'MKS {c}', '{c} FC'], 2),
      'GKS {c}',
      'LKS {c}',
      'Stal {c}',
      'Górnik {c}',
      'Ruch {c}',
      'Zagłębie {c}',
      'Polonia {c}',
      '{c} Sokół',
      'Unia {c}',
      'Znicz {c}',
    ],
    ground: ['Stadion Miejski im. {p}', 'Stadion {x}', 'Arena {x}', 'Stadion im. {p}', 'Stadion Ludowy {c}'],
    colours: {
      red: 'Czerwoni',
      blue: 'Niebiescy',
      white: 'Biali',
      black: 'Czarni',
      yellow: 'Żółci',
      green: 'Zieloni',
      orange: 'Pomarańczowi',
      claret: 'Bordowi',
      sky: 'Błękitni',
      navy: 'Granatowi',
    },
    misc: words('Orły Wilki Lwy Sokoły Żubry Niedźwiedzie Górnicy Husaria Kosynierzy Rycerze'),
    tiers: ['Liga Główna', 'Liga Pierwsza', 'Liga Druga', 'Liga Trzecia', 'Liga Czwarta'],
    cup: 'Puchar Federacji',
  },
  cze: {
    nations: 'CZE',
    a: words(
      'Bran Hrad Jab Kar Lib Mlad Nym Olom Pard Prost Roky Stra Tren Vsetín Zlín Boh Doub Hol Kost Lys Pelh Rych Sed Vys',
    ),
    b: words('ice ov any ín ec ná ná dov ice ava ice ov'),
    elide: true,
    link: 'oe',
    pre: ['Nový', 'Starý', 'Horní', 'Dolní', 'Velký'],
    preGap: ' ',
    joins: [],
    club: [
      ...rep(['FK {c}', 'SK {c}', 'FC {c}'], 2),
      'Slavoj {c}',
      'Sokol {c}',
      'Baník {c}',
      '{c} Slovan',
      'Viktoria {c}',
      'Dynamo {c}',
      'TJ {c}',
      '1. FC {c}',
    ],
    ground: ['Stadion {x}', 'Městský stadion {c}', 'Letní stadion {c}', 'Stadion u {x}', 'Aréna {x}'],
    colours: {
      red: 'Červení',
      blue: 'Modří',
      white: 'Bílí',
      black: 'Černí',
      yellow: 'Žlutí',
      green: 'Zelení',
      orange: 'Oranžoví',
      claret: 'Vínoví',
      sky: 'Nebesky modří',
      navy: 'Námořníci',
    },
    misc: words('Lvi Orli Vlci Sokoli Medvědi Horníci Husité Rytíři Kováři Býci'),
    tiers: ['První Liga', 'Druhá Liga', 'Třetí Liga', 'Čtvrtá Liga', 'Pátá Liga'],
    cup: 'Pohár Federace',
  },
  hun: {
    nations: 'HUN',
    a: words('Bak Csaj Dab Gyön Hajd Kisv Nagy Ors Pász Sár Szarv Tisz Vesz Zala Bar Dun Fehér Győr Kál Lőr Mez Rác'),
    b: words('háza falva vár szeg ád ény lak ó hegy kert város telek'),
    elide: true,
    link: 'ae',
    pre: ['Kis', 'Nagy', 'Felső', 'Alsó', 'Új'],
    preGap: '',
    joins: [],
    club: [
      ...rep(['{c} FC', '{c} SE', '{c} SC'], 2),
      '{c} TE',
      '{c} VSC',
      '{c} Futball Club',
      'FC {c}',
      '{c} AC',
      '{c} Atlétikai Klub',
      'Egyetértés {c}',
      '{c} Sport Egylet',
    ],
    ground: ['{x} Stadion', '{c} Városi Stadion', '{x} Aréna', '{p} Stadion', '{c} Sportpálya'],
    colours: {
      red: 'Vörösök',
      blue: 'Kékek',
      white: 'Fehérek',
      black: 'Feketék',
      yellow: 'Sárgák',
      green: 'Zöldek',
      orange: 'Narancsok',
      claret: 'Bordók',
      sky: 'Égszínkékek',
      navy: 'Sötétkékek',
    },
    misc: words('Oroszlánok Sasok Farkasok Sólymok Bikák Medvék Bányászok Huszárok Kovácsok Lovagok'),
    tiers: ['Első Osztály', 'Második Osztály', 'Harmadik Osztály', 'Negyedik Osztály', 'Ötödik Osztály'],
    cup: 'Szövetségi Kupa',
  },
  gre: {
    nations: 'GRE',
    a: words('Ag Alex Arg Chal Kal Kor Lar Mes Nik Pat Pir Ser Thes Tri Xan Ioan Kav Kyp Lam Mar Nax Pel'),
    b: words('ópoli ina os ia ikos ás aki ida ópetra ouli ánia'),
    elide: true,
    link: 'oa',
    pre: ['Ágios', 'Néa', 'Palaiá', 'Ano', 'Kato'],
    preGap: ' ',
    joins: [],
    club: [
      ...rep(['AO {c}', 'AE {c}', '{c} FC'], 2),
      'PAE {c}',
      'GS {c}',
      'Panathlitikos {c}',
      'Ethnikos {c}',
      'Apollon {c}',
      'Doxa {c}',
      'Niki {c}',
    ],
    ground: ['Stadio {x}', 'Dimotiko Stadio {c}', '{x} Arena', 'Stadio {p}', 'Ethniko Stadio {c}'],
    colours: {
      red: 'Kókkinoi',
      blue: 'Galázioi',
      white: 'Áspri',
      black: 'Mávroi',
      yellow: 'Kítrinoi',
      green: 'Prásinoi',
      orange: 'Portokalí',
      claret: 'Kókkino Krasí',
      sky: 'Ouránioi',
      navy: 'Mple',
    },
    misc: words('Léontes Aetoí Lýkoi Ierakes Taýroi Delfínia Nautikoí Ypsilánti Spartiátes Titánes'),
    tiers: ['Alfa Liga', 'Beta Liga', 'Gamma Liga', 'Delta Liga', 'Epsilon Liga'],
    cup: 'Federation Kypello',
  },
  slav: {
    nations: 'SRB ROU SVK SVN BUL CRO BIH UKR RUS',
    a: words(
      `Bor Dra Gor Kra Lub Mal Nov Pol Rad Sla Tar Vel Zag Bel Ples Brat Kos Mir Zel Bog Doln Hrad Jas Kam Lipt Mik Ost
      Pet Ryb Slav Tur Vys`,
    ),
    b: words('ovo grad ice ava ina ovac ica ek in pol ec any ovice ik'),
    elide: false,
    pre: ['Novi', 'Stari', 'Gornji', 'Donji', 'Veliki', 'Mali', 'Nova', 'Stara'],
    preGap: ' ',
    joins: [],
    club: [
      ...rep(['FK {c}', 'SK {c}', 'FC {c}'], 2),
      '{c} Sokol',
      'Slavia {c}',
      'KS {c}',
      'NK {c}',
      'Union {c}',
      'MFK {c}',
      'AO {c}',
      'Lokomotiva {c}',
      'Zora {c}',
    ],
    ground: ['Stadion {x}', '{x} Arena', 'Gradski Stadion {c}', 'Stadion {p}', '{c} Park', 'Stadion Mir {c}'],
    colours: {
      red: 'Crveni',
      blue: 'Plavi',
      white: 'Beli',
      black: 'Crni',
      yellow: 'Žuti',
      green: 'Zeleni',
      orange: 'Narandžasti',
      claret: 'Bordo',
      sky: 'Svetloplavi',
      navy: 'Tamnoplavi',
    },
    misc: words('Orlovi Vukovi Lavovi Sokolovi Medvedi Zmajevi Gavranovi Bikovi Rakete Baroni'),
    tiers: ['Prva Liga', 'Druga Liga', 'Treća Liga', 'Četvrta Liga', 'Peta Liga'],
    cup: 'Savezni Kup',
  },
  tur: {
    nations: 'TUR',
    a: words(
      'Ak Bay Çam Dem Kar Mer Öz Sar Tek Yeni Gül Esk Kız Boz Kara Sultan Ali Yal Ayd Çan Dur Gön İnc Kay Orh Tav Uşa',
    ),
    b: words('ova ehir köy pınar tepe kale lar saray bahçe dere'),
    elide: true,
    pre: ['Yeni', 'Eski', 'Büyük', 'Küçük'],
    preGap: ' ',
    joins: [],
    club: [
      ...rep(['{c}spor', '{c} Belediyespor', '{c} SK'], 2),
      '{c} FK',
      'Yeni {c}spor',
      '{c} Gençlik',
      '{c} İdman Yurdu',
      '{c} Atletik',
      '{c} Gücü',
      '{c}gücü',
      '{c} Birlik',
    ],
    ground: ['{x} Stadyumu', '{c} Şehir Stadyumu', '{p} Stadyumu', '{x} Arena', '{c} Cumhuriyet Stadyumu'],
    colours: {
      red: 'Kırmızılar',
      blue: 'Mavililer',
      white: 'Beyazlar',
      black: 'Siyahlar',
      yellow: 'Sarılar',
      green: 'Yeşiller',
      orange: 'Turuncular',
      claret: 'Bordolar',
      sky: 'Gökler',
      navy: 'Lacivertler',
    },
    misc: words('Aslanlar Kartallar Kurtlar Şahinler Boğalar Akbabalar Atmacalar Yıldızlar Kaplanlar Ejderler'),
    tiers: ['Birinci Lig', 'İkinci Lig', 'Üçüncü Lig', 'Dördüncü Lig', 'Beşinci Lig'],
    cup: 'Federasyon Kupası',
  },
  jpn: {
    nations: 'JPN',
    a: words(
      'Aka Hoku Kawa Miya Naga Oka Sai Taka Yama Kita Minami Shin Higashi Nishi Fuji Sakura Take Haru Aki Nari Asa Ina Kuro Mats Oga Toy',
    ),
    b: words('saki gawa moto hama yama shima mori kami ta no ura hara zawa'),
    elide: false,
    pre: ['Kita', 'Minami', 'Higashi', 'Nishi', 'Shin'],
    preGap: '',
    joins: [],
    club: [
      ...rep(['{c} FC', '{c} United', '{c} Athletic'], 2),
      '{c} Sport Club',
      '{c} City',
      'FC {c}',
      '{c} Verde',
      '{c} Blaze',
      '{c} Sevens',
      '{c} Phoenix',
      '{c} Vortex',
    ],
    ground: ['{x} Stadium', '{c} Athletic Stadium', '{x} Arena', '{x} Park', '{c} Sports Complex'],
    colours: {
      red: 'Reds',
      blue: 'Blues',
      white: 'Whites',
      black: 'Blacks',
      yellow: 'Yellows',
      green: 'Greens',
      orange: 'Oranges',
      claret: 'Crimsons',
      sky: 'Sky Blues',
      navy: 'Navy',
    },
    misc: words('Dragons Tigers Phoenixes Hawks Wolves Samurai Warriors Cranes Bears Typhoons'),
    tiers: ['Premier League', 'Division 1', 'Division 2', 'Division 3', 'Regional League'],
    cup: 'National Cup',
  },
  kor: {
    nations: 'KOR CHN',
    a: words('Dae Gang Hae Chung Jeon Gyeong Nam Bu Jin Chun Seo Pyeong Dong Wol Sin Mun Ban Bo Cho Gim'),
    b: words('gu ju san cheon jeong seong ri yang won jin dong hwa'),
    elide: false,
    pre: [],
    preGap: '',
    joins: [],
    club: [
      ...rep(['{c} FC', '{c} United', '{c} Citizen'], 2),
      '{c} Dolphins',
      'FC {c}',
      '{c} Athletic',
      '{c} Stars',
      '{c} Tigers',
    ],
    ground: ['{c} Stadium', '{x} Sports Complex', '{x} Arena', '{c} Civic Stadium'],
    colours: {
      red: 'Reds',
      blue: 'Blues',
      white: 'Whites',
      black: 'Blacks',
      yellow: 'Yellows',
      green: 'Greens',
      orange: 'Oranges',
      claret: 'Crimsons',
      sky: 'Sky Blues',
      navy: 'Navy',
    },
    misc: words('Tigers Dragons Eagles Dolphins Hawks Bears Phoenixes Wolves'),
    tiers: ['Premier League', 'First League', 'Second League', 'Third League', 'Regional League'],
    cup: 'National Cup',
  },
  tha: {
    nations: 'THA IND IDN VIE MYS UZB IRN KSA QAT UAE IRQ',
    a: words('Ban Chiang Nakhon Sri Phra Lam Pak Ubon Sing Mae Nong Kao Phu Tha Wang Khao Bang Rat Sak Tak'),
    b: words('buri pur mai nong kaeo chan ra sai yai thong lek nam'),
    elide: false,
    pre: [],
    preGap: '',
    joins: [],
    club: [
      ...rep(['{c} United', 'FC {c}', '{c} City'], 2),
      '{c} Athletic',
      '{c} FC',
      'Muang {c}',
      '{c} Rangers',
      '{c} Mariners',
    ],
    ground: ['{x} Stadium', '{c} Provincial Stadium', '{x} Arena', '{x} Sports Park'],
    colours: {
      red: 'Reds',
      blue: 'Blues',
      white: 'Whites',
      black: 'Blacks',
      yellow: 'Yellows',
      green: 'Greens',
      orange: 'Oranges',
      claret: 'Crimsons',
      sky: 'Sky Blues',
      navy: 'Navy',
    },
    misc: words('Elephants Tigers Eagles Dragons Cobras Hornbills Lions Panthers'),
    tiers: ['Premier League', 'Division 1', 'Division 2', 'Division 3', 'Regional League'],
    cup: 'Champions Cup',
  },
};
export const TIERS_BY = {
  CZE: ['První Liga', 'Druhá Liga', 'Třetí Liga', 'Čtvrtá Liga'],
  SVK: ['První Liga', 'Druhá Liga', 'Třetí Liga'],
  POL: ['Liga Główna', 'Liga Pierwsza', 'Liga Druga', 'Liga Trzecia'],
  HUN: ['Első Osztály', 'Második Osztály', 'Harmadik Osztály'],
  GRE: ['Alfa Liga', 'Beta Liga', 'Gamma Liga'],
  ROU: ['Liga Întâi', 'Liga a Doua', 'Liga a Treia'],
  SUI: ['Super Liga', 'Challenge Liga', 'Promotion Liga'],
  AUT: ['Bundesstaffel', 'Zweite Bundesstaffel', 'Regionalliga'],
};
export const CUP_BY = {
  CZE: 'Pohár Federace',
  SVK: 'Pohár Federácie',
  POL: 'Puchar Federacji',
  HUN: 'Szövetségi Kupa',
  GRE: 'Federation Kypello',
  ROU: 'Cupa Federației',
};
export const langOf = (nat) => Object.values(LANG).find((l) => l.nations.split(' ').includes(nat)) || LANG.eng;

// ---------------------------------------------------------------- town names
// Stems and endings are joined with the sounds kept tidy (no clashing vowels where the language elides, no triple
// letters); some towns take a prefix ("Upper", "San", "Saint-") or a join ("-on-Sea", " del Mar"), in the way
// real place names do. Returns a town name.
export function stem(L, r) {
  let a = r.pick(L.a),
    b = r.pick(L.b);
  if (L.elide && isVowel(a.slice(-1)) && isVowel(b[0])) a = a.slice(0, -1);
  if (a.slice(-1).toLowerCase() === b[0].toLowerCase() && !isVowel(b[0])) b = b.slice(1);
  if (L.link && !isVowel(a.slice(-1)) && !isVowel(b[0])) a += L.link[Math.floor(r() * L.link.length)];
  return cap(a + b).replace(/(.)\1\1+/g, '$1$1');
}
export function placeName(L, r) {
  const roll = r();
  let s = stem(L, r);
  if (roll < 0.1 && L.pre.length) {
    const p = r.pick(L.pre);
    s =
      L.preDe && r() < L.preDe
        ? `${p} de ${s}`
        : `${p}${L.preGap}${L.preGap || p.endsWith('-') ? s : s.charAt(0).toLowerCase() + s.slice(1)}`;
  } else if (roll < 0.15 && L.joins.length) s += r.pick(L.joins);
  return s;
}
